/**
 * API-59 SIM Status
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 12.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.simStatus;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Response object with status boolean
 **/
//TODO: add to realm migration
public class SIMStatusEBUSuccess extends RealmObject {

  @PrimaryKey
  private long primaryKey;
  @SerializedName("isActiv")
  private Boolean isActiv = null;
  @SerializedName("productId")
  private String productId = null;
  @SerializedName("productSpecName")
  private String productSpecName = null;

  public SIMStatusEBUSuccess() {
    this.primaryKey = 1;
  }

  /**
   * boolean type
   **/
  @ApiModelProperty(value = "boolean type")
  public Boolean getIsActiv() {
    return isActiv;
  }
  public void setIsActiv(Boolean isActiv) {
    this.isActiv = isActiv;
  }

  /**
   * ProductSpecCid from getAssignProductResponse
   **/
  @ApiModelProperty(value = "ProductSpecCid from getAssignProductResponse")
  public String getProductId() {
    return productId;
  }
  public void setProductId(String productId) {
    this.productId = productId;
  }

  /**
   * ProductSpecName from getAssignProductResponse
   **/
  @ApiModelProperty(value = "ProductSpecName from getAssignProductResponse")
  public String getProductSpecName() {
    return productSpecName;
  }
  public void setProductSpecName(String productSpecName) {
    this.productSpecName = productSpecName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SIMStatusEBUSuccess sIMStatusEBUSuccess = (SIMStatusEBUSuccess) o;
    return (this.isActiv == null ? sIMStatusEBUSuccess.isActiv == null : this.isActiv.equals(sIMStatusEBUSuccess.isActiv)) &&
        (this.productId == null ? sIMStatusEBUSuccess.productId == null : this.productId.equals(sIMStatusEBUSuccess.productId)) &&
        (this.productSpecName == null ? sIMStatusEBUSuccess.productSpecName == null : this.productSpecName.equals(sIMStatusEBUSuccess.productSpecName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.isActiv == null ? 0: this.isActiv.hashCode());
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    result = 31 * result + (this.productSpecName == null ? 0: this.productSpecName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SIMStatusEBUSuccess {\n");
    
    sb.append("  isActiv: ").append(isActiv).append("\n");
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  productSpecName: ").append(productSpecName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
