/**
 * API-63 Identity Selector
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 9.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.identity;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class AccountCui extends RealmObject implements EntityInterface {
  
  @SerializedName("displayName")
  private String displayName = null;
  @PrimaryKey
  @SerializedName("entityId")
  private String entityId = null;
  @SerializedName("crmRole")
  private String crmRole = null;
  @SerializedName("vfOdsCui")
  private String vfOdsCui = null;
  @SerializedName("vfOdsSsn")
  private String vfOdsSsn = null;
  @SerializedName("vfOdsSsnType")
  private String vfOdsSsnType = null;
  @SerializedName("childList")
  private RealmList<BillingCustomer> childList = null;

  /**
   * name which will be displayed to user to be selected as entity
   **/
  @ApiModelProperty(required = true, value = "name which will be displayed to user to be selected as entity")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   * unique ID to identify an entity
   **/
  @ApiModelProperty(required = true, value = "unique ID to identify an entity")
  public String getEntityId() {
    return entityId;
  }
  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  /**
   * CRM Role for definied entity
   **/
  @ApiModelProperty(required = true, value = "CRM Role for definied entity")
  public String getCrmRole() {
    return crmRole;
  }
  public void setCrmRole(String crmRole) {
    this.crmRole = crmRole;
  }

  /**
   * CUI belonging to current entity
   **/
  @ApiModelProperty(required = true, value = "CUI belonging to current entity")
  public String getVfOdsCui() {
    return vfOdsCui;
  }
  public void setVfOdsCui(String vfOdsCui) {
    this.vfOdsCui = vfOdsCui;
  }

  /**
   * Social security number belonging to current entity, which can be CUI or CNP
   **/
  @ApiModelProperty(required = true, value = "Social security number belonging to current entity, which can be CUI or CNP")
  public String getVfOdsSsn() {
    return vfOdsSsn;
  }
  public void setVfOdsSsn(String vfOdsSsn) {
    this.vfOdsSsn = vfOdsSsn;
  }

  /**
   * Type of social security number belonging to current entity
   **/
  @ApiModelProperty(value = "Type of social security number belonging to current entity")
  public String getVfOdsSsnType() {
    return vfOdsSsnType;
  }
  public void setVfOdsSsnType(String vfOdsSsnType) {
    this.vfOdsSsnType = vfOdsSsnType;
  }

  /**
   * billingCustomer list under current CUI
   **/
  @ApiModelProperty(required = true, value = "billingCustomer list under current CUI")
  public RealmList<BillingCustomer> getChildList() {
    return childList;
  }
  public void setChildList(RealmList<BillingCustomer> childList) {
    this.childList = childList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountCui accountCui = (AccountCui) o;
    return (this.displayName == null ? accountCui.displayName == null : this.displayName.equals(accountCui.displayName)) &&
        (this.entityId == null ? accountCui.entityId == null : this.entityId.equals(accountCui.entityId)) &&
        (this.crmRole == null ? accountCui.crmRole == null : this.crmRole.equals(accountCui.crmRole)) &&
        (this.vfOdsCui == null ? accountCui.vfOdsCui == null : this.vfOdsCui.equals(accountCui.vfOdsCui)) &&
        (this.vfOdsSsn == null ? accountCui.vfOdsSsn == null : this.vfOdsSsn.equals(accountCui.vfOdsSsn)) &&
        (this.vfOdsSsnType == null ? accountCui.vfOdsSsnType == null : this.vfOdsSsnType.equals(accountCui.vfOdsSsnType)) &&
        (this.childList == null ? accountCui.childList == null : this.childList.equals(accountCui.childList));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.entityId == null ? 0: this.entityId.hashCode());
    result = 31 * result + (this.crmRole == null ? 0: this.crmRole.hashCode());
    result = 31 * result + (this.vfOdsCui == null ? 0: this.vfOdsCui.hashCode());
    result = 31 * result + (this.vfOdsSsn == null ? 0: this.vfOdsSsn.hashCode());
    result = 31 * result + (this.vfOdsSsnType == null ? 0: this.vfOdsSsnType.hashCode());
    result = 31 * result + (this.childList == null ? 0: this.childList.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountCui {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  entityId: ").append(entityId).append("\n");
    sb.append("  crmRole: ").append(crmRole).append("\n");
    sb.append("  vfOdsCui: ").append(vfOdsCui).append("\n");
    sb.append("  vfOdsSsn: ").append(vfOdsSsn).append("\n");
    sb.append("  vfOdsSsnType: ").append(vfOdsSsnType).append("\n");
    sb.append("  childList: ").append(childList).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
