/**
 * API-63 Identity Selector
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 9.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.identity;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful products
 **/
@ApiModel(description = "object containing data associated with successful products")
public class Entity extends RealmObject implements EntityInterface {

  @SerializedName("displayName")
  private String displayName = null;

  @PrimaryKey
  @SerializedName("entityId")
  private String entityId = null;

  @SerializedName("crmRole")
  private String crmRole = null;

  /**
   * name which will be displayed to user to be selected as entity
   **/
  @ApiModelProperty(required = true, value = "name which will be displayed to user to be selected as entity")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   * unique ID to identify an entity
   **/
  @ApiModelProperty(required = true, value = "unique ID to identify an entity")
  public String getEntityId() {
    return entityId;
  }
  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  /**
   * CRM Role for definied entity
   **/
  @ApiModelProperty(required = true, value = "CRM Role for definied entity")
  public String getCrmRole() {
    return crmRole;
  }
  public void setCrmRole(String crmRole) {
    this.crmRole = crmRole;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Entity entity = (Entity) o;
    return (this.displayName == null ? entity.displayName == null : this.displayName.equals(entity.displayName)) &&
        (this.entityId == null ? entity.entityId == null : this.entityId.equals(entity.entityId)) &&
        (this.crmRole == null ? entity.crmRole == null : this.crmRole.equals(entity.crmRole));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.entityId == null ? 0: this.entityId.hashCode());
    result = 31 * result + (this.crmRole == null ? 0: this.crmRole.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Entity {\n");
    
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  entityId: ").append(entityId).append("\n");
    sb.append("  crmRole: ").append(crmRole).append("\n");
    sb.append("}\n");
    return sb.toString();
  }

}
