/**
 * API-63 Identity Selector
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 9.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.identity;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful response
 **/
@ApiModel(description = "object containing data associated with successful response")
public class InverseHierarchyDetailsSuccess extends RealmObject {

  @PrimaryKey
  private long id;

  @SerializedName("cuiName")
  private String cuiName = null;
  @SerializedName("vfOdsCui")
  private String vfOdsCui = null;
  @SerializedName("vfOdsSsn")
  private String vfOdsSsn = null;
  @SerializedName("vfOdsSsnType")
  private String vfOdsSsnType = null;
  @SerializedName("vfOdsCid")
  private String vfOdsCid = null;
  @SerializedName("treatmentSegment")
  private String treatmentSegment = null;
  @SerializedName("microSegment")
  private String microSegment = null;
  @SerializedName("vfOdsBan")
  private String vfOdsBan = null;
  @SerializedName("vfOdsBen")
  private String vfOdsBen = null;

  public InverseHierarchyDetailsSuccess() {
    this.id = 1;
  }

  /**
   * Name belonging to parent AccountCui entity
   **/
  @ApiModelProperty(value = "Name belonging to parent AccountCui entity")
  public String getCuiName() {
    return cuiName;
  }
  public void setCuiName(String cuiName) {
    this.cuiName = cuiName;
  }

  /**
   * CUI belonging to parent AccountCui entity
   **/
  @ApiModelProperty(required = true, value = "CUI belonging to parent AccountCui entity")
  public String getVfOdsCui() {
    return vfOdsCui;
  }
  public void setVfOdsCui(String vfOdsCui) {
    this.vfOdsCui = vfOdsCui;
  }

  /**
   * SSN belonging to parent AccountCui entity
   **/
  @ApiModelProperty(required = true, value = "SSN belonging to parent AccountCui entity")
  public String getVfOdsSsn() {
    return vfOdsSsn;
  }
  public void setVfOdsSsn(String vfOdsSsn) {
    this.vfOdsSsn = vfOdsSsn;
  }

  /**
   * Type of social security number belonging to current entity
   **/
  @ApiModelProperty(value = "Type of social security number belonging to current entity")
  public String getVfOdsSsnType() {
    return vfOdsSsnType;
  }
  public void setVfOdsSsnType(String vfOdsSsnType) {
    this.vfOdsSsnType = vfOdsSsnType;
  }

  /**
   * CID belonging to parent Customer entity. Available only for FinancialAccount and Subscriber entity
   **/
  @ApiModelProperty(value = "CID belonging to parent Customer entity. Available only for FinancialAccount and Subscriber entity")
  public String getVfOdsCid() {
    return vfOdsCid;
  }
  public void setVfOdsCid(String vfOdsCid) {
    this.vfOdsCid = vfOdsCid;
  }

  /**
   * Treatment segment
   **/
  @ApiModelProperty(value = "Treatment segment")
  public String getTreatmentSegment() {
    return treatmentSegment;
  }
  public void setTreatmentSegment(String treatmentSegment) {
    this.treatmentSegment = treatmentSegment;
  }

  /**
   * Micro segment
   **/
  @ApiModelProperty(value = "Micro segment")
  public String getMicroSegment() {
    return microSegment;
  }
  public void setMicroSegment(String microSegment) {
    this.microSegment = microSegment;
  }

  /**
   * BAN belonging to parent Financial Account entity. Available only for Subscriber entity
   **/
  @ApiModelProperty(value = "BAN belonging to parent Financial Account entity. Available only for Subscriber entity")
  public String getVfOdsBan() {
    return vfOdsBan;
  }
  public void setVfOdsBan(String vfOdsBan) {
    this.vfOdsBan = vfOdsBan;
  }

  /**
   * BEN belonging to parent Financial Account entity. Available only for Subscriber entity
   **/
  @ApiModelProperty(value = "BEN belonging to parent Financial Account entity. Available only for Subscriber entity")
  public String getVfOdsBen() {
    return vfOdsBen;
  }
  public void setVfOdsBen(String vfOdsBen) {
    this.vfOdsBen = vfOdsBen;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InverseHierarchyDetailsSuccess inverseHierarchyDetailsSuccess = (InverseHierarchyDetailsSuccess) o;
    return (this.cuiName == null ? inverseHierarchyDetailsSuccess.cuiName == null : this.cuiName.equals(inverseHierarchyDetailsSuccess.cuiName)) &&
        (this.vfOdsCui == null ? inverseHierarchyDetailsSuccess.vfOdsCui == null : this.vfOdsCui.equals(inverseHierarchyDetailsSuccess.vfOdsCui)) &&
        (this.vfOdsSsn == null ? inverseHierarchyDetailsSuccess.vfOdsSsn == null : this.vfOdsSsn.equals(inverseHierarchyDetailsSuccess.vfOdsSsn)) &&
        (this.vfOdsSsnType == null ? inverseHierarchyDetailsSuccess.vfOdsSsnType == null : this.vfOdsSsnType.equals(inverseHierarchyDetailsSuccess.vfOdsSsnType)) &&
        (this.vfOdsCid == null ? inverseHierarchyDetailsSuccess.vfOdsCid == null : this.vfOdsCid.equals(inverseHierarchyDetailsSuccess.vfOdsCid)) &&
        (this.treatmentSegment == null ? inverseHierarchyDetailsSuccess.treatmentSegment == null : this.treatmentSegment.equals(inverseHierarchyDetailsSuccess.treatmentSegment)) &&
        (this.microSegment == null ? inverseHierarchyDetailsSuccess.microSegment == null : this.microSegment.equals(inverseHierarchyDetailsSuccess.microSegment)) &&
        (this.vfOdsBan == null ? inverseHierarchyDetailsSuccess.vfOdsBan == null : this.vfOdsBan.equals(inverseHierarchyDetailsSuccess.vfOdsBan)) &&
        (this.vfOdsBen == null ? inverseHierarchyDetailsSuccess.vfOdsBen == null : this.vfOdsBen.equals(inverseHierarchyDetailsSuccess.vfOdsBen));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.cuiName == null ? 0: this.cuiName.hashCode());
    result = 31 * result + (this.vfOdsCui == null ? 0: this.vfOdsCui.hashCode());
    result = 31 * result + (this.vfOdsSsn == null ? 0: this.vfOdsSsn.hashCode());
    result = 31 * result + (this.vfOdsSsnType == null ? 0: this.vfOdsSsnType.hashCode());
    result = 31 * result + (this.vfOdsCid == null ? 0: this.vfOdsCid.hashCode());
    result = 31 * result + (this.treatmentSegment == null ? 0: this.treatmentSegment.hashCode());
    result = 31 * result + (this.microSegment == null ? 0: this.microSegment.hashCode());
    result = 31 * result + (this.vfOdsBan == null ? 0: this.vfOdsBan.hashCode());
    result = 31 * result + (this.vfOdsBen == null ? 0: this.vfOdsBen.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InverseHierarchyDetailsSuccess {\n");
    
    sb.append("  cuiName: ").append(cuiName).append("\n");
    sb.append("  vfOdsCui: ").append(vfOdsCui).append("\n");
    sb.append("  vfOdsSsn: ").append(vfOdsSsn).append("\n");
    sb.append("  vfOdsSsnType: ").append(vfOdsSsnType).append("\n");
    sb.append("  vfOdsCid: ").append(vfOdsCid).append("\n");
    sb.append("  treatmentSegment: ").append(treatmentSegment).append("\n");
    sb.append("  microSegment: ").append(microSegment).append("\n");
    sb.append("  vfOdsBan: ").append(vfOdsBan).append("\n");
    sb.append("  vfOdsBen: ").append(vfOdsBen).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
