/**
 * API-63 Identity Selector
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 9.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.identity;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class SubscriberEntity extends RealmObject implements EntityInterface{
  
  @SerializedName("displayName")
  private String displayName = null;
  @PrimaryKey
  @SerializedName("entityId")
  private String entityId = null;
  @SerializedName("crmRole")
  private String crmRole = null;
  @SerializedName("vfOdsPhoneNumber")
  private String vfOdsPhoneNumber = null;
  @SerializedName("vfOdsSid")
  private String vfOdsSid = null;
  @SerializedName("vfOdsResourceType")
  private String vfOdsResourceType = null;


  /**
   * name which will be displayed to user to be selected as entity
   **/
  @ApiModelProperty(required = true, value = "name which will be displayed to user to be selected as entity")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   * unique ID to identify an entity
   **/
  @ApiModelProperty(required = true, value = "unique ID to identify an entity")
  public String getEntityId() {
    return entityId;
  }
  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  /**
   * CRM Role for definied entity
   **/
  @ApiModelProperty(required = true, value = "CRM Role for definied entity")
  public String getCrmRole() {
    return crmRole;
  }
  public void setCrmRole(String crmRole) {
    this.crmRole = crmRole;
  }

  /**
   * MSISDN for current entity
   **/
  @ApiModelProperty(required = true, value = "MSISDN for current entity")
  public String getVfOdsPhoneNumber() {
    return vfOdsPhoneNumber;
  }
  public void setVfOdsPhoneNumber(String vfOdsPhoneNumber) {
    this.vfOdsPhoneNumber = vfOdsPhoneNumber;
  }

  /**
   * SubscriberID for current entity
   **/
  @ApiModelProperty(required = true, value = "SubscriberID for current entity")
  public String getVfOdsSid() {
    return vfOdsSid;
  }
  public void setVfOdsSid(String vfOdsSid) {
    this.vfOdsSid = vfOdsSid;
  }

  /**
   * Resource type representing phone number
   **/
  @ApiModelProperty(required = true, value = "Resource type representing phone number")
  public String getVfOdsResourceType() {
    return vfOdsResourceType;
  }
  public void setVfOdsResourceType(String vfOdsResourceType) {
    this.vfOdsResourceType = vfOdsResourceType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriberEntity subscriberEntity = (SubscriberEntity) o;
    return (this.displayName == null ? subscriberEntity.displayName == null : this.displayName.equals(subscriberEntity.displayName)) &&
        (this.entityId == null ? subscriberEntity.entityId == null : this.entityId.equals(subscriberEntity.entityId)) &&
        (this.crmRole == null ? subscriberEntity.crmRole == null : this.crmRole.equals(subscriberEntity.crmRole)) &&
        (this.vfOdsPhoneNumber == null ? subscriberEntity.vfOdsPhoneNumber == null : this.vfOdsPhoneNumber.equals(subscriberEntity.vfOdsPhoneNumber)) &&
        (this.vfOdsSid == null ? subscriberEntity.vfOdsSid == null : this.vfOdsSid.equals(subscriberEntity.vfOdsSid)) &&
        (this.vfOdsResourceType == null ? subscriberEntity.vfOdsResourceType == null : this.vfOdsResourceType.equals(subscriberEntity.vfOdsResourceType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.entityId == null ? 0: this.entityId.hashCode());
    result = 31 * result + (this.crmRole == null ? 0: this.crmRole.hashCode());
    result = 31 * result + (this.vfOdsPhoneNumber == null ? 0: this.vfOdsPhoneNumber.hashCode());
    result = 31 * result + (this.vfOdsSid == null ? 0: this.vfOdsSid.hashCode());
    result = 31 * result + (this.vfOdsResourceType == null ? 0: this.vfOdsResourceType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Subscriber {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  entityId: ").append(entityId).append("\n");
    sb.append("  crmRole: ").append(crmRole).append("\n");
    sb.append("  vfOdsPhoneNumber: ").append(vfOdsPhoneNumber).append("\n");
    sb.append("  vfOdsSid: ").append(vfOdsSid).append("\n");
    sb.append("  vfOdsResourceType: ").append(vfOdsResourceType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
