/**
 * API-63 Identity Selector
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 9.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.identity;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful response
 **/
@ApiModel(description = "object containing data associated with successful response")
public class UserEntitiesSuccess extends RealmObject{

  @PrimaryKey
  private long id;

  @SerializedName("defaultEntity")
  private String defaultEntity = null;
  @SerializedName("contactFirstName")
  private String contactFirstName = null;
  @SerializedName("entitiesList")
  private RealmList<EntityChildItem> entitiesList = null;

  public UserEntitiesSuccess() {
    this.id = 1;
  }

  /**
   * default entity to be logged in
   **/
  @ApiModelProperty(value = "default entity to be logged in")
  public String getDefaultEntity() {
    return defaultEntity;
  }
  public void setDefaultEntity(String defaultEntity) {
    this.defaultEntity = defaultEntity;
  }

  /**
   * user's contact first name
   **/
  @ApiModelProperty(value = "user's contact first name")
  public String getContactFirstName() {
    return contactFirstName;
  }
  public void setContactFirstName(String contactFirstName) {
    this.contactFirstName = contactFirstName;
  }

  /**
   * entities list in a hierarchical structure
   **/
  @ApiModelProperty(value = "entities list in a hierarchical structure")
  public RealmList<EntityChildItem> getEntitiesList() {
    return entitiesList;
  }
  public void setEntitiesList(RealmList<EntityChildItem> entitiesList) {
    this.entitiesList = entitiesList;
  }



}
