/**
 * API-57 Payment Agreement
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.paymentAgreement;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Object containing data associated with successful transaction
 **/
@ApiModel(description = "Object containing data associated with successful transaction")
public class PaymentAgreementSuccess {
  
  @SerializedName("maxAgreementDays")
  private Integer maxAgreementDays = null;
  @SerializedName("currentDate")
  private Long currentDate = null;

  /**
   * Maximum number of days to postpone payment, starting from the current date
   **/
  @ApiModelProperty(value = "Maximum number of days to postpone payment, starting from the current date")
  public Integer getMaxAgreementDays() {
    return maxAgreementDays;
  }
  public void setMaxAgreementDays(Integer maxAgreementDays) {
    this.maxAgreementDays = maxAgreementDays;
  }

  /**
   * System date
   **/
  @ApiModelProperty(value = "System date")
  public Long getCurrentDate() {
    return currentDate;
  }
  public void setCurrentDate(Long currentDate) {
    this.currentDate = currentDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAgreementSuccess paymentAgreementSuccess = (PaymentAgreementSuccess) o;
    return (this.maxAgreementDays == null ? paymentAgreementSuccess.maxAgreementDays == null : this.maxAgreementDays.equals(paymentAgreementSuccess.maxAgreementDays)) &&
        (this.currentDate == null ? paymentAgreementSuccess.currentDate == null : this.currentDate.equals(paymentAgreementSuccess.currentDate));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.maxAgreementDays == null ? 0: this.maxAgreementDays.hashCode());
    result = 31 * result + (this.currentDate == null ? 0: this.currentDate.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAgreementSuccess {\n");
    
    sb.append("  maxAgreementDays: ").append(maxAgreementDays).append("\n");
    sb.append("  currentDate: ").append(currentDate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
