/**
 * API-29  Recommended recharge values
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.recommendedRecharge;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class RecommendedRechargesSuccess extends RealmObject {

  @PrimaryKey
  private long id_recommendedRechargesSuccess;

  @SerializedName("recommendedRecharges")
  private RealmList<RecommendedRecharge> recommendedRecharges = null;


  public RecommendedRechargesSuccess() {
    this.id_recommendedRechargesSuccess = 1;
  }

  public long getId_recommendedRechargesSuccess() {
    return id_recommendedRechargesSuccess;
  }

  /**
   * list with information about recommended recharges
   **/
  @ApiModelProperty(required = true, value = "list with information about recommended recharges")
  public List<RecommendedRecharge> getRecommendedRecharges() {
    return recommendedRecharges;
  }
  public void setRecommendedRecharges(RealmList<RecommendedRecharge> recommendedRecharges) {
    this.recommendedRecharges = recommendedRecharges;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendedRechargesSuccess recommendedRechargesSuccess = (RecommendedRechargesSuccess) o;
    return (this.recommendedRecharges == null ? recommendedRechargesSuccess.recommendedRecharges == null : this.recommendedRecharges.equals(recommendedRechargesSuccess.recommendedRecharges));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.recommendedRecharges == null ? 0: this.recommendedRecharges.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendedRechargesSuccess {\n");
    
    sb.append("  recommendedRecharges: ").append(recommendedRecharges).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
