/**
 * API-29  Recommended recharge values
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.recommendedRecharge;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about current recommended recharge
 **/
@ApiModel(description = "object containing data about current recommended recharge")
public class RecommendedRecharge extends RealmObject{
  
  @SerializedName("amount")
  private Integer amount = null;
  @SerializedName("validity")
  private Integer validity = null;


  public RecommendedRecharge(){
  }

  public RecommendedRecharge(Integer amount, Integer validity) {
    this.amount = amount;
    this.validity = validity;
  }

  /**
   * amount in euro for current recommended recharge
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "amount in euro for current recommended recharge")
  public Integer getAmount() {
    return amount;
  }
  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  /**
   * validity in days for current recommended recharge
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "validity in days for current recommended recharge")
  public Integer getValidity() {
    return validity;
  }
  public void setValidity(Integer validity) {
    this.validity = validity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendedRecharge recommendedRecharge = (RecommendedRecharge) o;
    return (this.amount == null ? recommendedRecharge.amount == null : this.amount.equals(recommendedRecharge.amount)) &&
        (this.validity == null ? recommendedRecharge.validity == null : this.validity.equals(recommendedRecharge.validity));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    result = 31 * result + (this.validity == null ? 0: this.validity.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendedRecharge {\n");
    
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  validity: ").append(validity).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
