/**
 * API-33  Recharge history
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.topUp.history;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about recharge history per month.
 **/
@ApiModel(description = "object containing data about recharge history per month.")
public class RechargeHistoryMonthlyGroup extends RealmObject {


  @PrimaryKey
  @SerializedName("month")
  private int month;

  @SerializedName("averageSpent")
  private Float averageSpent = null;
  @SerializedName("rechargeHistoryRow")
  private RealmList<RechargeHistoryRow> rechargeHistoryRow = null;

  public RechargeHistoryMonthlyGroup() {
  }

  /**
   * month representing current object. 1 - January to 12 - December.
   * minimum: 1
   * maximum: 12
   **/
  @ApiModelProperty(required = true, value = "month representing current object. 1 - January to 12 - December.")
  public int getMonth() {
    return month;
  }
  public void setMonth(int month) {
    this.month = month;
  }

  /**
   * average spent per month
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "average spent per month")
  public Float getAverageSpent() {
    return averageSpent;
  }
  public void setAverageSpent(Float averageSpent) {
    this.averageSpent = averageSpent;
  }

  /**
   * list with recharges made in current month. Recharges will be sorted in descending order by date.
   **/
  @ApiModelProperty(required = true, value = "list with recharges made in current month. Recharges will be sorted in descending order by date.")
  public List<RechargeHistoryRow> getRechargeHistoryRow() {
    return rechargeHistoryRow;
  }
  public void setRechargeHistoryRow(RealmList<RechargeHistoryRow> rechargeHistoryRow) {
    this.rechargeHistoryRow = rechargeHistoryRow;
  }

  public int getSumOfAllRechargeHistory(){
    if(rechargeHistoryRow==null || !rechargeHistoryRow.isValid() || rechargeHistoryRow.isEmpty()){
      return 0;
    }
    int sum=0;
    for (RechargeHistoryRow rechargeElement:
         rechargeHistoryRow) {
      sum+= rechargeElement.getAmount()!=null?rechargeElement.getAmount():0;
    }
    return sum;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RechargeHistoryMonthlyGroup {\n");
    
    sb.append("  month: ").append(month).append("\n");
    sb.append("  averageSpent: ").append(averageSpent).append("\n");
    sb.append("  rechargeHistoryRow: ").append(rechargeHistoryRow).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
