/**
 * API-33  Recharge history
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.topUp.history;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class RechargeHistorySuccess extends RealmObject{

  @PrimaryKey
  private long id;

  @SerializedName("monthlyRechargeHistoryList")
  private RealmList<RechargeHistoryMonthlyGroup> monthlyRechargeHistoryList = null;

  public RechargeHistorySuccess() {
    id = 1;
  }

  /**
   * list with information about recharge history per month. RechargeHistoryMonthlyGroup objects will be sorted in descending order by month.
   **/
  @ApiModelProperty(value = "list with information about recharge history per month. RechargeHistoryMonthlyGroup objects will be sorted in descending order by month.")
  public List<RechargeHistoryMonthlyGroup> getMonthlyRechargeHistoryList() {
    return monthlyRechargeHistoryList;
  }
  public void setMonthlyRechargeHistoryList(RealmList<RechargeHistoryMonthlyGroup> monthlyRechargeHistoryList) {
    this.monthlyRechargeHistoryList = monthlyRechargeHistoryList;
  }


  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RechargeHistorySuccess {\n");
    
    sb.append("  monthlyRechargeHistoryList: ").append(monthlyRechargeHistoryList).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
