/**
 * API-35  Active offers prepaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.beo.prepaid.activeOffers;


import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import ro.vodafone.mcare.android.client.model.beo.OfferRowInterface;

/**
 * object containing data about prepaid offer
 **/
@ApiModel(description = "object containing data about prepaid offer")
public class ActiveOffer extends RealmObject implements OfferRowInterface {
  
  @SerializedName("offerId")
  private Long offerId = null;
  @SerializedName("offerName")
  private String offerName = null;
  @SerializedName("offerCategoryCode")
  private String offerCategoryCode = null;
  @SerializedName("offerCategory")
  private String offerCategory = null;
  @SerializedName("offerShortDescription")
  private String offerShortDescription = null;
  @SerializedName("offerPriority")
  private Integer offerPriority = null;
  @SerializedName("offerPrice")
  private Double offerPrice = null;
  @SerializedName("offerStatus")
  private String offerStatus = null;
  @SerializedName("roamingInfoUrl")
  private String roamingInfoUrl = null;
  @SerializedName("isMultipleActivation")
  private Boolean isMultipleActivation = null;
  @SerializedName("isRenewable")
  private Boolean isRenewable = null;
  @SerializedName("allowOfferDelete")
  private Boolean allowOfferDelete = null;
  @SerializedName("startDate")
  private Long startDate = null;
  @SerializedName("endDate")
  private Long endDate = null;
  @SerializedName("period")
  private Integer period = null;
  @SerializedName("balances")
  private RealmList<BalanceInfo> balances = null;
  @SerializedName("offerImage")
  private String offerImage = null;

  /**
   * offer id
   **/
  @ApiModelProperty(required = true, value = "offer id")
  public Long getOfferId() {
    return offerId;
  }
  public void setOfferId(Long offerId) {
    this.offerId = offerId;
  }

  /**
   * offer name
   **/
  @ApiModelProperty(required = true, value = "offer name")
  public String getOfferName() {
    return offerName;
  }
  public void setOfferName(String offerName) {
    this.offerName = offerName;
  }

  /**
   * code of category to which the offer belongs
   **/
  @ApiModelProperty(value = "code of category to which the offer belongs")
  public String getOfferCategoryCode() {
    return offerCategoryCode;
  }
  public void setOfferCategoryCode(String offerCategoryCode) {
    this.offerCategoryCode = offerCategoryCode;
  }

  /**
   * name of category to which the offer belongs
   **/
  @ApiModelProperty(required = true, value = "name of category to which the offer belongs")
  public String getOfferCategory() {
    return offerCategory;
  }
  public void setOfferCategory(String offerCategory) {
    this.offerCategory = offerCategory;
  }

  /**
   * text description of offer
   **/
  @ApiModelProperty(value = "text description of offer")
  public String getOfferShortDescription() {
    return offerShortDescription;
  }
  public void setOfferShortDescription(String offerShortDescription) {
    this.offerShortDescription = offerShortDescription;
  }

  /**
   * priority indicator from Offer Catalog (hotIndicator)
   **/
  @ApiModelProperty(required = true, value = "priority indicator from Offer Catalog (hotIndicator)")
  public Integer getOfferPriority() {
    return offerPriority;
  }
  public void setOfferPriority(Integer offerPriority) {
    this.offerPriority = offerPriority;
  }

  /**
   * cost for activating offer
   **/
  @ApiModelProperty(required = true, value = "cost for activating offer")
  public Double getOfferPrice() {
    return offerPrice;
  }
  public void setOfferPrice(Double offerPrice) {
    this.offerPrice = offerPrice;
  }

  /**
   * status for active offer; 0 - Inactive, 1 - Active, 2 - Marked for delete, 3 - Suspended, 4 - Pre-active
   **/
  @ApiModelProperty(required = true, value = "status for active offer; 0 - Inactive, 1 - Active, 2 - Marked for delete, 3 - Suspended, 4 - Pre-active")
  public String getOfferStatus() {
    return offerStatus;
  }
  public void setOfferStatus(String offerStatus) {
    this.offerStatus = offerStatus;
  }

  /**
   * URL for roaming info & tariffs
   **/
  @ApiModelProperty(value = "URL for roaming info & tariffs")
  public String getRoamingInfoUrl() {
    return roamingInfoUrl;
  }
  public void setRoamingInfoUrl(String roamingInfoUrl) {
    this.roamingInfoUrl = roamingInfoUrl;
  }

  /**
   * in extraoptions, display only the active offers with multiple activation flag
   **/
  @ApiModelProperty(value = "in extraoptions, display only the active offers with multiple activation flag")
  public Boolean getIsMultipleActivation() {
    return isMultipleActivation;
  }
  public void setIsMultipleActivation(Boolean isMultipleActivation) {
    this.isMultipleActivation = isMultipleActivation;
  }

  /**
   * offer auto reactivation flag
   **/
  @ApiModelProperty(required = true, value = "offer auto reactivation flag")
  public Boolean getIsRenewable() {
    return isRenewable;
  }
  public void setIsRenewable(Boolean isRenewable) {
    this.isRenewable = isRenewable;
  }

  /**
   * allow an offer to be removed, according to a business configured specific set of srvIds
   **/
  @ApiModelProperty(required = true, value = "allow an offer to be removed, according to a business configured specific set of srvIds")
  public Boolean getAllowOfferDelete() {
    return allowOfferDelete;
  }
  public void setAllowOfferDelete(Boolean allowOfferDelete) {
    this.allowOfferDelete = allowOfferDelete;
  }

  /**
   * start date for active offer (timestamp)
   **/
  @ApiModelProperty(value = "start date for active offer (timestamp)")
  public Long getStartDate() {
    return startDate;
  }
  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  /**
   * start date for active offer (timestamp)
   **/
  @ApiModelProperty(value = "start date for active offer (timestamp)")
  public Long getEndDate() {
    return endDate;
  }
  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  /**
   * period in days
   **/
  @ApiModelProperty(value = "period in days")
  public Integer getPeriod() {
    return period;
  }
  public void setPeriod(Integer period) {
    this.period = period;
  }

  /**
   * list containing child offer details for active offer
   **/
  @ApiModelProperty(value = "list containing child offer details for active offer")
  public RealmList<BalanceInfo> getBalances() {
    return balances;
  }
  public void setBalances(RealmList<BalanceInfo> balances) {
    this.balances = balances;
  }

  /**
   * link to CMS image for OTT offers
   **/
  @ApiModelProperty(value = "link to CMS image for OTT offers")
  public String getOfferImage() {
    return offerImage;
  }
  public void setOfferImage(String offerImage) {
    this.offerImage = offerImage;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiveOffer activeOffer = (ActiveOffer) o;
    return (this.offerId == null ? activeOffer.offerId == null : this.offerId.equals(activeOffer.offerId)) &&
        (this.offerName == null ? activeOffer.offerName == null : this.offerName.equals(activeOffer.offerName)) &&
        (this.offerCategoryCode == null ? activeOffer.offerCategoryCode == null : this.offerCategoryCode.equals(activeOffer.offerCategoryCode)) &&
        (this.offerCategory == null ? activeOffer.offerCategory == null : this.offerCategory.equals(activeOffer.offerCategory)) &&
        (this.offerShortDescription == null ? activeOffer.offerShortDescription == null : this.offerShortDescription.equals(activeOffer.offerShortDescription)) &&
        (this.offerPriority == null ? activeOffer.offerPriority == null : this.offerPriority.equals(activeOffer.offerPriority)) &&
        (this.offerPrice == null ? activeOffer.offerPrice == null : this.offerPrice.equals(activeOffer.offerPrice)) &&
        (this.offerStatus == null ? activeOffer.offerStatus == null : this.offerStatus.equals(activeOffer.offerStatus)) &&
        (this.isMultipleActivation == null ? activeOffer.isMultipleActivation == null : this.isMultipleActivation.equals(activeOffer.isMultipleActivation)) &&
        (this.isRenewable == null ? activeOffer.isRenewable == null : this.isRenewable.equals(activeOffer.isRenewable)) &&
        (this.allowOfferDelete == null ? activeOffer.allowOfferDelete == null : this.allowOfferDelete.equals(activeOffer.allowOfferDelete)) &&
        (this.startDate == null ? activeOffer.startDate == null : this.startDate.equals(activeOffer.startDate)) &&
        (this.endDate == null ? activeOffer.endDate == null : this.endDate.equals(activeOffer.endDate)) &&
        (this.period == null ? activeOffer.period == null : this.period.equals(activeOffer.period)) &&
        (this.balances == null ? activeOffer.balances == null : this.balances.equals(activeOffer.balances)) &&
        (this.offerImage == null ? activeOffer.offerImage == null : this.offerImage.equals(activeOffer.offerImage));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.offerId == null ? 0: this.offerId.hashCode());
    result = 31 * result + (this.offerName == null ? 0: this.offerName.hashCode());
    result = 31 * result + (this.offerCategoryCode == null ? 0: this.offerCategoryCode.hashCode());
    result = 31 * result + (this.offerCategory == null ? 0: this.offerCategory.hashCode());
    result = 31 * result + (this.offerShortDescription == null ? 0: this.offerShortDescription.hashCode());
    result = 31 * result + (this.offerPriority == null ? 0: this.offerPriority.hashCode());
    result = 31 * result + (this.offerPrice == null ? 0: this.offerPrice.hashCode());
    result = 31 * result + (this.offerStatus == null ? 0: this.offerStatus.hashCode());
    result = 31 * result + (this.isMultipleActivation == null ? 0: this.isMultipleActivation.hashCode());
    result = 31 * result + (this.isRenewable == null ? 0: this.isRenewable.hashCode());
    result = 31 * result + (this.allowOfferDelete == null ? 0: this.allowOfferDelete.hashCode());
    result = 31 * result + (this.startDate == null ? 0: this.startDate.hashCode());
    result = 31 * result + (this.endDate == null ? 0: this.endDate.hashCode());
    result = 31 * result + (this.period == null ? 0: this.period.hashCode());
    result = 31 * result + (this.balances == null ? 0: this.balances.hashCode());
    result = 31 * result + (this.offerImage == null ? 0: this.offerImage.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiveOffer {\n");
    
    sb.append("  offerId: ").append(offerId).append("\n");
    sb.append("  offerName: ").append(offerName).append("\n");
    sb.append("  offerCategoryCode: ").append(offerCategoryCode).append("\n");
    sb.append("  offerCategory: ").append(offerCategory).append("\n");
    sb.append("  offerShortDescription: ").append(offerShortDescription).append("\n");
    sb.append("  offerPriority: ").append(offerPriority).append("\n");
    sb.append("  offerPrice: ").append(offerPrice).append("\n");
    sb.append("  offerStatus: ").append(offerStatus).append("\n");
    sb.append("  isMultipleActivation: ").append(isMultipleActivation).append("\n");
    sb.append("  isRenewable: ").append(isRenewable).append("\n");
    sb.append("  allowOfferDelete: ").append(allowOfferDelete).append("\n");
    sb.append("  startDate: ").append(startDate).append("\n");
    sb.append("  endDate: ").append(endDate).append("\n");
    sb.append("  period: ").append(period).append("\n");
    sb.append("  balances: ").append(balances).append("\n");
    sb.append("  offerImage: ").append(offerImage).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
