/**
 * API-69 Loyalty Voucher
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.loyalty.market;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * an abstract promotion from which concrete promotion will inherit
 **/
@ApiModel(description = "an abstract promotion from which concrete promotion will inherit")
public class AbstractPromotion {
  
  @SerializedName("campaignExpiryDate")
  private String campaignExpiryDate = null;
  @SerializedName("loyaltySegment")
  private String loyaltySegment = null;
  @SerializedName("promotionId")
  private String promotionId = null;
  @SerializedName("repositoryId")
  private String repositoryId = null;
  @SerializedName("subscriberType")
  private String subscriberType = null;
  @SerializedName("treatmentSegment")
  private String treatmentSegment = null;
  @SerializedName("userRole")
  private String userRole = null;

  /**
   * campaign expiry date
   **/
  @ApiModelProperty(value = "campaign expiry date")
  public String getCampaignExpiryDate() {
    return campaignExpiryDate;
  }
  public void setCampaignExpiryDate(String campaignExpiryDate) {
    this.campaignExpiryDate = campaignExpiryDate;
  }

  /**
   * loyalty segment
   **/
  @ApiModelProperty(value = "loyalty segment")
  public String getLoyaltySegment() {
    return loyaltySegment;
  }
  public void setLoyaltySegment(String loyaltySegment) {
    this.loyaltySegment = loyaltySegment;
  }

  /**
   * promotion id, @PrimaryKey for Promotion object
   **/
  @ApiModelProperty(value = "promotion id, @PrimaryKey for Promotion object")
  public String getPromotionId() {
    return promotionId;
  }
  public void setPromotionId(String promotionId) {
    this.promotionId = promotionId;
  }

  /**
   * repository id
   **/
  @ApiModelProperty(value = "repository id")
  public String getRepositoryId() {
    return repositoryId;
  }
  public void setRepositoryId(String repositoryId) {
    this.repositoryId = repositoryId;
  }

  /**
   * subscriber type
   **/
  @ApiModelProperty(value = "subscriber type")
  public String getSubscriberType() {
    return subscriberType;
  }
  public void setSubscriberType(String subscriberType) {
    this.subscriberType = subscriberType;
  }

  /**
   * treatment segment
   **/
  @ApiModelProperty(value = "treatment segment")
  public String getTreatmentSegment() {
    return treatmentSegment;
  }
  public void setTreatmentSegment(String treatmentSegment) {
    this.treatmentSegment = treatmentSegment;
  }

  /**
   * user role
   **/
  @ApiModelProperty(value = "user role")
  public String getUserRole() {
    return userRole;
  }
  public void setUserRole(String userRole) {
    this.userRole = userRole;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AbstractPromotion abstractPromotion = (AbstractPromotion) o;
    return (this.campaignExpiryDate == null ? abstractPromotion.campaignExpiryDate == null : this.campaignExpiryDate.equals(abstractPromotion.campaignExpiryDate)) &&
        (this.loyaltySegment == null ? abstractPromotion.loyaltySegment == null : this.loyaltySegment.equals(abstractPromotion.loyaltySegment)) &&
        (this.promotionId == null ? abstractPromotion.promotionId == null : this.promotionId.equals(abstractPromotion.promotionId)) &&
        (this.repositoryId == null ? abstractPromotion.repositoryId == null : this.repositoryId.equals(abstractPromotion.repositoryId)) &&
        (this.subscriberType == null ? abstractPromotion.subscriberType == null : this.subscriberType.equals(abstractPromotion.subscriberType)) &&
        (this.treatmentSegment == null ? abstractPromotion.treatmentSegment == null : this.treatmentSegment.equals(abstractPromotion.treatmentSegment)) &&
        (this.userRole == null ? abstractPromotion.userRole == null : this.userRole.equals(abstractPromotion.userRole));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.campaignExpiryDate == null ? 0: this.campaignExpiryDate.hashCode());
    result = 31 * result + (this.loyaltySegment == null ? 0: this.loyaltySegment.hashCode());
    result = 31 * result + (this.promotionId == null ? 0: this.promotionId.hashCode());
    result = 31 * result + (this.repositoryId == null ? 0: this.repositoryId.hashCode());
    result = 31 * result + (this.subscriberType == null ? 0: this.subscriberType.hashCode());
    result = 31 * result + (this.treatmentSegment == null ? 0: this.treatmentSegment.hashCode());
    result = 31 * result + (this.userRole == null ? 0: this.userRole.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AbstractPromotion {\n");
    
    sb.append("  campaignExpiryDate: ").append(campaignExpiryDate).append("\n");
    sb.append("  loyaltySegment: ").append(loyaltySegment).append("\n");
    sb.append("  promotionId: ").append(promotionId).append("\n");
    sb.append("  repositoryId: ").append(repositoryId).append("\n");
    sb.append("  subscriberType: ").append(subscriberType).append("\n");
    sb.append("  treatmentSegment: ").append(treatmentSegment).append("\n");
    sb.append("  userRole: ").append(userRole).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
