/**
 * API-68 Loyalty segment
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 10.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.loyalty.market;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Object containing data associated with successful transaction
 **/
@ApiModel(description = "Object containing data associated with successful transaction")
public class LoyaltySegmentSuccess extends RealmObject{

  @PrimaryKey
  private String id = null;

  @SerializedName("lpsSegment")
  private String lpsSegment = null;
  @SerializedName("treatmentSegment")
  private String treatmentSegment = null;

  public LoyaltySegmentSuccess() {
    this.id = "1";
  }

  /**
   * LPS Segment
   **/
  @ApiModelProperty(value = "LPS Segment")
  public String getLpsSegment() {
    return lpsSegment;
  }
  public void setLpsSegment(String lpsSegment) {
    this.lpsSegment = lpsSegment;
  }

  /**
   * Treatment Segment
   **/
  @ApiModelProperty(value = "Treatment Segment")
  public String getTreatmentSegment() {
    return treatmentSegment;
  }
  public void setTreatmentSegment(String treatmentSegment) {
    this.treatmentSegment = treatmentSegment;
  }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}
