/**
 * API-69 Loyalty Voucher
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.loyalty.market;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import ro.vodafone.mcare.android.utils.RealmManager;

/**
 * promotion
 **/
@ApiModel(description = "promotion")
public class Promotion extends RealmObject {

    public static final String  PRIORITY_KEY ="priority";
    public static final String  PARTNER_NAME_KEY ="partnerName";
    public static final String  CAMPAIGN_EXPIRY_DATE_KEY ="campaignExpiryDate";
    public static final String  VOUCHER_EXPIRY_DATE_KEY ="voucherExpiryDate";
    public static final String  CATEGORY_KEY ="category";
    public static final String IS_RESERVED_KEY = "isReserved";
    public static final String IS_HERO_OFFER = "heroOffer";

  @SerializedName("campaignExpiryDate")
  private Long campaignExpiryDate = null;
  @SerializedName("loyaltySegment")
  private String loyaltySegment = null;
  @SerializedName("promotionId")
  @PrimaryKey
  private String promotionId = null;
  @SerializedName("repositoryId")
  private String repositoryId = null;
  @SerializedName("subscriberType")
  private String subscriberType = null;
  @SerializedName("treatmentSegment")
  private String treatmentSegment = null;
  @SerializedName("userRole")
  private String userRole = null;
  @SerializedName("bannerId")
  private String bannerId = null;
  @SerializedName("campaignStartDate")
  private Long campaignStartDate = null;
  @SerializedName("category")
  private String category = null;
  @SerializedName("customerType")
  private String customerType = null;
  @SerializedName("discountValue")
  private String discountValue = null;
  @SerializedName("heroOffer")
  private String heroOffer = null;
  @SerializedName("partnerHyperlink")
  private String partnerHyperlink = null;
  @SerializedName("partnerName")
  private String partnerName = null;
  @SerializedName("priority")
  private Long priority = Long.MAX_VALUE;
  @SerializedName("quantity")
  private Integer quantity = null;
  @SerializedName("shortDescription")
  private String shortDescription = null;
  @SerializedName("termsAndConditions")
  private String termsAndConditions = null;
  @SerializedName("unitMeasure")
  private String unitMeasure = null;
  @SerializedName("voucherCode")
  private String voucherCode = null;
  @SerializedName("voucherExpiryDate")
  private long voucherExpiryDate = Long.MAX_VALUE;
  @SerializedName("voucherName")
  private String voucherName = null;
  @SerializedName("isReserved")
  private boolean isReserved;

  /**
   * campaign expiry date
   **/
  @ApiModelProperty(value = "campaign expiry date")
  public Long getCampaignExpiryDate() {
    return campaignExpiryDate;
  }
  public void setCampaignExpiryDate(Long campaignExpiryDate) {
    this.campaignExpiryDate = campaignExpiryDate;
  }

  /**
   * loyalty segment
   **/
  @ApiModelProperty(value = "loyalty segment")
  public String getLoyaltySegment() {
    return loyaltySegment;
  }
  public void setLoyaltySegment(String loyaltySegment) {
    this.loyaltySegment = loyaltySegment;
  }

  /**
   * promotion id, @PrimaryKey for Promotion object
   **/
  @ApiModelProperty(value = "promotion id, @PrimaryKey for Promotion object")
  public String getPromotionId() {
    return promotionId;
  }
  public void setPromotionId(String promotionId) {
    this.promotionId = promotionId;
  }

  /**
   * repository id
   **/
  @ApiModelProperty(value = "repository id")
  public String getRepositoryId() {
    return repositoryId;
  }
  public void setRepositoryId(String repositoryId) {
    this.repositoryId = repositoryId;
  }

  /**
   * subscriber type
   **/
  @ApiModelProperty(value = "subscriber type")
  public String getSubscriberType() {
    return subscriberType;
  }
  public void setSubscriberType(String subscriberType) {
    this.subscriberType = subscriberType;
  }

  /**
   * treatment segment
   **/
  @ApiModelProperty(value = "treatment segment")
  public String getTreatmentSegment() {
    return treatmentSegment;
  }
  public void setTreatmentSegment(String treatmentSegment) {
    this.treatmentSegment = treatmentSegment;
  }

  /**
   * user role
   **/
  @ApiModelProperty(value = "user role")
  public String getUserRole() {
    return userRole;
  }
  public void setUserRole(String userRole) {
    this.userRole = userRole;
  }

  /**
   * banner id
   **/
  @ApiModelProperty(value = "banner id")
  public String getBannerId() {
    return bannerId;
  }
  public void setBannerId(String bannerId) {
    this.bannerId = bannerId;
  }

  /**
   * campaign start date
   **/
  @ApiModelProperty(value = "campaign start date")
  public Long getCampaignStartDate() {
    return campaignStartDate;
  }
  public void setCampaignStartDate(Long campaignStartDate) {
    this.campaignStartDate = campaignStartDate;
  }

  /**
   * category
   **/
  @ApiModelProperty(value = "category")
  public String getCategory() {
    return category;
  }
  public void setCategory(String category) {
    RealmManager.startTransaction();
    this.category = category;
    RealmManager.update(this);
  }

  /**
   * customer type
   **/
  @ApiModelProperty(value = "customer type")
  public String getCustomerType() {
    return customerType;
  }
  public void setCustomerType(String customerType) {
    this.customerType = customerType;
  }

  /**
   * discount value
   **/
  @ApiModelProperty(value = "discount value")
  public String getDiscountValue() {
    return discountValue;
  }
  public void setDiscountValue(String discountValue) {
    this.discountValue = discountValue;
  }

  /**
   * hero offer
   **/
  @ApiModelProperty(value = "hero offer")
  public String getHeroOffer() {
    return heroOffer;
  }
  public void setHeroOffer(String heroOffer) {
    this.heroOffer = heroOffer;
  }

  /**
   * partner hyperlink
   **/
  @ApiModelProperty(value = "partner hyperlink")
  public String getPartnerHyperlink() {
    return partnerHyperlink;
  }
  public void setPartnerHyperlink(String partnerHyperlink) {
    this.partnerHyperlink = partnerHyperlink;
  }

  /**
   * partner name
   **/
  @ApiModelProperty(value = "partner name")
  public String getPartnerName() {
    return partnerName;
  }
  public void setPartnerName(String partnerName) {
    this.partnerName = partnerName;
  }

  /**
   * priority
   **/
  @ApiModelProperty(value = "priority")
  public Long getPriority() {
    return priority;
  }
  public void setPriority(Long priority) {
    this.priority = priority;
  }

  /**
   * quantity
   **/
  @ApiModelProperty(value = "quantity")
  public Integer getQuantity() {
    return quantity;
  }
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  /**
   * short description
   **/
  @ApiModelProperty(value = "short description")
  public String getShortDescription() {
    return shortDescription;
  }
  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  /**
   * terms and conditions
   **/
  @ApiModelProperty(value = "terms and conditions")
  public String getTermsAndConditions() {
    return termsAndConditions;
  }
  public void setTermsAndConditions(String termsAndConditions) {
    this.termsAndConditions = termsAndConditions;
  }

  /**
   * unit measure
   **/
  @ApiModelProperty(value = "unit measure")
  public String getUnitMeasure() {
    return unitMeasure;
  }
  public void setUnitMeasure(String unitMeasure) {
    this.unitMeasure = unitMeasure;
  }

  /**
   * voucherCode
   **/
  @ApiModelProperty(value = "voucherCode")
  public String getVoucherCode() {
    return voucherCode;
  }
  public void setVoucherCode(String voucherCode) {
    this.voucherCode = voucherCode;
  }

  /**
   * voucher expiry date
   **/
  @ApiModelProperty(value = "voucher expiry date")
  public Long getVoucherExpiryDate() {
    return voucherExpiryDate;
  }
  public void setVoucherExpiryDate(Long voucherExpiryDate) {
    this.voucherExpiryDate = voucherExpiryDate;
  }

    public boolean isReserved() {
        return isReserved;
    }

    public void setReserved(boolean reserved) {
        isReserved = reserved;
    }

    /**
   * voucher name
   **/
  @ApiModelProperty(value = "voucher name")
  public String getVoucherName() {
    return voucherName;
  }
  public void setVoucherName(String voucherName) {
    this.voucherName = voucherName;
  }
}
