/**
 * API-69 Loyalty Voucher
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.loyalty.market;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * reserved promotion
 **/
@ApiModel(description = "reserved promotion")
public class ReservedPromotion extends RealmObject {

  public static final String RESERVATION_ID_KEY = "reservationId";

  public static final String  CAMPAIGN_EXPIRY_DATE_KEY ="campaignExpiryDate";


  @SerializedName(CAMPAIGN_EXPIRY_DATE_KEY)
  private String campaignExpiryDate = null;
  @SerializedName("loyaltySegment")
  private String loyaltySegment = null;
  @SerializedName("repositoryId")
  private String repositoryId = null;
  @SerializedName("subscriberType")
  private String subscriberType = null;
  @SerializedName("treatmentSegment")
  private String treatmentSegment = null;
  @SerializedName("userRole")
  private String userRole = null;
  @SerializedName("promotion")
  private Promotion promotion = null;
  @SerializedName("campaignReservationDate")
  private String campaignReservationDate = null;
  @SerializedName("msisdn")
  private String msisdn = null;
  @SerializedName("reservationId")
  @PrimaryKey
  private String reservationId = null;
  @SerializedName("subscriberId")
  private String subscriberId = null;

  /**
   * campaign expiry date
   **/
  @ApiModelProperty(value = "campaign expiry date")
  public String getCampaignExpiryDate() {
    return campaignExpiryDate;
  }
  public void setCampaignExpiryDate(String campaignExpiryDate) {
    this.campaignExpiryDate = campaignExpiryDate;
  }

  /**
   * loyalty segment
   **/
  @ApiModelProperty(value = "loyalty segment")
  public String getLoyaltySegment() {
    return loyaltySegment;
  }
  public void setLoyaltySegment(String loyaltySegment) {
    this.loyaltySegment = loyaltySegment;
  }

  /**
   * repository id
   **/
  @ApiModelProperty(value = "repository id")
  public String getRepositoryId() {
    return repositoryId;
  }
  public void setRepositoryId(String repositoryId) {
    this.repositoryId = repositoryId;
  }

  /**
   * subscriber type
   **/
  @ApiModelProperty(value = "subscriber type")
  public String getSubscriberType() {
    return subscriberType;
  }
  public void setSubscriberType(String subscriberType) {
    this.subscriberType = subscriberType;
  }

  /**
   * treatment segment
   **/
  @ApiModelProperty(value = "treatment segment")
  public String getTreatmentSegment() {
    return treatmentSegment;
  }
  public void setTreatmentSegment(String treatmentSegment) {
    this.treatmentSegment = treatmentSegment;
  }

  /**
   * user role
   **/
  @ApiModelProperty(value = "user role")
  public String getUserRole() {
    return userRole;
  }
  public void setUserRole(String userRole) {
    this.userRole = userRole;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Promotion getPromotion() {
    return promotion;
  }
  public void setPromotion(Promotion promotion) {
    this.promotion = promotion;
  }

  /**
   * campaign reservation date
   **/
  @ApiModelProperty(value = "campaign reservation date")
  public String getCampaignReservationDate() {
    return campaignReservationDate;
  }
  public void setCampaignReservationDate(String campaignReservationDate) {
    this.campaignReservationDate = campaignReservationDate;
  }

  /**
   * msisdn
   **/
  @ApiModelProperty(value = "msisdn")
  public String getMsisdn() {
    return msisdn;
  }
  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }

  /**
   * reservation id, @PrimaryKey
   **/
  @ApiModelProperty(value = "reservation id, @PrimaryKey")
  public String getReservationId() {
    return reservationId;
  }
  public void setReservationId(String reservationId) {
    this.reservationId = reservationId;
  }

  /**
   * subscriber id
   **/
  @ApiModelProperty(value = "subscriber id")
  public String getSubscriberId() {
    return subscriberId;
  }
  public void setSubscriberId(String subscriberId) {
    this.subscriberId = subscriberId;
  }


    public boolean isCampaignExpired() {
      try {
        return Long.valueOf(campaignExpiryDate) < System.currentTimeMillis();
      }catch (Exception e){
        e.printStackTrace();
      }
      return false;
    }
}
