/**
 * API-32  Bill recharges
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.billRecharges;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * phone number for current scheduled recharge
 **/
@ApiModel(description = "phone number for current scheduled recharge")
public class MonthlyRecharge extends RealmObject{

  @PrimaryKey
  @SerializedName("scheduleId")
  private Integer scheduleId = null;
  @SerializedName("msisdn")
  private String msisdn = null;
  @SerializedName("scheduledAmount")
  private Float scheduledAmount = null;
  @SerializedName("monthlyCycle")
  private Integer monthlyCycle = null;

  public MonthlyRecharge(){

  }

  /**
   * phone number for current scheduled recharge
   **/
  @ApiModelProperty(required = true, value = "phone number for current scheduled recharge")
  public String getMsisdn() {
    return msisdn;
  }
  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }

  /**
   * scheduled amount to be recharged
   **/
  @ApiModelProperty(required = true, value = "scheduled amount to be recharged")
  public Float getScheduledAmount() {
    return scheduledAmount;
  }
  public void setScheduledAmount(Float scheduledAmount) {
    this.scheduledAmount = scheduledAmount;
  }

  /**
   * schedule recharge id
   **/
  @ApiModelProperty(value = "schedule recharge id")
  public Integer getScheduleId() {
    return scheduleId;
  }
  public void setScheduleId(Integer scheduleId) {
    this.scheduleId = scheduleId;
  }

  /**
   * day in month representing current scheduled recharge.
   * minimum: 0
   * maximum: 31
   **/
  @ApiModelProperty(required = true, value = "day in month representing current scheduled recharge.")
  public Integer getMonthlyCycle() {
    return monthlyCycle;
  }
  public void setMonthlyCycle(Integer monthlyCycle) {
    this.monthlyCycle = monthlyCycle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonthlyRecharge monthlyRecharge = (MonthlyRecharge) o;
    return (this.msisdn == null ? monthlyRecharge.msisdn == null : this.msisdn.equals(monthlyRecharge.msisdn)) &&
        (this.scheduledAmount == null ? monthlyRecharge.scheduledAmount == null : this.scheduledAmount.equals(monthlyRecharge.scheduledAmount)) &&
        (this.scheduleId == null ? monthlyRecharge.scheduleId == null : this.scheduleId.equals(monthlyRecharge.scheduleId)) &&
        (this.monthlyCycle == null ? monthlyRecharge.monthlyCycle == null : this.monthlyCycle.equals(monthlyRecharge.monthlyCycle));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.msisdn == null ? 0: this.msisdn.hashCode());
    result = 31 * result + (this.scheduledAmount == null ? 0: this.scheduledAmount.hashCode());
    result = 31 * result + (this.scheduleId == null ? 0: this.scheduleId.hashCode());
    result = 31 * result + (this.monthlyCycle == null ? 0: this.monthlyCycle.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonthlyRecharge {\n");
    
    sb.append("  msisdn: ").append(msisdn).append("\n");
    sb.append("  scheduledAmount: ").append(scheduledAmount).append("\n");
    sb.append("  scheduleId: ").append(scheduleId).append("\n");
    sb.append("  monthlyCycle: ").append(monthlyCycle).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
