/**
 * API-62 Travelling Abroad Postpaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.travellingAboard;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Object containing data associated with successful transaction
 **/
@ApiModel(description = "Object containing data associated with successful transaction")
public class AccessTypeSuccess extends RealmObject {

  @PrimaryKey
  private int id;

  @SerializedName("isInternational")
  private Boolean isInternational = null;
  @SerializedName("isRoaming")
  private Boolean isRoaming = null;

  public AccessTypeSuccess() {
    id = 1;
  }

  public int getId() {
    return id;
  }


  /**
   * Flag indicating if International access type is enabled for subscriber
   **/
  @ApiModelProperty(required = true, value = "Flag indicating if International access type is enabled for subscriber")
  public Boolean getIsInternational() {
    return isInternational;
  }
  public void setIsInternational(Boolean isInternational) {
    this.isInternational = isInternational;
  }

  /**
   * Flag indicating if Roaming access type is enabled for subscriber
   **/
  @ApiModelProperty(required = true, value = "Flag indicating if Roaming access type is enabled for subscriber")
  public Boolean getIsRoaming() {
    return isRoaming;
  }
  public void setIsRoaming(Boolean isRoaming) {
    this.isRoaming = isRoaming;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccessTypeSuccess accessTypeSuccess = (AccessTypeSuccess) o;
    return (this.isInternational == null ? accessTypeSuccess.isInternational == null : this.isInternational.equals(accessTypeSuccess.isInternational)) &&
        (this.isRoaming == null ? accessTypeSuccess.isRoaming == null : this.isRoaming.equals(accessTypeSuccess.isRoaming));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.isInternational == null ? 0: this.isInternational.hashCode());
    result = 31 * result + (this.isRoaming == null ? 0: this.isRoaming.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccessTypeSuccess {\n");

    sb.append("  isInternational: ").append(isInternational).append("\n");
    sb.append("  isRoaming: ").append(isRoaming).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
