package ro.vodafone.mcare.android.client.model.offers; /**
 * API-39  Active offers postpaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import ro.vodafone.mcare.android.client.model.beo.OfferRowInterface;

/**
 * object containing data about postpaid offer
 **/
@ApiModel(description = "object containing data about postpaid offer")
public class ActiveOfferPostpaid extends RealmObject implements OfferRowInterface, Serializable {

  public static String OFFER_INSTANCE_ID_REALM_KEY = "offerInstanceId";

  @SerializedName("offerId")
  private Long offerId = null;
  @SerializedName("instanceId")
  private Long offerInstanceId = null;
  @SerializedName("offerName")
  private String offerName = null;
  @SerializedName("offerCategory")
  private String offerCategory = null;
  @SerializedName("offerShortDescription")
  private String offerShortDescription = null;
  @SerializedName("offerPrice")
  private Double offerPrice = null;
  @SerializedName("allowOfferDelete")
  private Boolean allowOfferDelete = null;
  @SerializedName("startDate")
  private Long startDate = null;
  @SerializedName("endDate")
  private Long endDate = null;
  @SerializedName("hasETF")
  private Boolean hasETF = null;
  @SerializedName("offerImage")
  private String offerImage = null;
  @SerializedName("offerType")
  private String offerType = null;
  @SerializedName("isNationalOnly")
  private Boolean isNationalOnly = null;
  @SerializedName("currentDate")
  private Long currentDate = null;

  /**
   * offer id
   **/
  @ApiModelProperty(required = true, value = "offer id")
  public Long getOfferId() {
    return offerId;
  }
  public void setOfferId(Long offerId) {
    this.offerId = offerId;
  }

  /**
   * offer instance id
   **/
  @ApiModelProperty(value = "offer instance id")
  public Long getOfferInstanceId() {
    return offerInstanceId;
  }
  public void setOfferInstanceId(Long offerInstanceId) {
    this.offerInstanceId = offerInstanceId;
  }

  /**
   * offer name
   **/
  @ApiModelProperty(required = true, value = "offer name")
  public String getOfferName() {
    return offerName;
  }
  public void setOfferName(String offerName) {
    this.offerName = offerName;
  }

  /**
   * name of category to which the offer belongs
   **/
  @ApiModelProperty(required = true, value = "name of category to which the offer belongs")
  public String getOfferCategory() {
    return offerCategory;
  }
  public void setOfferCategory(String offerCategory) {
    this.offerCategory = offerCategory;
  }

  /**
   * text description of offer
   **/
  @ApiModelProperty(value = "text description of offer")
  public String getOfferShortDescription() {
    return offerShortDescription;
  }
  public void setOfferShortDescription(String offerShortDescription) {
    this.offerShortDescription = offerShortDescription;
  }

  /**
   * cost for activating offer
   **/
  @ApiModelProperty(value = "cost for activating offer")
  public Double getOfferPrice() {
    return offerPrice;
  }
  public void setOfferPrice(Double offerPrice) {
    this.offerPrice = offerPrice;
  }

  /**
   * allow an offer to be removed, according to a business configured specific set of srvIds
   **/
  @ApiModelProperty(required = true, value = "allow an offer to be removed, according to a business configured specific set of srvIds")
  public Boolean getAllowOfferDelete() {
    return allowOfferDelete;
  }
  public void setAllowOfferDelete(Boolean allowOfferDelete) {
    this.allowOfferDelete = allowOfferDelete;
  }

  /**
   * start date for active offer (timestamp)
   **/
  @ApiModelProperty(value = "start date for active offer (timestamp)")
  public Long getStartDate() {
    return startDate;
  }
  public void setStartDate(Long startDate) {
    this.startDate = startDate;
  }

  /**
   * end date for active offer (timestamp)
   **/
  @ApiModelProperty(value = "end date for active offer (timestamp)")
  public Long getEndDate() {
    return endDate;
  }
  public void setEndDate(Long endDate) {
    this.endDate = endDate;
  }

  /**
   * flag indicating that at least one of the incompatible active offers has an early termination fee
   **/
  @ApiModelProperty(required = true, value = "flag indicating that at least one of the incompatible active offers has an early termination fee")
  public Boolean getHasETF() {
    return hasETF;
  }
  public void setHasETF(Boolean hasETF) {
    this.hasETF = hasETF;
  }

  /**
   * link to CMS image for OTT offers
   **/
  @ApiModelProperty(value = "link to CMS image for OTT offers")
  public String getOfferImage() {
    return offerImage;
  }
  public void setOfferImage(String offerImage) {
    this.offerImage = offerImage;
  }

  /**
   * offer type
   **/
  @ApiModelProperty(value = "offer type")
  public String getOfferType() {
    return offerType;
  }
  public void setOfferType(String offerType) {
    this.offerType = offerType;
  }

  /**
   * flag indicating that a price plan has National only access, according to a business configured specific set of srvIds
   **/
  @ApiModelProperty(value = "flag indicating that a price plan has National only access, according to a business configured specific set of srvIds")
  public Boolean getIsNationalOnly() {
    return isNationalOnly;
  }
  public void setIsNationalOnly(Boolean isNationalOnly) {
    this.isNationalOnly = isNationalOnly;
  }

  public Long getCurrentDate() {
    return currentDate;
  }

  public void setCurrentDate(Long currentDate) {
    this.currentDate = currentDate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActiveOfferPostpaid activeOfferPostpaid = (ActiveOfferPostpaid) o;
    return (this.offerId == null ? activeOfferPostpaid.offerId == null : this.offerId.equals(activeOfferPostpaid.offerId)) &&
            (this.offerInstanceId == null ? activeOfferPostpaid.offerInstanceId == null : this.offerInstanceId.equals(activeOfferPostpaid.offerInstanceId)) &&
            (this.offerName == null ? activeOfferPostpaid.offerName == null : this.offerName.equals(activeOfferPostpaid.offerName)) &&
            (this.offerCategory == null ? activeOfferPostpaid.offerCategory == null : this.offerCategory.equals(activeOfferPostpaid.offerCategory)) &&
            (this.offerShortDescription == null ? activeOfferPostpaid.offerShortDescription == null : this.offerShortDescription.equals(activeOfferPostpaid.offerShortDescription)) &&
            (this.offerPrice == null ? activeOfferPostpaid.offerPrice == null : this.offerPrice.equals(activeOfferPostpaid.offerPrice)) &&
            (this.allowOfferDelete == null ? activeOfferPostpaid.allowOfferDelete == null : this.allowOfferDelete.equals(activeOfferPostpaid.allowOfferDelete)) &&
            (this.startDate == null ? activeOfferPostpaid.startDate == null : this.startDate.equals(activeOfferPostpaid.startDate)) &&
            (this.endDate == null ? activeOfferPostpaid.endDate == null : this.endDate.equals(activeOfferPostpaid.endDate)) &&
            (this.hasETF == null ? activeOfferPostpaid.hasETF == null : this.hasETF.equals(activeOfferPostpaid.hasETF)) &&
            (this.offerImage == null ? activeOfferPostpaid.offerImage == null : this.offerImage.equals(activeOfferPostpaid.offerImage)) &&
            (this.offerType == null ? activeOfferPostpaid.offerType == null : this.offerType.equals(activeOfferPostpaid.offerType)) &&
            (this.isNationalOnly == null ? activeOfferPostpaid.isNationalOnly == null : this.isNationalOnly.equals(activeOfferPostpaid.isNationalOnly));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.offerId == null ? 0: this.offerId.hashCode());
    result = 31 * result + (this.offerInstanceId == null ? 0: this.offerInstanceId.hashCode());
    result = 31 * result + (this.offerName == null ? 0: this.offerName.hashCode());
    result = 31 * result + (this.offerCategory == null ? 0: this.offerCategory.hashCode());
    result = 31 * result + (this.offerShortDescription == null ? 0: this.offerShortDescription.hashCode());
    result = 31 * result + (this.offerPrice == null ? 0: this.offerPrice.hashCode());
    result = 31 * result + (this.allowOfferDelete == null ? 0: this.allowOfferDelete.hashCode());
    result = 31 * result + (this.startDate == null ? 0: this.startDate.hashCode());
    result = 31 * result + (this.endDate == null ? 0: this.endDate.hashCode());
    result = 31 * result + (this.hasETF == null ? 0: this.hasETF.hashCode());
    result = 31 * result + (this.offerImage == null ? 0: this.offerImage.hashCode());
    result = 31 * result + (this.offerType == null ? 0: this.offerType.hashCode());
    result = 31 * result + (this.isNationalOnly == null ? 0: this.isNationalOnly.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActiveOfferPostpaid {\n");

    sb.append("  offerId: ").append(offerId).append("\n");
    sb.append("  offerInstanceId: ").append(offerInstanceId).append("\n");
    sb.append("  offerName: ").append(offerName).append("\n");
    sb.append("  offerCategory: ").append(offerCategory).append("\n");
    sb.append("  offerShortDescription: ").append(offerShortDescription).append("\n");
    sb.append("  offerPrice: ").append(offerPrice).append("\n");
    sb.append("  allowOfferDelete: ").append(allowOfferDelete).append("\n");
    sb.append("  startDate: ").append(startDate).append("\n");
    sb.append("  endDate: ").append(endDate).append("\n");
    sb.append("  hasETF: ").append(hasETF).append("\n");
    sb.append("  offerImage: ").append(offerImage).append("\n");
    sb.append("  offerType: ").append(offerType).append("\n");
    sb.append("  isNationalOnly: ").append(isNationalOnly).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
