/**
 * API-39  Active offers postpaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.offers;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class ActiveOffersPostpaidSuccess extends RealmObject{

  @PrimaryKey
  private long id;

  @SerializedName("activeOffersList")
  private RealmList<ActiveOfferPostpaid> activeOffersList = null;
  @SerializedName("activeServicesList")
  private RealmList<ActiveOfferPostpaid> activeServicesList = null;
  @SerializedName("pricePlan")
  private ActiveOfferPostpaid pricePlan = null;

  public ActiveOffersPostpaidSuccess() {
    this.id = 1;
  }

  /**
   * list with active offers
   **/
  @ApiModelProperty(value = "list with active offers")
  public RealmList<ActiveOfferPostpaid> getActiveOffersList() {
    return activeOffersList;
  }
  public void setActiveOffersList(RealmList<ActiveOfferPostpaid> activeOffersList) {
    this.activeOffersList = activeOffersList;
  }

  /**
   * list with active services
   **/
  @ApiModelProperty(value = "list with active services")
  public RealmList<ActiveOfferPostpaid> getActiveServicesList() {
    return activeServicesList;
  }
  public void setActiveServicesList(RealmList<ActiveOfferPostpaid> activeServicesList) {
    this.activeServicesList = activeServicesList;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ActiveOfferPostpaid getPricePlan() {
    return pricePlan;
  }
  public void setPricePlan(ActiveOfferPostpaid pricePlan) {
    this.pricePlan = pricePlan;
  }


}
