/**
 * API-61 Loyalty Points
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 8.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.loyaltyProgram;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data Loyalty Points
 **/
@ApiModel(description = "object containing data Loyalty Points")
public class LoyaltyPoints extends RealmObject {
  
  @SerializedName("amount")
  private Integer amount = null;
  @SerializedName("reason")
  private String reason = null;
  @SerializedName("displayDate")
  private String displayDate = null;

  /**
   * Loyalty Points amount
   **/
  @ApiModelProperty(value = "Loyalty Points amount")
  public Integer getAmount() {
    return amount;
  }
  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  /**
   * Loyalty Points reason
   **/
  @ApiModelProperty(value = "Loyalty Points reason")
  public String getReason() {
    return reason;
  }
  public void setReason(String reason) {
    this.reason = reason;
  }

  /**
   * Loyalty Points Date
   **/
  @ApiModelProperty(value = "Loyalty Points Date")
  public String getDisplayDate() {
    return displayDate;
  }
  public void setDisplayDate(String displayDate) {
    this.displayDate = displayDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoyaltyPoints loyaltyPoints = (LoyaltyPoints) o;
    return (this.amount == null ? loyaltyPoints.amount == null : this.amount.equals(loyaltyPoints.amount)) &&
        (this.reason == null ? loyaltyPoints.reason == null : this.reason.equals(loyaltyPoints.reason)) &&
        (this.displayDate == null ? loyaltyPoints.displayDate == null : this.displayDate.equals(loyaltyPoints.displayDate));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    result = 31 * result + (this.reason == null ? 0: this.reason.hashCode());
    result = 31 * result + (this.displayDate == null ? 0: this.displayDate.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoyaltyPoints {\n");
    
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  reason: ").append(reason).append("\n");
    sb.append("  displayDate: ").append(displayDate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
