/**
 * API-60 Loyalty Program
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 8.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.loyaltyProgram;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data Loyalty Program
 **/
@ApiModel(description = "object containing data Loyalty Program")
public class LPSMessage extends RealmObject {
  
  @SerializedName("messageType")
  private String messageType = null;
  @SerializedName("lpAmount")
  private String lpAmount = null;

  /**
   * Loyalty Program Message Type
   **/
  @ApiModelProperty(value = "Loyalty Program Message Type")
  public String getMessageType() {
    return messageType;
  }
  public void setMessageType(String messageType) {
    this.messageType = messageType;
  }

  /**
   * Loyalty Program Amount
   **/
  @ApiModelProperty(value = "Loyalty Program Amount")
  public String getLpAmount() {
    return lpAmount;
  }
  public void setLpAmount(String lpAmount) {
    this.lpAmount = lpAmount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LPSMessage lPSMessage = (LPSMessage) o;
    return (this.messageType == null ? lPSMessage.messageType == null : this.messageType.equals(lPSMessage.messageType)) &&
        (this.lpAmount == null ? lPSMessage.lpAmount == null : this.lpAmount.equals(lPSMessage.lpAmount));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.messageType == null ? 0: this.messageType.hashCode());
    result = 31 * result + (this.lpAmount == null ? 0: this.lpAmount.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LPSMessage {\n");
    
    sb.append("  messageType: ").append(messageType).append("\n");
    sb.append("  lpAmount: ").append(lpAmount).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
