/**
 * API-49 Shop PricePlans
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about AdditionalBenefits
 **/
@ApiModel(description = "object containing data about AdditionalBenefits")
public class AdditionalBenefits extends RealmObject {
  
  @SerializedName("benefitImageURL")
  private String benefitImageURL = null;
  @SerializedName("name")
  private String name = null;

  /**
   * benefit url to image
   **/
  @ApiModelProperty(value = "benefit url to image")
  public String getBenefitImageURL() {
    return benefitImageURL;
  }
  public void setBenefitImageURL(String benefitImageURL) {
    this.benefitImageURL = benefitImageURL;
  }

  /**
   * additional benefits name
   **/
  @ApiModelProperty(value = "additional benefits name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalBenefits additionalBenefits = (AdditionalBenefits) o;
    return (this.benefitImageURL == null ? additionalBenefits.benefitImageURL == null : this.benefitImageURL.equals(additionalBenefits.benefitImageURL)) &&
        (this.name == null ? additionalBenefits.name == null : this.name.equals(additionalBenefits.name));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.benefitImageURL == null ? 0: this.benefitImageURL.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalBenefits {\n");
    
    sb.append("  benefitImageURL: ").append(benefitImageURL).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
