/**
 * API-47 Shop Products
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about ProductColor
 **/
@ApiModel(description = "object containing data about ProductColor")
public class ProductColor extends RealmObject{

  @SerializedName("colorImg")
  private String colorImg = null;
  @SerializedName("phoneSkuId")
  private String phoneSkuId = null;
  @SerializedName("pricePlanSkuId")
  private String pricePlanSkuId = null;

  /**
   * url to image
   **/
  @ApiModelProperty(value = "url to image")
  public String getColorImg() {
    return colorImg;
  }
  public void setColorImg(String colorImg) {
    this.colorImg = colorImg;
  }

  /**
   * unique identifier for phone product
   **/
  @ApiModelProperty(value = "unique identifier for phone product")
  public String getPhoneSkuId() {
    return phoneSkuId;
  }
  public void setPhoneSkuId(String phoneSkuId) {
    this.phoneSkuId = phoneSkuId;
  }

  /**
   * unique identifier for price plan
   **/
  @ApiModelProperty(value = "unique identifier for price plan")
  public String getPricePlanSkuId() {
    return pricePlanSkuId;
  }
  public void setPricePlanSkuId(String pricePlanSkuId) {
    this.pricePlanSkuId = pricePlanSkuId;
  }


  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductColor {\n");
    
    sb.append("  colorImg: ").append(colorImg).append("\n");
    sb.append("  phoneSkuId: ").append(phoneSkuId).append("\n");
    sb.append("  pricePlanSkuId: ").append(pricePlanSkuId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
