/**
 * API-48 Shop Products
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about ProductColor
 **/
@ApiModel(description = "object containing data about ProductColor")
public class ProductImage extends RealmObject{
  
  @SerializedName("imageURL")
  private String imageURL = null;

  /**
   * url to image
   **/
  @ApiModelProperty(value = "url to image")
  public String getImageURL() {
    return imageURL;
  }
  public void setImageURL(String imageURL) {
    this.imageURL = imageURL;
  }


  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductImage {\n");
    
    sb.append("  imageURL: ").append(imageURL).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
