/**
 * API-47 Shop Products
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about RecommendedPricePlan
 **/
@ApiModel(description = "object containing data about RecommendedPricePlan")
public class RecommendedPricePlan extends RealmObject{

  public static final String PRICE_PLAN_SKUID= "pricePlanSkuId";

  /**
   * Value for pricePlanSkuId that shows current service
   */
  public static final String PRICE_PLAN_SKUID_KEEP_ID= "keep";
  public static final String ELIGIBLE_WITH_DEVICE= "eligibleWithDevice";


  /**
   * keep means current service
   */
  @PrimaryKey
  @SerializedName("pricePlanSkuId")
  private String pricePlanSkuId = null;
  @SerializedName("phoneSkuId")
  private String phoneSkuId = null;
  @SerializedName("productId")
  private String productId = null;
  @SerializedName("cfgSkuId")
  private String cfgSkuId = null;
  @SerializedName("phoneDisplayName")
  private String phoneDisplayName = null;
  @SerializedName("pricePlanDisplayName")
  private String pricePlanDisplayName = null;
  @SerializedName("pricePlanBenefits")
  private String pricePlanBenefits = null;
  @SerializedName("pricePlanDetails")
  private String pricePlanDetails = null;
  @SerializedName("pricePlanMothlyFee")
  private Float pricePlanMothlyFee = null;
  @SerializedName("pricePlanContractPeriod")
  private Integer pricePlanContractPeriod = null;
  @SerializedName("bundlePrice")
  private Float bundlePrice = null;
  @SerializedName("discountedPrice")
  private Float discountedPrice = null;
  @SerializedName("eligibleWithDevice")
  private boolean eligibleWithDevice = false;
  @SerializedName("additionalBenefits")
  private RealmList<AdditionalBenefits> additionalBenefits;

  /**
   * unique identifier for phone product
   **/
  @ApiModelProperty(value = "unique identifier for phone product")
  public String getPhoneSkuId() {
    return phoneSkuId;
  }
  public void setPhoneSkuId(String phoneSkuId) {
    this.phoneSkuId = phoneSkuId;
  }

  public boolean isEligibleWithDevice() {
    return eligibleWithDevice;
  }

  public void setEligibleWithDevice(boolean eligibleWithDevice) {
    this.eligibleWithDevice = eligibleWithDevice;
  }

  public RealmList<AdditionalBenefits> getAdditionalBenefits() {
    return additionalBenefits;
  }

  public void setAdditionalBenefits(RealmList<AdditionalBenefits> additionalBenefits) {
    this.additionalBenefits = additionalBenefits;
  }

  /**
   * unique identifier for price plan
   **/
  @ApiModelProperty(value = "unique identifier for price plan")
  public String getPricePlanSkuId() {
    return pricePlanSkuId;
  }
  public void setPricePlanSkuId(String pricePlanSkuId) {
    this.pricePlanSkuId = pricePlanSkuId;
  }

  /**
   * unique identifier for phone product
   **/
  @ApiModelProperty(value = "unique identifier for phone product")
  public String getProductId() {
    return productId;
  }
  public void setProductId(String productId) {
    this.productId = productId;
  }

  /**
   * unique identifier for configuration
   **/
  @ApiModelProperty(value = "unique identifier for configuration")
  public String getCfgSkuId() {
    return cfgSkuId;
  }
  public void setCfgSkuId(String cfgSkuId) {
    this.cfgSkuId = cfgSkuId;
  }

  /**
   * display name
   **/
  @ApiModelProperty(value = "display name")
  public String getPhoneDisplayName() {
    return phoneDisplayName;
  }
  public void setPhoneDisplayName(String phoneDisplayName) {
    this.phoneDisplayName = phoneDisplayName;
  }

  /**
   * display name
   **/
  @ApiModelProperty(value = "display name")
  public String getPricePlanDisplayName() {
    return pricePlanDisplayName;
  }
  public void setPricePlanDisplayName(String pricePlanDisplayName) {
    this.pricePlanDisplayName = pricePlanDisplayName;
  }

  /**
   * display name
   **/
  @ApiModelProperty(value = "display name")
  public String getPricePlanBenefits() {
    return pricePlanBenefits;
  }
  public void setPricePlanBenefits(String pricePlanBenefits) {
    this.pricePlanBenefits = pricePlanBenefits;
  }

  /**
   * display name
   **/
  @ApiModelProperty(value = "display name")
  public String getPricePlanDetails() {
    return pricePlanDetails;
  }
  public void setPricePlanDetails(String pricePlanDetails) {
    this.pricePlanDetails = pricePlanDetails;
  }

  /**
   * display name
   **/
  @ApiModelProperty(value = "display name")
  public Float getPricePlanMothlyFee() {
    return pricePlanMothlyFee;
  }
  public void setPricePlanMothlyFee(Float pricePlanMothlyFee) {
    this.pricePlanMothlyFee = pricePlanMothlyFee;
  }

  /**
   * display name
   **/
  @ApiModelProperty(value = "display name")
  public Integer getPricePlanContractPeriod() {
    return pricePlanContractPeriod;
  }
  public void setPricePlanContractPeriod(Integer pricePlanContractPeriod) {
    this.pricePlanContractPeriod = pricePlanContractPeriod;
  }

  /**
   * price for bundle
   **/
  @ApiModelProperty(value = "price for bundle")
  public Float getBundlePrice() {
    return bundlePrice;
  }
  public void setBundlePrice(Float bundlePrice) {
    this.bundlePrice = bundlePrice;
  }

  /**
   * price with discount
   **/
  @ApiModelProperty(value = "price with discount")
  public Float getDiscountedPrice() {
    return discountedPrice;
  }
  public void setDiscountedPrice(Float discountedPrice) {
    this.discountedPrice = discountedPrice;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendedPricePlan {\n");
    
    sb.append("  phoneSkuId: ").append(phoneSkuId).append("\n");
    sb.append("  pricePlanSkuId: ").append(pricePlanSkuId).append("\n");
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  cfgSkuId: ").append(cfgSkuId).append("\n");
    sb.append("  phoneDisplayName: ").append(phoneDisplayName).append("\n");
    sb.append("  pricePlanDisplayName: ").append(pricePlanDisplayName).append("\n");
    sb.append("  pricePlanBenefits: ").append(pricePlanBenefits).append("\n");
    sb.append("  pricePlanDetails: ").append(pricePlanDetails).append("\n");
    sb.append("  pricePlanMothlyFee: ").append(pricePlanMothlyFee).append("\n");
    sb.append("  pricePlanContractPeriod: ").append(pricePlanContractPeriod).append("\n");
    sb.append("  bundlePrice: ").append(bundlePrice).append("\n");
    sb.append("  discountedPrice: ").append(discountedPrice).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
