/**
 * API-47 Shop Products
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful products
 **/
@ApiModel(description = "object containing data associated with successful products")
public class ShopProductsSuccess extends RealmObject{

  public static final String ID= "id";
  @PrimaryKey
  private String id;
  @SerializedName("productsList")
  private RealmList<ShopProduct> productsList = null;

  /**
   * list of Shop Products from Catalog
   **/
  @ApiModelProperty(value = "list of Shop Products from Catalog")
  public RealmList<ShopProduct> getProductsList() {
    return productsList;
  }
  public void setProductsList(RealmList<ShopProduct> productsList) {
    this.productsList = productsList;
  }

  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }
}
