/**
 * API-51 Shopping Cart
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about ShopProduct
 **/
@ApiModel(description = "object containing data about ShopProduct")
public class ShopCartSuccess extends RealmObject {
  
  @SerializedName("shoppingCartUrl")
  private String shoppingCartUrl = null;
  @SerializedName("shopCookieName")
  private String shopCookieName = null;

  /**
   * shopping cart url to be opened in WebView
   **/
  @ApiModelProperty(value = "shopping cart url to be opened in WebView")
  public String getShoppingCartUrl() {
    return shoppingCartUrl;
  }
  public void setShopingCartUrl(String shoppingCartUrl) {
    this.shoppingCartUrl = shoppingCartUrl;
  }

  /**
   * shop cookie to be set in Webview (ATG_SESSION_ID)
   **/
  @ApiModelProperty(value = "shop cookie to be set in Webview (ATG_SESSION_ID)")
  public String getShopCookieName() {
    return shopCookieName;
  }
  public void setShopCookieName(String shopCookieName) {
    this.shopCookieName = shopCookieName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopCartSuccess shopCartSuccess = (ShopCartSuccess) o;
    return (this.shoppingCartUrl == null ? shopCartSuccess.shoppingCartUrl == null : this.shoppingCartUrl.equals(shopCartSuccess.shoppingCartUrl)) &&
        (this.shopCookieName == null ? shopCartSuccess.shopCookieName == null : this.shopCookieName.equals(shopCartSuccess.shopCookieName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.shoppingCartUrl == null ? 0: this.shoppingCartUrl.hashCode());
    result = 31 * result + (this.shopCookieName == null ? 0: this.shopCookieName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopCartSuccess {\n");
    
    sb.append("  shoppingCartUrl: ").append(shoppingCartUrl).append("\n");
    sb.append("  shopCookieName: ").append(shopCookieName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
