/**
 * API-46 Shop Login
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ShopLoginRequest {
  
  @SerializedName("msisdn")
  private String msisdn = null;
  @SerializedName("shopSessionToken")
  private String shopSessionToken = null;
  @SerializedName("phoneSkuId")
  private String phoneSkuId = null;

  /**
   * Phone Number from Profile or MSISDN Selector
   **/
  @ApiModelProperty(required = true, value = "Phone Number from Profile or MSISDN Selector")
  public String getMsisdn() {
    return msisdn;
  }
  public void setMsisdn(String msisdn) {
    this.msisdn = msisdn;
  }

  /**
   * previous value of ATG Session Id
   **/
  @ApiModelProperty(required = true, value = "previous value of ATG Session Id")
  public String getShopSessionToken() {
    return shopSessionToken;
  }
  public void setShopSessionToken(String shopSessionToken) {
    this.shopSessionToken = shopSessionToken;
  }

  /**
   * unique identifier for the selected Phone
   **/
  @ApiModelProperty(required = true, value = "unique identifier for the selected Phone")
  public String getPhoneSkuId() {
    return phoneSkuId;
  }
  public void setPhoneSkuId(String phoneSkuId) {
    this.phoneSkuId = phoneSkuId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopLoginRequest shopLoginRequest = (ShopLoginRequest) o;
    return (this.msisdn == null ? shopLoginRequest.msisdn == null : this.msisdn.equals(shopLoginRequest.msisdn)) &&
        (this.shopSessionToken == null ? shopLoginRequest.shopSessionToken == null : this.shopSessionToken.equals(shopLoginRequest.shopSessionToken)) &&
        (this.phoneSkuId == null ? shopLoginRequest.phoneSkuId == null : this.phoneSkuId.equals(shopLoginRequest.phoneSkuId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.msisdn == null ? 0: this.msisdn.hashCode());
    result = 31 * result + (this.shopSessionToken == null ? 0: this.shopSessionToken.hashCode());
    result = 31 * result + (this.phoneSkuId == null ? 0: this.phoneSkuId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopLoginRequest {\n");
    
    sb.append("  msisdn: ").append(msisdn).append("\n");
    sb.append("  shopSessionToken: ").append(shopSessionToken).append("\n");
    sb.append("  phoneSkuId: ").append(phoneSkuId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
