/**
 * API-46 Shop Login
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ShopLoginSuccess extends RealmObject{

  @PrimaryKey
  private long id;
  @SerializedName("shopSessionToken")
  private String shopSessionToken = null;

  public ShopLoginSuccess() {
    this.id = 1;
  }

  /**
   * value of ATG Session Id
   **/
  @ApiModelProperty(required = true, value = "value of ATG Session Id")
  public String getShopSessionToken() {
    return shopSessionToken;
  }
  public void setShopSessionToken(String shopSessionToken) {
    this.shopSessionToken = shopSessionToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopLoginSuccess shopLoginSuccess = (ShopLoginSuccess) o;
    return (this.shopSessionToken == null ? shopLoginSuccess.shopSessionToken == null : this.shopSessionToken.equals(shopLoginSuccess.shopSessionToken));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.shopSessionToken == null ? 0: this.shopSessionToken.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopLoginSuccess {\n");
    
    sb.append("  shopSessionToken: ").append(shopSessionToken).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
