/**
 * API-51 Shopping Cart
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.shop;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data submited for Shopping Cart
 **/
@ApiModel(description = "object containing data submited for Shopping Cart")
public class ShopCartRequest {
  
  @SerializedName("phoneSkuId")
  private String phoneSkuId = null;
  @SerializedName("pricePlanSkuId")
  private String pricePlanSkuId = null;
  @SerializedName("productId")
  private String productId = null;
  @SerializedName("cfgSkuId")
  private String cfgSkuId = null;

  /**
   * unique identifier for phone product
   **/
  @ApiModelProperty(value = "unique identifier for phone product")
  public String getPhoneSkuId() {
    return phoneSkuId;
  }
  public void setPhoneSkuId(String phoneSkuId) {
    this.phoneSkuId = phoneSkuId;
  }

  /**
   * unique identifier for price plan
   **/
  @ApiModelProperty(value = "unique identifier for price plan")
  public String getPricePlanSkuId() {
    return pricePlanSkuId;
  }
  public void setPricePlanSkuId(String pricePlanSkuId) {
    this.pricePlanSkuId = pricePlanSkuId;
  }

  /**
   * unique identifier for phone product
   **/
  @ApiModelProperty(value = "unique identifier for phone product")
  public String getProductId() {
    return productId;
  }
  public void setProductId(String productId) {
    this.productId = productId;
  }

  /**
   * unique identifier for configuration
   **/
  @ApiModelProperty(value = "unique identifier for configuration")
  public String getCfgSkuId() {
    return cfgSkuId;
  }
  public void setCfgSkuId(String cfgSkuId) {
    this.cfgSkuId = cfgSkuId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopCartRequest shopCartRequest = (ShopCartRequest) o;
    return (this.phoneSkuId == null ? shopCartRequest.phoneSkuId == null : this.phoneSkuId.equals(shopCartRequest.phoneSkuId)) &&
        (this.pricePlanSkuId == null ? shopCartRequest.pricePlanSkuId == null : this.pricePlanSkuId.equals(shopCartRequest.pricePlanSkuId)) &&
        (this.productId == null ? shopCartRequest.productId == null : this.productId.equals(shopCartRequest.productId)) &&
        (this.cfgSkuId == null ? shopCartRequest.cfgSkuId == null : this.cfgSkuId.equals(shopCartRequest.cfgSkuId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.phoneSkuId == null ? 0: this.phoneSkuId.hashCode());
    result = 31 * result + (this.pricePlanSkuId == null ? 0: this.pricePlanSkuId.hashCode());
    result = 31 * result + (this.productId == null ? 0: this.productId.hashCode());
    result = 31 * result + (this.cfgSkuId == null ? 0: this.cfgSkuId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopCartRequest {\n");
    
    sb.append("  phoneSkuId: ").append(phoneSkuId).append("\n");
    sb.append("  pricePlanSkuId: ").append(pricePlanSkuId).append("\n");
    sb.append("  productId: ").append(productId).append("\n");
    sb.append("  cfgSkuId: ").append(cfgSkuId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
