/**
 * API-22 Offers Unica
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.offers;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class BannerOffersSuccess extends RealmObject{

  @PrimaryKey
  private int id;

  @SerializedName("bannerOffers")
  private RealmList<BannerOffer> bannerOffers = null;

  public BannerOffersSuccess() {
    id = 1;
  }

  public int getId() {
    return id;
  }

  /**
   * offers received from unica
   **/
  @ApiModelProperty(required = true, value = "bannerOffers received from CMS")
  public RealmList<BannerOffer> getBannerOffers() {
    return bannerOffers;
  }
  public void setBannerOffers(RealmList<BannerOffer> bannerOffers) {
    this.bannerOffers = bannerOffers;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BannerOffersSuccess {\n");
    
    sb.append("  bannerOffers: ").append(bannerOffers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
