/**
 * API-22 Offers Unica
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.offers;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing all information about current unica offer
 **/
@ApiModel(description = "object containing all information about current banner offer")
public class BannerOffer extends RealmObject {
  
  @PrimaryKey
  @SerializedName("offerId")
  private String offerId = null;
  @SerializedName("offerType")
  private String offerType = null;
  @SerializedName("priority")
  private Integer priority = null;
  @SerializedName("bannerImg")
  private String bannerImg = null;
  @SerializedName("bannerTitle")
  private String bannerTitle = null;
  @SerializedName("bannerDescription")
  private String bannerDescription = null;
  @SerializedName("link")
  private String link = null;

  /**
   * offer name to be displayed
   **/
  @ApiModelProperty(value = "offerId to be displayed")
  public String getOfferId() {
    return offerId;
  }
  public void setOfferId(String offerId) {
    this.offerId = offerId;
  }

  /**
   * offer type different for prepaid or postpaid (values can be \"PRP\" - prepaid and \"POP\" - postpaid), (value from InteractParameters[i].Name=”Customertype”)
   **/
  @ApiModelProperty(value = "offer type different for prepaid or postpaid (values can be \"PRP\" - prepaid and \"POP\" - postpaid), (value from InteractParameters[i].Name=”Customertype”)")
  public String getOfferType() {
    return offerType;
  }
  public void setOfferType(String offerType) {
    this.offerType = offerType;
  }

  /**
   * offer priority
   **/
  @ApiModelProperty(value = "offer priority")
  public Integer getPriority() {
    return priority;
  }
  public void setPriority(Integer priority) {
    this.priority = priority;
  }

  /**
   * bannerImg to be displayed
   **/
  @ApiModelProperty(value = "bannerImg to be displayed")
  public String getBannerImg() {
    return bannerImg;
  }
  public void setBannerImg(String bannerImg) {
    this.bannerImg = bannerImg;
  }

  /**
   * bannerTitle to be displayed as first row
   **/
  @ApiModelProperty(value = "bannerTitle to be displayed as first row")
  public String getBannerTitle() {
    return bannerTitle;
  }
  public void setBannerTitle(String bannerTitle) {
    this.bannerTitle = bannerTitle;
  }

  /**
   * bannerTitle to be displayed as first row
   **/
  @ApiModelProperty(value = "bannerDescription to be displayed as second row")
  public String getBannerDescription() {
    return bannerDescription;
  }
  public void setBannerDescription(String bannerDescription) {
    this.bannerDescription = bannerDescription;
  }

  /**
   * external url for unica html offer banner
   **/
  @ApiModelProperty(value = "external url for unica html offer banner")
  public String getLink() {
    return link;
  }
  public void setLink(String link) {
    this.link = link;
  }

}
