/**
 * API-22 Offers Unica
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.offers;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class UnicaOffersSuccess extends RealmObject{

  @PrimaryKey
  @SerializedName("interactSessionId")
  private String interactSessionId = null;
  @SerializedName("offersList")
  private RealmList<UnicaOffer> offersList = null;

  /**
   * interact session ID from unica response
   **/
  @ApiModelProperty(required = true, value = "interact session ID from unica response")
  public String getInteractSessionId() {
    return interactSessionId;
  }
  public void setInteractSessionId(String interactSessionId) {
    this.interactSessionId = interactSessionId;
  }

  /**
   * offers received from unica
   **/
  @ApiModelProperty(required = true, value = "offers received from unica")
  public RealmList<UnicaOffer> getOffersList() {
    return offersList;
  }
  public void setOffersList(RealmList<UnicaOffer> offersList) {
    this.offersList = offersList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnicaOffersSuccess unicaOffersSuccess = (UnicaOffersSuccess) o;
    return (this.interactSessionId == null ? unicaOffersSuccess.interactSessionId == null : this.interactSessionId.equals(unicaOffersSuccess.interactSessionId)) &&
        (this.offersList == null ? unicaOffersSuccess.offersList == null : this.offersList.equals(unicaOffersSuccess.offersList));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.interactSessionId == null ? 0: this.interactSessionId.hashCode());
    result = 31 * result + (this.offersList == null ? 0: this.offersList.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnicaOffersSuccess {\n");
    
    sb.append("  interactSessionId: ").append(interactSessionId).append("\n");
    sb.append("  offersList: ").append(offersList).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
