/**
 * API-22 Offers Unica
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.offers;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing all information about current unica offer
 **/
@ApiModel(description = "object containing all information about current unica offer")
public class UnicaOffer extends RealmObject {
  
  @SerializedName("displayName")
  private String displayName = null;
  @SerializedName("offerName")
  private String offerName = null;
  @SerializedName("shortDescription")
  private String shortDescription = null;
  @SerializedName("offerCode")
  private String offerCode = null;
  @SerializedName("offerType")
  private String offerType = null;
  @SerializedName("score")
  private String score = null;
  @SerializedName("nextBillCycleOption")
  private String nextBillCycleOption = null;
  @SerializedName("billingEffectiveDate")
  private Long billingEffectiveDate = null;
  @SerializedName("nextInvoiceDate")
  private Long nextInvoiceDate = null;
  @SerializedName("urlBanner")
  private String urlBanner = null;
  @SerializedName("urlPdf")
  private String urlPdf = null;
  @SerializedName("treatmentCode")
  private String treatmentCode = null;
  @SerializedName("offerMessage")
  private String offerMessage = null;
  @SerializedName("costMessage")
  private String costMessage = null;
  @SerializedName("interactParameters")
  private RealmList<NameValueParam> interactParameters = null;
  @SerializedName("services")
  private RealmList<UnicaService> services = null;

  /**
   * offer name to be displayed
   **/
  @ApiModelProperty(value = "offer name to be displayed")
  public String getDisplayName() {
    return displayName;
  }
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  /**
   * offer name
   **/
  @ApiModelProperty(value = "offer name")
  public String getOfferName() {
    return offerName;
  }
  public void setOfferName(String offerName) {
    this.offerName = offerName;
  }

  /**
   * offer short description as HTML (to be used in dynamic banners)
   **/
  @ApiModelProperty(value = "offer short description as HTML (to be used in dynamic banners)")
  public String getShortDescription() {
    return shortDescription;
  }
  public void setShortDescription(String shortDescription) {
    this.shortDescription = shortDescription;
  }

  /**
   * offer id to be used in activation
   **/
  @ApiModelProperty(value = "offer id to be used in activation")
  public String getOfferCode() {
    return offerCode;
  }
  public void setOfferCode(String offerCode) {
    this.offerCode = offerCode;
  }

  /**
   * offer type different for prepaid or postpaid (values can be \"PRP\" - prepaid and \"POP\" - postpaid), (value from InteractParameters[i].Name=”Customertype”)
   **/
  @ApiModelProperty(value = "offer type different for prepaid or postpaid (values can be \"PRP\" - prepaid and \"POP\" - postpaid), (value from InteractParameters[i].Name=”Customertype”)")
  public String getOfferType() {
    return offerType;
  }
  public void setOfferType(String offerType) {
    this.offerType = offerType;
  }

  /**
   * offer priority
   **/
  @ApiModelProperty(value = "offer priority")
  public String getScore() {
    return score;
  }
  public void setScore(String score) {
    this.score = score;
  }

  /**
   * reactivation option for unica offer
   **/
  @ApiModelProperty(value = "reactivation option for unica offer")
  public String getNextBillCycleOption() {
    return nextBillCycleOption;
  }
  public void setNextBillCycleOption(String nextBillCycleOption) {
    this.nextBillCycleOption = nextBillCycleOption;
  }

  /**
   * time when offer will be activated
   **/
  @ApiModelProperty(value = "time when offer will be activated")
  public Long getBillingEffectiveDate() {
    return billingEffectiveDate;
  }
  public void setBillingEffectiveDate(Long billingEffectiveDate) {
    this.billingEffectiveDate = billingEffectiveDate;
  }

  /**
   * timestamp for next invoice
   **/
  @ApiModelProperty(value = "timestamp for next invoice")
  public Long getNextInvoiceDate() {
    return nextInvoiceDate;
  }
  public void setNextInvoiceDate(Long nextInvoiceDate) {
    this.nextInvoiceDate = nextInvoiceDate;
  }

  /**
   * external url for unica html offer banner
   **/
  @ApiModelProperty(value = "external url for unica html offer banner")
  public String getUrlBanner() {
    return urlBanner;
  }
  public void setUrlBanner(String urlBanner) {
    this.urlBanner = urlBanner;
  }

  /**
   * external url for offer terms and conditions
   **/
  @ApiModelProperty(value = "external url for offer terms and conditions")
  public String getUrlPdf() {
    return urlPdf;
  }
  public void setUrlPdf(String urlPdf) {
    this.urlPdf = urlPdf;
  }

  /**
   * treatment code for offer activation
   **/
  @ApiModelProperty(value = "treatment code for offer activation")
  public String getTreatmentCode() {
    return treatmentCode;
  }
  public void setTreatmentCode(String treatmentCode) {
    this.treatmentCode = treatmentCode;
  }

  /**
   * static message by offer code
   **/
  @ApiModelProperty(value = "static message by offer code")
  public String getOfferMessage() {
    return offerMessage;
  }
  public void setOfferMessage(String offerMessage) {
    this.offerMessage = offerMessage;
  }

  /**
   * cost message
   **/
  @ApiModelProperty(value = "cost message")
  public String getCostMessage() {
    return costMessage;
  }
  public void setCostMessage(String costMessage) {
    this.costMessage = costMessage;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public RealmList<NameValueParam> getInteractParameters() {
    return interactParameters;
  }
  public void setInteractParameters(RealmList<NameValueParam> interactParameters) {
    this.interactParameters = interactParameters;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public RealmList<UnicaService> getServices() {
    return services;
  }
  public void setServices(RealmList<UnicaService> services) {
    this.services = services;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UnicaOffer unicaOffer = (UnicaOffer) o;
    return (this.displayName == null ? unicaOffer.displayName == null : this.displayName.equals(unicaOffer.displayName)) &&
        (this.offerName == null ? unicaOffer.offerName == null : this.offerName.equals(unicaOffer.offerName)) &&
        (this.shortDescription == null ? unicaOffer.shortDescription == null : this.shortDescription.equals(unicaOffer.shortDescription)) &&
        (this.offerCode == null ? unicaOffer.offerCode == null : this.offerCode.equals(unicaOffer.offerCode)) &&
        (this.offerType == null ? unicaOffer.offerType == null : this.offerType.equals(unicaOffer.offerType)) &&
        (this.score == null ? unicaOffer.score == null : this.score.equals(unicaOffer.score)) &&
        (this.nextBillCycleOption == null ? unicaOffer.nextBillCycleOption == null : this.nextBillCycleOption.equals(unicaOffer.nextBillCycleOption)) &&
        (this.billingEffectiveDate == null ? unicaOffer.billingEffectiveDate == null : this.billingEffectiveDate.equals(unicaOffer.billingEffectiveDate)) &&
        (this.nextInvoiceDate == null ? unicaOffer.nextInvoiceDate == null : this.nextInvoiceDate.equals(unicaOffer.nextInvoiceDate)) &&
        (this.urlBanner == null ? unicaOffer.urlBanner == null : this.urlBanner.equals(unicaOffer.urlBanner)) &&
        (this.urlPdf == null ? unicaOffer.urlPdf == null : this.urlPdf.equals(unicaOffer.urlPdf)) &&
        (this.treatmentCode == null ? unicaOffer.treatmentCode == null : this.treatmentCode.equals(unicaOffer.treatmentCode)) &&
        (this.offerMessage == null ? unicaOffer.offerMessage == null : this.offerMessage.equals(unicaOffer.offerMessage)) &&
        (this.costMessage == null ? unicaOffer.costMessage == null : this.costMessage.equals(unicaOffer.costMessage)) &&
        (this.interactParameters == null ? unicaOffer.interactParameters == null : this.interactParameters.equals(unicaOffer.interactParameters)) &&
        (this.services == null ? unicaOffer.services == null : this.services.equals(unicaOffer.services));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.displayName == null ? 0: this.displayName.hashCode());
    result = 31 * result + (this.offerName == null ? 0: this.offerName.hashCode());
    result = 31 * result + (this.shortDescription == null ? 0: this.shortDescription.hashCode());
    result = 31 * result + (this.offerCode == null ? 0: this.offerCode.hashCode());
    result = 31 * result + (this.offerType == null ? 0: this.offerType.hashCode());
    result = 31 * result + (this.score == null ? 0: this.score.hashCode());
    result = 31 * result + (this.nextBillCycleOption == null ? 0: this.nextBillCycleOption.hashCode());
    result = 31 * result + (this.billingEffectiveDate == null ? 0: this.billingEffectiveDate.hashCode());
    result = 31 * result + (this.nextInvoiceDate == null ? 0: this.nextInvoiceDate.hashCode());
    result = 31 * result + (this.urlBanner == null ? 0: this.urlBanner.hashCode());
    result = 31 * result + (this.urlPdf == null ? 0: this.urlPdf.hashCode());
    result = 31 * result + (this.treatmentCode == null ? 0: this.treatmentCode.hashCode());
    result = 31 * result + (this.offerMessage == null ? 0: this.offerMessage.hashCode());
    result = 31 * result + (this.costMessage == null ? 0: this.costMessage.hashCode());
    result = 31 * result + (this.interactParameters == null ? 0: this.interactParameters.hashCode());
    result = 31 * result + (this.services == null ? 0: this.services.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UnicaOffer {\n");
    
    sb.append("  displayName: ").append(displayName).append("\n");
    sb.append("  offerName: ").append(offerName).append("\n");
    sb.append("  shortDescription: ").append(shortDescription).append("\n");
    sb.append("  offerCode: ").append(offerCode).append("\n");
    sb.append("  offerType: ").append(offerType).append("\n");
    sb.append("  score: ").append(score).append("\n");
    sb.append("  nextBillCycleOption: ").append(nextBillCycleOption).append("\n");
    sb.append("  billingEffectiveDate: ").append(billingEffectiveDate).append("\n");
    sb.append("  nextInvoiceDate: ").append(nextInvoiceDate).append("\n");
    sb.append("  urlBanner: ").append(urlBanner).append("\n");
    sb.append("  urlPdf: ").append(urlPdf).append("\n");
    sb.append("  treatmentCode: ").append(treatmentCode).append("\n");
    sb.append("  offerMessage: ").append(offerMessage).append("\n");
    sb.append("  costMessage: ").append(costMessage).append("\n");
    sb.append("  interactParameters: ").append(interactParameters).append("\n");
    sb.append("  services: ").append(services).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
