/**
 * API-31  Post4pre eligibility
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.eligibility;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Response object with data for bill recharges eligibility.
 **/
@ApiModel(description = "Response object with data for bill recharges eligibility.")
public class BanPost4preEligibilitySuccess extends RealmObject {

  @PrimaryKey
  private long id;

  public BanPost4preEligibilitySuccess(){
    this.id = 1;
  }

  @SerializedName("ben")
  private String ben = null;
  @SerializedName("maxRechargeSum")
  private Float maxRechargeSum = null;
  @SerializedName("currentRechargeSum")
  private Float currentRechargeSum = null;

  /**
   * billing arrangement id
   **/
  @ApiModelProperty(required = true, value = "billing arrangement id")
  public String getBen() {
    return ben;
  }
  public void setBen(String ben) {
    this.ben = ben;
  }

  /**
   * the maximum recharge balance
   **/
  @ApiModelProperty(required = true, value = "the maximum recharge balance")
  public Float getMaxRechargeSum() {
    return maxRechargeSum;
  }
  public void setMaxRechargeSum(Float maxRechargeSum) {
    this.maxRechargeSum = maxRechargeSum;
  }

  /**
   * the sum of previos recharges
   **/
  @ApiModelProperty(required = true, value = "the sum of previos recharges")
  public Float getCurrentRechargeSum() {
    return currentRechargeSum;
  }
  public void setCurrentRechargeSum(Float currentRechargeSum) {
    this.currentRechargeSum = currentRechargeSum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BanPost4preEligibilitySuccess banPost4preEligibilitySuccess = (BanPost4preEligibilitySuccess) o;
    return (this.ben == null ? banPost4preEligibilitySuccess.ben == null : this.ben.equals(banPost4preEligibilitySuccess.ben)) &&
        (this.maxRechargeSum == null ? banPost4preEligibilitySuccess.maxRechargeSum == null : this.maxRechargeSum.equals(banPost4preEligibilitySuccess.maxRechargeSum)) &&
        (this.currentRechargeSum == null ? banPost4preEligibilitySuccess.currentRechargeSum == null : this.currentRechargeSum.equals(banPost4preEligibilitySuccess.currentRechargeSum));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ben == null ? 0: this.ben.hashCode());
    result = 31 * result + (this.maxRechargeSum == null ? 0: this.maxRechargeSum.hashCode());
    result = 31 * result + (this.currentRechargeSum == null ? 0: this.currentRechargeSum.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BanPost4preEligibilitySuccess {\n");
    
    sb.append("  ben: ").append(ben).append("\n");
    sb.append("  maxRechargeSum: ").append(maxRechargeSum).append("\n");
    sb.append("  currentRechargeSum: ").append(currentRechargeSum).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
