/**
 * API-32  Bill recharges
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.8
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.rest.requests;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Request object with data required for bill recharge.
 **/
@ApiModel(description = "Request object with data required for bill recharge.")
public class BillRechargeRequest {
  
  public enum RechargeTypeEnum {
     imd,  otr,  ewr,  emr, 
  };
  @SerializedName("rechargeType")
  private RechargeTypeEnum rechargeType = null;
  @SerializedName("amount")
  private Float amount = null;
  @SerializedName("scheduleID")
  private Integer scheduleID = null;
  @SerializedName("distinctBAquery")
  private String distinctBAquery = null;
  @SerializedName("oneTimeDate")
  private Long oneTimeDate = null;
  @SerializedName("dayInWeek")
  private Integer dayInWeek = null;
  @SerializedName("dayInMonth")
  private Integer dayInMonth = null;

  /**
   * bill recharge type
   **/
  @ApiModelProperty(required = true, value = "bill recharge type")
  public RechargeTypeEnum getRechargeType() {
    return rechargeType;
  }
  public void setRechargeType(RechargeTypeEnum rechargeType) {
    this.rechargeType = rechargeType;
  }

  /**
   * amount to be recharged
   **/
  @ApiModelProperty(required = true, value = "amount to be recharged")
  public Float getAmount() {
    return amount;
  }
  public void setAmount(Float amount) {
    this.amount = amount;
  }

  /**
   * for new recharges scheduleID will be set to 0
   **/
  @ApiModelProperty(required = true, value = "for new recharges scheduleID will be set to 0")
  public Integer getScheduleID() {
    return scheduleID;
  }
  public void setScheduleID(Integer scheduleID) {
    this.scheduleID = scheduleID;
  }

  /**
   * received if rechargeType=\"imd\" (imediatelly).
   **/
  @ApiModelProperty(value = "received if rechargeType=\"imd\" (imediatelly).")
  public String getDistinctBAquery() {
    return distinctBAquery;
  }
  public void setDistinctBAquery(String distinctBAquery) {
    this.distinctBAquery = distinctBAquery;
  }

  /**
   * received if rechargeType=\"otr\" (one time recharge). Timestamp in milliseconds.
   **/
  @ApiModelProperty(value = "received if rechargeType=\"otr\" (one time recharge). Timestamp in milliseconds.")
  public Long getOneTimeDate() {
    return oneTimeDate;
  }
  public void setOneTimeDate(Long oneTimeDate) {
    this.oneTimeDate = oneTimeDate;
  }

  /**
   * received if rechargeType=\"ewr\" (every week recharge). 0 - Monday, 1- Tuesday, 2 - Wednesday, 3 -Thursday, 4 - Friday, 5 - Saturday, 6 - Sunday.
   * minimum: 0
   * maximum: 6
   **/
  @ApiModelProperty(value = "received if rechargeType=\"ewr\" (every week recharge). 0 - Monday, 1- Tuesday, 2 - Wednesday, 3 -Thursday, 4 - Friday, 5 - Saturday, 6 - Sunday.")
  public Integer getDayInWeek() {
    return dayInWeek;
  }
  public void setDayInWeek(Integer dayInWeek) {
    this.dayInWeek = dayInWeek;
  }

  /**
   * received if rechargeType=\"ewm\" (every month recharge).
   * minimum: 0
   * maximum: 31
   **/
  @ApiModelProperty(value = "received if rechargeType=\"ewm\" (every month recharge).")
  public Integer getDayInMonth() {
    return dayInMonth;
  }
  public void setDayInMonth(Integer dayInMonth) {
    this.dayInMonth = dayInMonth;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillRechargeRequest billRechargeRequest = (BillRechargeRequest) o;
    return (this.rechargeType == null ? billRechargeRequest.rechargeType == null : this.rechargeType.equals(billRechargeRequest.rechargeType)) &&
        (this.amount == null ? billRechargeRequest.amount == null : this.amount.equals(billRechargeRequest.amount)) &&
        (this.scheduleID == null ? billRechargeRequest.scheduleID == null : this.scheduleID.equals(billRechargeRequest.scheduleID)) &&
        (this.distinctBAquery == null ? billRechargeRequest.distinctBAquery == null : this.distinctBAquery.equals(billRechargeRequest.distinctBAquery)) &&
        (this.oneTimeDate == null ? billRechargeRequest.oneTimeDate == null : this.oneTimeDate.equals(billRechargeRequest.oneTimeDate)) &&
        (this.dayInWeek == null ? billRechargeRequest.dayInWeek == null : this.dayInWeek.equals(billRechargeRequest.dayInWeek)) &&
        (this.dayInMonth == null ? billRechargeRequest.dayInMonth == null : this.dayInMonth.equals(billRechargeRequest.dayInMonth));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.rechargeType == null ? 0: this.rechargeType.hashCode());
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    result = 31 * result + (this.scheduleID == null ? 0: this.scheduleID.hashCode());
    result = 31 * result + (this.distinctBAquery == null ? 0: this.distinctBAquery.hashCode());
    result = 31 * result + (this.oneTimeDate == null ? 0: this.oneTimeDate.hashCode());
    result = 31 * result + (this.dayInWeek == null ? 0: this.dayInWeek.hashCode());
    result = 31 * result + (this.dayInMonth == null ? 0: this.dayInMonth.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillRechargeRequest {\n");
    
    sb.append("  rechargeType: ").append(rechargeType).append("\n");
    sb.append("  amount: ").append(amount).append("\n");
    sb.append("  scheduleID: ").append(scheduleID).append("\n");
    sb.append("  distinctBAquery: ").append(distinctBAquery).append("\n");
    sb.append("  oneTimeDate: ").append(oneTimeDate).append("\n");
    sb.append("  dayInWeek: ").append(dayInWeek).append("\n");
    sb.append("  dayInMonth: ").append(dayInMonth).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
