/**
 * API-60 Loyalty Program
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 8.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.rest.requests;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data submited for LoyaltyProgram
 **/
@ApiModel(description = "object containing data submited for LoyaltyProgram")
public class LoyaltyProgramRequest {
  
  @SerializedName("selectedBan")
  private String selectedBan = null;

  /**
   * unique identifier for selected Ban
   **/
  @ApiModelProperty(value = "unique identifier for selected Ban")
  public String getSelectedBan() {
    return selectedBan;
  }
  public void setSelectedBan(String selectedBan) {
    this.selectedBan = selectedBan;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoyaltyProgramRequest loyaltyProgramRequest = (LoyaltyProgramRequest) o;
    return (this.selectedBan == null ? loyaltyProgramRequest.selectedBan == null : this.selectedBan.equals(loyaltyProgramRequest.selectedBan));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.selectedBan == null ? 0: this.selectedBan.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoyaltyProgramRequest {\n");
    
    sb.append("  selectedBan: ").append(selectedBan).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
