/**
 * API-24  Payment Request
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 3.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.rest.requests;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Request object with data required for payment.
 **/
@ApiModel(description = "Request object with data required for payment.")
public class PaymentRequest extends RestApiRequest {
  
  @SerializedName("phoneNumber")
  private String phoneNumber = null;
  @SerializedName("amount")
  private Float amount = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("accountNo")
  private String accountNo = null;
  @SerializedName("invoiceNo")
  private String invoiceNo = null;
  @SerializedName("saveCreditCard")
  private boolean saveCreditCard = false;
  @SerializedName("token")
  private String token = null;


  public PaymentRequest(String phoneNumber, Float amount, String email, String accountNo, String invoiceNo) {
    this.phoneNumber = phoneNumber;
    this.amount = amount;
    this.email = email;
    this.accountNo = accountNo;
    this.invoiceNo = invoiceNo;
  }
  public PaymentRequest(String phoneNumber, Float amount, String email, String accountNo, String invoiceNo,String token,boolean saveCreditCard) {
    this.phoneNumber = phoneNumber;
    this.amount = amount;
    this.email = email;
    this.accountNo = accountNo;
    this.invoiceNo = invoiceNo;
    this.saveCreditCard = saveCreditCard;
    this.token = token;
  }
  /**
   * other phone number for which the user is making a payment request
   **/
  @ApiModelProperty(value = "other phone number for which the user is making a payment request")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   * amount to pay
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "amount to pay")
  public Float getAmount() {
    return amount;
  }
  public void setAmount(Float amount) {
    this.amount = amount;
  }

  /**
   * user input email
   **/
  @ApiModelProperty(required = true, value = "user input email")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * BAN on which the payment is being made
   **/
  @ApiModelProperty(required = true, value = "BAN on which the payment is being made")
  public String getAccountNo() {
    return accountNo;
  }
  public void setAccountNo(String accountNo) {
    this.accountNo = accountNo;
  }

  /**
   * invoice number from Invoice Details API
   **/
  @ApiModelProperty(required = true, value = "invoice number from Invoice Details API")
  public String getInvoiceNo() {
    return invoiceNo;
  }
  public void setInvoiceNo(String invoiceNo) {
    this.invoiceNo = invoiceNo;
  }

  public boolean isSaveCreditCard() {
    return saveCreditCard;
  }

  public void setSaveCreditCard(boolean saveCreditCard) {
    this.saveCreditCard = saveCreditCard;
  }

  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRequest paymentRequest = (PaymentRequest) o;
    return (this.phoneNumber == null ? paymentRequest.phoneNumber == null : this.phoneNumber.equals(paymentRequest.phoneNumber)) &&
        (this.amount == null ? paymentRequest.amount == null : this.amount.equals(paymentRequest.amount)) &&
        (this.email == null ? paymentRequest.email == null : this.email.equals(paymentRequest.email)) &&
        (this.accountNo == null ? paymentRequest.accountNo == null : this.accountNo.equals(paymentRequest.accountNo)) &&
        (this.invoiceNo == null ? paymentRequest.invoiceNo == null : this.invoiceNo.equals(paymentRequest.invoiceNo));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.phoneNumber == null ? 0: this.phoneNumber.hashCode());
    result = 31 * result + (this.amount == null ? 0: this.amount.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.accountNo == null ? 0: this.accountNo.hashCode());
    result = 31 * result + (this.invoiceNo == null ? 0: this.invoiceNo.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRequest {\n");
    sb.append("  " + super.toString()).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  billAmount: ").append(amount).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  accountNo: ").append(accountNo).append("\n");
    sb.append("  invoiceNo: ").append(invoiceNo).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
