/**
 * API-57 Payment Agreement
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.rest.requests;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Parameters for payment agreement
 **/
@ApiModel(description = "Parameters for payment agreement")
public class PaymentAgreementRequest {
  
  @SerializedName("agreementDate")
  private Long agreementDate = null;
  @SerializedName("accountId")
  private String accountId = null;
  @SerializedName("userStatus")
  private String userStatus = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("crmRole")
  private String crmRole = null;

  /**
   * Selected date for payment agreement in timestamp format
   **/
  @ApiModelProperty(required = true, value = "Selected date for payment agreement in timestamp format")
  public Long getAgreementDate() {
    return agreementDate;
  }
  public void setAgreementDate(Long agreementDate) {
    this.agreementDate = agreementDate;
  }

  /**
   * Last selected account id
   **/
  @ApiModelProperty(value = "Last selected account id")
  public String getAccountId() {
    return accountId;
  }
  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  /**
   * User status from Login/Seamless Login. Will be set to \"seamless\" if Seamless Login.
   **/
  @ApiModelProperty(value = "User status from Login/Seamless Login. Will be set to \"seamless\" if Seamless Login.")
  public String getUserStatus() {
    return userStatus;
  }
  public void setUserStatus(String userStatus) {
    this.userStatus = userStatus;
  }

  /**
   * Phone number for payment agreement. Format 40xxxxxxxxx. Optional.
   **/
  @ApiModelProperty(value = "Phone number for payment agreement. Format 40xxxxxxxxx. Optional.")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  public String getCrmRole() {
    return crmRole;
  }

  public void setCrmRole(String crmRole) {
    this.crmRole = crmRole;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAgreementRequest paymentAgreementRequest = (PaymentAgreementRequest) o;
    return (this.agreementDate == null ? paymentAgreementRequest.agreementDate == null : this.agreementDate.equals(paymentAgreementRequest.agreementDate)) &&
        (this.accountId == null ? paymentAgreementRequest.accountId == null : this.accountId.equals(paymentAgreementRequest.accountId)) &&
        (this.userStatus == null ? paymentAgreementRequest.userStatus == null : this.userStatus.equals(paymentAgreementRequest.userStatus)) &&
        (this.phone == null ? paymentAgreementRequest.phone == null : this.phone.equals(paymentAgreementRequest.phone));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.agreementDate == null ? 0: this.agreementDate.hashCode());
    result = 31 * result + (this.accountId == null ? 0: this.accountId.hashCode());
    result = 31 * result + (this.userStatus == null ? 0: this.userStatus.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAgreementRequest {\n");
    
    sb.append("  agreementDate: ").append(agreementDate).append("\n");
    sb.append("  accountId: ").append(accountId).append("\n");
    sb.append("  userStatus: ").append(userStatus).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
