package ro.vodafone.mcare.android.rest.requests;

/**
 * API-43 Reset Password
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class ResetPasswordRequest {

    @SerializedName("oldPassword")
    private String oldPassword = null;
    @SerializedName("newPassword")
    private String newPassword = null;

    /**
     * previous password
     **/
    @ApiModelProperty(required = true, value = "previous password")
    public String getOldPassword() {
        return oldPassword;
    }

    public void setOldPassword(String oldPassword) {
        this.oldPassword = oldPassword;
    }

    /**
     * new password
     **/
    @ApiModelProperty(required = true, value = "new password")
    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    @Override
    public String toString()  {
        StringBuilder sb = new StringBuilder();
        sb.append("class ResetPasswordRequest {\n");

        sb.append("  oldPassword: ").append(oldPassword).append("\n");
        sb.append("  newPassword: ").append(newPassword).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
