package ro.vodafone.mcare.android.rest.requests;
/**
 * API-12 Self Register Create Profile
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class SelfRegisterCreateRequest {
  
  @SerializedName("username")
  private String username = null;
  @SerializedName("phoneNumber")
  private String phoneNumber = null;
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("contactPhone")
  private String contactPhone = null;
  @SerializedName("customerType")
  private String customerType = null;
  @SerializedName("acceptTerm")
  private Boolean acceptTerm = null;
  @SerializedName("newsletter")
  private Boolean newsletter = null;
  @SerializedName("salutation")
  private String salutation = null;
  @SerializedName("updateWithoutUsernameFlag")
  private Boolean updateWithoutUsernameFlag = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUsername() {
    return username;
  }
  public void setUsername(String username) {
    this.username = username;
  }

  /**
   * format 0xxxxxxxxx
   **/
  @ApiModelProperty(required = true, value = "format 0xxxxxxxxx")
  public String getPhoneNumber() {
    return phoneNumber;
  }
  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * format 07xxxxxxxx
   **/
  @ApiModelProperty(value = "format 07xxxxxxxx")
  public String getContactPhone() {
    return contactPhone;
  }
  public void setContactPhone(String contactPhone) {
    this.contactPhone = contactPhone;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCustomerType() {
    return customerType;
  }
  public void setCustomerType(String customerType) {
    this.customerType = customerType;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getAcceptTerm() {
    return acceptTerm;
  }
  public void setAcceptTerm(Boolean acceptTerm) {
    this.acceptTerm = acceptTerm;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getNewsletter() {
    return newsletter;
  }
  public void setNewsletter(Boolean newsletter) {
    this.newsletter = newsletter;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getSalutation() {
    return salutation;
  }
  public void setSalutation(String salutation) {
    this.salutation = salutation;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Boolean getUpdateWithoutUsernameFlag() {
    return updateWithoutUsernameFlag;
  }
  public void setUpdateWithoutUsernameFlag(Boolean updateWithoutUsernameFlag) {
    this.updateWithoutUsernameFlag = updateWithoutUsernameFlag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SelfRegisterCreateRequest selfRegisterCreateRequest = (SelfRegisterCreateRequest) o;
    return (this.username == null ? selfRegisterCreateRequest.username == null : this.username.equals(selfRegisterCreateRequest.username)) &&
        (this.phoneNumber == null ? selfRegisterCreateRequest.phoneNumber == null : this.phoneNumber.equals(selfRegisterCreateRequest.phoneNumber)) &&
        (this.firstName == null ? selfRegisterCreateRequest.firstName == null : this.firstName.equals(selfRegisterCreateRequest.firstName)) &&
        (this.lastName == null ? selfRegisterCreateRequest.lastName == null : this.lastName.equals(selfRegisterCreateRequest.lastName)) &&
        (this.email == null ? selfRegisterCreateRequest.email == null : this.email.equals(selfRegisterCreateRequest.email)) &&
        (this.contactPhone == null ? selfRegisterCreateRequest.contactPhone == null : this.contactPhone.equals(selfRegisterCreateRequest.contactPhone)) &&
        (this.customerType == null ? selfRegisterCreateRequest.customerType == null : this.customerType.equals(selfRegisterCreateRequest.customerType)) &&
        (this.acceptTerm == null ? selfRegisterCreateRequest.acceptTerm == null : this.acceptTerm.equals(selfRegisterCreateRequest.acceptTerm)) &&
        (this.newsletter == null ? selfRegisterCreateRequest.newsletter == null : this.newsletter.equals(selfRegisterCreateRequest.newsletter)) &&
        (this.salutation == null ? selfRegisterCreateRequest.salutation == null : this.salutation.equals(selfRegisterCreateRequest.salutation)) &&
        (this.updateWithoutUsernameFlag == null ? selfRegisterCreateRequest.updateWithoutUsernameFlag == null : this.updateWithoutUsernameFlag.equals(selfRegisterCreateRequest.updateWithoutUsernameFlag));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.username == null ? 0: this.username.hashCode());
    result = 31 * result + (this.phoneNumber == null ? 0: this.phoneNumber.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.contactPhone == null ? 0: this.contactPhone.hashCode());
    result = 31 * result + (this.customerType == null ? 0: this.customerType.hashCode());
    result = 31 * result + (this.acceptTerm == null ? 0: this.acceptTerm.hashCode());
    result = 31 * result + (this.newsletter == null ? 0: this.newsletter.hashCode());
    result = 31 * result + (this.salutation == null ? 0: this.salutation.hashCode());
    result = 31 * result + (this.updateWithoutUsernameFlag == null ? 0: this.updateWithoutUsernameFlag.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SelfRegisterCreateRequest {\n");
    
    sb.append("  username: ").append(username).append("\n");
    sb.append("  phoneNumber: ").append(phoneNumber).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  contactPhone: ").append(contactPhone).append("\n");
    sb.append("  customerType: ").append(customerType).append("\n");
    sb.append("  acceptTerm: ").append(acceptTerm).append("\n");
    sb.append("  newsletter: ").append(newsletter).append("\n");
    sb.append("  salutation: ").append(salutation).append("\n");
    sb.append("  updateWithoutUsernameFlag: ").append(updateWithoutUsernameFlag).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
