/**
 * API-34 Recharge Voucher
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.rest.requests;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


public class TransferCreditRequest extends BaseRequest {

  @SerializedName("msisdnRecipient")
  private String msisdnRecipient = null;
  @SerializedName("amount")
  private int amount;

  public String getMsisdnRecipient() {
    return msisdnRecipient;
  }

  public void setMsisdnRecipient(String msisdnRecipient) {
    this.msisdnRecipient = msisdnRecipient;
  }

  public int getAmount() {
    return amount;
  }

  public void setAmount(int amount) {
    this.amount = amount;
  }

  public TransferCreditRequest(String msisdnRecipient, int amount) {
    this.msisdnRecipient = msisdnRecipient;
    this.amount = amount;
  }
}