/**
 * API-55  Bill History
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 * <p>
 * OpenAPI spec version: 6.0.1
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.billHistory;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Object containing data about bill history for one month
 **/
@ApiModel(description = "Object containing data about bill history for one month")
public class BillHistoryDetails extends RealmObject implements Serializable {

    @SerializedName("billClosedDate")
    private Long billClosedDate = null;

    @SerializedName("totalAmountDue")
    private double totalAmountDue;
    @SerializedName("totalMonthlyFee")
    private double totalMonthlyFee;
    @SerializedName("gsmUtilizedServices")
    private double gsmUtilizedServices;

    @SerializedName("historyDetails")
    private RealmList<HistoryDetail> historyDetails = null;

    /**
     * bill closed date in timestamp format
     **/
    @ApiModelProperty(value = "bill closed date in timestamp format")
    public Long getBillClosedDate() {
        return billClosedDate;
    }

    public void setBillClosedDate(Long billClosedDate) {
        this.billClosedDate = billClosedDate;
    }

    /**
     * list with each details for a bill
     **/
    @ApiModelProperty(value = "list with each details for a bill")
    public RealmList<HistoryDetail> getHistoryDetails() {
        return historyDetails;
    }

    public void setHistoryDetails(RealmList<HistoryDetail> historyDetails) {
        this.historyDetails = historyDetails;
    }

    /**
     * total payable amount
     **/
    @ApiModelProperty(value = "total payable amount")
    public double getTotalAmountDue() {
        return totalAmountDue;
    }

    public void setTotalAmountDue(double totalAmountDue) {
        this.totalAmountDue = totalAmountDue;
    }

    /**
     * monthly fee for price plan and extraoptions
     **/
    @ApiModelProperty(value = "monthly fee for price plan and extraoptions")
    public double getTotalMonthlyFee() {
        return totalMonthlyFee;
    }

    public void setTotalMonthlyFee(double totalMonthlyFee) {
        this.totalMonthlyFee = totalMonthlyFee;
    }

    /**
     * additional costs
     **/
    @ApiModelProperty(value = "additional costs")
    public double getGsmUtilizedServices() {
        return gsmUtilizedServices;
    }

    public void setGsmUtilizedServices(double gsmUtilizedServices) {
        this.gsmUtilizedServices = gsmUtilizedServices;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class BillHistoryDetails {\n");

        sb.append("  billClosedDate: ").append(billClosedDate).append("\n");
        sb.append("  totalAmountDue: ").append(totalAmountDue).append("\n");
        sb.append("  totalMonthlyFee: ").append(totalMonthlyFee).append("\n");
        sb.append("  gsmUtilizedServices: ").append(gsmUtilizedServices).append("\n");
        sb.append("  historyDetails: ").append(historyDetails).append("\n");
        sb.append("}\n");
        return sb.toString();
    }

}
