/**
 * API-33 Call Details
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.callDetails;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class CallDetailsRow {
  
  @SerializedName("calledNumber")
  private String calledNumber = null;
  @SerializedName("accessType")
  private String accessType = null;
  @SerializedName("eventDate")
  private Long eventDate = null;
  @SerializedName("usage")
  private String usage = null;
  @SerializedName("cost")
  private String cost = null;

  /**
   * call destination
   **/
  @ApiModelProperty(value = "call destination")
  public String getCalledNumber() {
    return calledNumber;
  }
  public void setCalledNumber(String calledNumber) {
    this.calledNumber = calledNumber;
  }

  /**
   * type of access - National or International or Roaming
   **/
  @ApiModelProperty(value = "type of access - National or International or Roaming")
  public String getAccessType() {
    return accessType;
  }
  public void setAccessType(String accessType) {
    this.accessType = accessType;
  }

  /**
   * call start date
   **/
  @ApiModelProperty(value = "call start date")
  public Long getEventDate() {
    return eventDate;
  }
  public void setEventDate(Long eventDate) {
    this.eventDate = eventDate;
  }

  /**
   * call duration or data usage, including uom
   **/
  @ApiModelProperty(value = "call duration or data usage, including uom")
  public String getUsage() {
    return usage;
  }
  public void setUsage(String usage) {
    this.usage = usage;
  }

  /**
   * call cost, including currency
   **/
  @ApiModelProperty(value = "call cost, including currency")
  public String getCost() {
    return cost;
  }
  public void setCost(String cost) {
    this.cost = cost;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallDetailsRow callDetailsRow = (CallDetailsRow) o;
    return (this.calledNumber == null ? callDetailsRow.calledNumber == null : this.calledNumber.equals(callDetailsRow.calledNumber)) &&
        (this.accessType == null ? callDetailsRow.accessType == null : this.accessType.equals(callDetailsRow.accessType)) &&
        (this.eventDate == null ? callDetailsRow.eventDate == null : this.eventDate.equals(callDetailsRow.eventDate)) &&
        (this.usage == null ? callDetailsRow.usage == null : this.usage.equals(callDetailsRow.usage)) &&
        (this.cost == null ? callDetailsRow.cost == null : this.cost.equals(callDetailsRow.cost));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.calledNumber == null ? 0: this.calledNumber.hashCode());
    result = 31 * result + (this.accessType == null ? 0: this.accessType.hashCode());
    result = 31 * result + (this.eventDate == null ? 0: this.eventDate.hashCode());
    result = 31 * result + (this.usage == null ? 0: this.usage.hashCode());
    result = 31 * result + (this.cost == null ? 0: this.cost.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallDetailsRow {\n");
    
    sb.append("  calledNumber: ").append(calledNumber).append("\n");
    sb.append("  accessType: ").append(accessType).append("\n");
    sb.append("  eventDate: ").append(eventDate).append("\n");
    sb.append("  usage: ").append(usage).append("\n");
    sb.append("  cost: ").append(cost).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
