/**
 * API-37  Eligible offers prepaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.beo.prepaid.eligibleOffers;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing information about banner offers
 **/
@ApiModel(description = "object containing information about banner offers")
public class BannerOfferPrepaid extends RealmObject{
  
  @SerializedName("offerId")
  private Long offerId = null;
  @SerializedName("offerType")
  private String offerType = null;
  @SerializedName("offerImage")
  private String offerImage = null;
  @SerializedName("offerLink")
  private String offerLink = null;

  /**
   * offer id
   **/
  @ApiModelProperty(required = true, value = "offer id")
  public Long getOfferId() {
    return offerId;
  }
  public void setOfferId(Long offerId) {
    this.offerId = offerId;
  }

  /**
   * offer type
   **/
  @ApiModelProperty(required = true, value = "offer type")
  public String getOfferType() {
    return offerType;
  }
  public void setOfferType(String offerType) {
    this.offerType = offerType;
  }

  /**
   * link to banner image
   **/
  @ApiModelProperty(value = "link to banner image")
  public String getOfferImage() {
    return offerImage;
  }
  public void setOfferImage(String offerImage) {
    this.offerImage = offerImage;
  }

  /**
   * link containing offer details
   **/
  @ApiModelProperty(value = "link containing offer details")
  public String getOfferLink() {
    return offerLink;
  }
  public void setOfferLink(String offerLink) {
    this.offerLink = offerLink;
  }

}
