/**
 * Phoenix Integration Devices API
 * Phoenix Integration Devices API (new mCare)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.vodafoneTv;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class DeleteRequest {
  
  @SerializedName("masterUser_id")
  private String masterUserId = null;
  @SerializedName("udid")
  private String udid = null;

  /**
   * add description
   **/
  @ApiModelProperty(value = "add description")
  public String getMasterUserId() {
    return masterUserId;
  }
  public void setMasterUserId(String masterUserId) {
    this.masterUserId = masterUserId;
  }

  /**
   * add description
   **/
  @ApiModelProperty(value = "add description")
  public String getUdid() {
    return udid;
  }
  public void setUdid(String udid) {
    this.udid = udid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeleteRequest deleteRequest = (DeleteRequest) o;
    return (this.masterUserId == null ? deleteRequest.masterUserId == null : this.masterUserId.equals(deleteRequest.masterUserId)) &&
        (this.udid == null ? deleteRequest.udid == null : this.udid.equals(deleteRequest.udid));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.masterUserId == null ? 0: this.masterUserId.hashCode());
    result = 31 * result + (this.udid == null ? 0: this.udid.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeleteRequest {\n");
    
    sb.append("  masterUserId: ").append(masterUserId).append("\n");
    sb.append("  udid: ").append(udid).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
