/**
 * Phoenix Integration Devices API
 * Phoenix Integration Devices API (new mCare)
 * <p>
 * OpenAPI spec version: 1.0.0
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.vodafoneTv;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description = "")
public class DeviceFamiliesList extends RealmObject {

    @SerializedName("devices")
    private RealmList<DevicesList> devices = null;
    @SerializedName("name")
    private String name = null;
    @SerializedName("deviceLimit")
    private Integer deviceLimit = null;
    @SerializedName("icon")
    private String icon = null;

    /**
     **/
    @ApiModelProperty(value = "")
    public List<DevicesList> getDevices() {
        return devices;
    }

    public void setDevices(RealmList<DevicesList> devices) {
        this.devices = devices;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     **/
    @ApiModelProperty(value = "")
    public Integer getDeviceLimit() {
        return deviceLimit;
    }

    public void setDeviceLimit(Integer deviceLimit) {
        this.deviceLimit = deviceLimit;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeviceFamiliesList deviceFamiliesList = (DeviceFamiliesList) o;
        return (this.devices == null ? deviceFamiliesList.devices == null : this.devices.equals(deviceFamiliesList.devices)) &&
                (this.name == null ? deviceFamiliesList.name == null : this.name.equals(deviceFamiliesList.name)) &&
                (this.deviceLimit == null ? deviceFamiliesList.deviceLimit == null : this.deviceLimit.equals(deviceFamiliesList.deviceLimit));
    }

    @Override
    public int hashCode() {
        int result = 17;
        result = 31 * result + (this.devices == null ? 0 : this.devices.hashCode());
        result = 31 * result + (this.name == null ? 0 : this.name.hashCode());
        result = 31 * result + (this.deviceLimit == null ? 0 : this.deviceLimit.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class DeviceFamiliesList {\n");

        sb.append("  devices: ").append(devices).append("\n");
        sb.append("  name: ").append(name).append("\n");
        sb.append("  deviceLimit: ").append(deviceLimit).append("\n");
        sb.append("}\n");
        return sb.toString();
    }
}
