/**
 * Phoenix Integration Devices API
 * Phoenix Integration Devices API (new mCare)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.vodafoneTv;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResetPinRequest {
  
  @SerializedName("defaultUser_id")
  private String defaultUserId = null;

  /**
   * defaultUser_id from getByOperator rsp
   **/
  @ApiModelProperty(required = true, value = "defaultUser_id from getByOperator rsp")
  public String getDefaultUserId() {
    return defaultUserId;
  }
  public void setDefaultUserId(String defaultUserId) {
    this.defaultUserId = defaultUserId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResetPinRequest resetPinRequest = (ResetPinRequest) o;
    return (this.defaultUserId == null ? resetPinRequest.defaultUserId == null : this.defaultUserId.equals(resetPinRequest.defaultUserId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.defaultUserId == null ? 0: this.defaultUserId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResetPinRequest {\n");
    
    sb.append("  defaultUserId: ").append(defaultUserId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
