/**
 * Phoenix Integration Devices API
 * Phoenix Integration Devices API (new mCare)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.vodafoneTv;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ResetPinSuccess {
  
  @SerializedName("newPin")
  private String newPin = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNewPin() {
    return newPin;
  }
  public void setNewPin(String newPin) {
    this.newPin = newPin;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResetPinSuccess resetPinSuccess = (ResetPinSuccess) o;
    return (this.newPin == null ? resetPinSuccess.newPin == null : this.newPin.equals(resetPinSuccess.newPin));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.newPin == null ? 0: this.newPin.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResetPinSuccess {\n");
    
    sb.append("  newPin: ").append(newPin).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
