/**
 * API-42 VOS Offers for Ancom
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.offers.ancom;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Response object with offers list.
 **/
@ApiModel(description = "Response object with offers list.")
public class AncomAcceptedOffersSuccess extends RealmObject{

  @PrimaryKey
  private long id;

  @SerializedName("ancomOffers")
  private RealmList<AncomOffer> ancomOffers = null;

  public AncomAcceptedOffersSuccess() {
    id = 1;
  }

  /**
   * list with offers
   **/
  @ApiModelProperty(value = "list with favorite numbers for recharge")
  public RealmList<AncomOffer> getAncomOffers() {
    return ancomOffers;
  }
  public void setAncomOffers(RealmList<AncomOffer> ancomOffers) {
    this.ancomOffers = ancomOffers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AncomAcceptedOffersSuccess ancomOffersSuccess = (AncomAcceptedOffersSuccess) o;
    return (this.ancomOffers == null ? ancomOffersSuccess.ancomOffers == null : this.ancomOffers.equals(ancomOffersSuccess.ancomOffers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ancomOffers == null ? 0: this.ancomOffers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AncomPendingOffersSuccess {\n");
    
    sb.append("  ancomOffers: ").append(ancomOffers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
