/*
 * API-67 International Calling rates
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 10.0.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ro.vodafone.mcare.android.client.model.internationalCostRates;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Parameters for International Calling RatesRequest
 */
@ApiModel(description = "Parameters for International Calling RatesRequest")
public class InternationalCallingRatesRequest {
  @SerializedName("callerPhone")
  private String callerPhone = null;

  @SerializedName("calledPhone")
  private String calledPhone = null;

  @SerializedName("smsCode")
  private String smsCode = null;

  @SerializedName("isMSISDNResourceType")
  private Boolean isMSISDNResourceType = null;

  public InternationalCallingRatesRequest callerPhone(String callerPhone) {
    this.callerPhone = callerPhone;
    return this;
  }

   /**
   * Caller phone number. Format 0xxxxxxxxx.
   * @return callerPhone
  **/
  @ApiModelProperty(required = true, value = "Caller phone number. Format 0xxxxxxxxx.")
  public String getCallerPhone() {
    return callerPhone;
  }

  public void setCallerPhone(String callerPhone) {
    this.callerPhone = callerPhone;
  }

  public InternationalCallingRatesRequest calledPhone(String calledPhone) {
    this.calledPhone = calledPhone;
    return this;
  }

   /**
   * Called phone number. Format 00xxxxxxxxxx.
   * @return calledPhone
  **/
  @ApiModelProperty(required = true, value = "Called phone number. Format 00xxxxxxxxxx.")
  public String getCalledPhone() {
    return calledPhone;
  }

  public void setCalledPhone(String calledPhone) {
    this.calledPhone = calledPhone;
  }

  public InternationalCallingRatesRequest smsCode(String smsCode) {
    this.smsCode = smsCode;
    return this;
  }

   /**
   * Code received via sms (postpaid user)
   * @return smsCode
  **/
  @ApiModelProperty(required = true, value = "Code received via sms (postpaid user)")
  public String getSmsCode() {
    return smsCode;
  }

  public void setSmsCode(String smsCode) {
    this.smsCode = smsCode;
  }

  public InternationalCallingRatesRequest isMSISDNResourceType(Boolean isMSISDNResourceType) {
    this.isMSISDNResourceType = isMSISDNResourceType;
    return this;
  }

   /**
   * Flag for ResourceType, if it&#39;s true then ResourceTipe is MSISDN
   * @return isMSISDNResourceType
  **/
  @ApiModelProperty(value = "Flag for ResourceType, if it's true then ResourceTipe is MSISDN")
  public Boolean isIsMSISDNResourceType() {
    return isMSISDNResourceType;
  }

  public void setIsMSISDNResourceType(Boolean isMSISDNResourceType) {
    this.isMSISDNResourceType = isMSISDNResourceType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternationalCallingRatesRequest internationalCallingRatesRequest = (InternationalCallingRatesRequest) o;
    return Objects.equals(this.callerPhone, internationalCallingRatesRequest.callerPhone) &&
        Objects.equals(this.calledPhone, internationalCallingRatesRequest.calledPhone) &&
        Objects.equals(this.smsCode, internationalCallingRatesRequest.smsCode) &&
        Objects.equals(this.isMSISDNResourceType, internationalCallingRatesRequest.isMSISDNResourceType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callerPhone, calledPhone, smsCode, isMSISDNResourceType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternationalCallingRatesRequest {\n");
    
    sb.append("    callerPhone: ").append(toIndentedString(callerPhone)).append("\n");
    sb.append("    calledPhone: ").append(toIndentedString(calledPhone)).append("\n");
    sb.append("    smsCode: ").append(toIndentedString(smsCode)).append("\n");
    sb.append("    isMSISDNResourceType: ").append(toIndentedString(isMSISDNResourceType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

