/**
 * API-64  Credit In Advance
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 9.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.creditInAdvance;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class CreditInAdvanceSuccess extends RealmObject {

  @PrimaryKey
  private long id;

  public CreditInAdvanceSuccess(){
    id = 1;
  }

  @SerializedName("CIAEligibiliy")
  private EligibilityInfo CIAEligibiliy = null;

  /**
   * Return object if user is eligibil for credit
   **/
  @ApiModelProperty(value = "Return object if user is eligibil for credit")
  public EligibilityInfo getCIAEligibiliy() {
    return CIAEligibiliy;
  }
  public void setCIAEligibiliy(EligibilityInfo cIAEligibiliy) {
    this.CIAEligibiliy = cIAEligibiliy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditInAdvanceSuccess creditInAdvanceSuccess = (CreditInAdvanceSuccess) o;
    return (this.CIAEligibiliy == null ? creditInAdvanceSuccess.CIAEligibiliy == null : this.CIAEligibiliy.equals(creditInAdvanceSuccess.CIAEligibiliy));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.CIAEligibiliy == null ? 0: this.CIAEligibiliy.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditInAdvanceSuccess {\n");
    
    sb.append("  cIAEligibiliy: ").append(CIAEligibiliy).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
