/**
 * API-64  Credit In Advance
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 9.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.creditInAdvance;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data Eligibility Info
 **/
@ApiModel(description = "object containing data Eligibility Info")
public class EligibilityInfo extends RealmObject {
  
  @SerializedName("credit")
  private String credit = null;
  @SerializedName("fee")
  private String fee = null;
  @SerializedName("ciaID")
  private String ciaID = null;
  @SerializedName("orderNo")
  private String orderNo = null;
  @SerializedName("trsId")
  private String trsId = null;
  @SerializedName("minMos")
  private String minMos = null;
  @SerializedName("minReload")
  private String minReload = null;
  @SerializedName("maxBalance")
  private String maxBalance = null;
  @SerializedName("enabled")
  private String enabled = null;


  /**
   * Credit value from elegibility
   **/
  @ApiModelProperty(required = true, value = "Credit value from elegibility")
  public String getCredit() {
    return credit;
  }
  public void setCredit(String credit) {
    this.credit = credit;
  }

  /**
   * Fee value from elegibility
   **/
  @ApiModelProperty(required = true, value = "Fee value from elegibility")
  public String getFee() {
    return fee;
  }
  public void setFee(String fee) {
    this.fee = fee;
  }

  /**
   * CiaID value from elegibility
   **/
  @ApiModelProperty(required = true, value = "CiaID value from elegibility")
  public String getCiaID() {
    return ciaID;
  }
  public void setCiaID(String ciaID) {
    this.ciaID = ciaID;
  }

  /**
   * OrderNo value from elegibility
   **/
  @ApiModelProperty(required = true, value = "OrderNo value from elegibility")
  public String getOrderNo() {
    return orderNo;
  }
  public void setOrderNo(String orderNo) {
    this.orderNo = orderNo;
  }

  /**
   * TrsId value from elegibility
   **/
  @ApiModelProperty(required = true, value = "TrsId value from elegibility")
  public String getTrsId() {
    return trsId;
  }
  public void setTrsId(String trsId) {
    this.trsId = trsId;
  }

  /**
   * MinMos value from elegibility
   **/
  @ApiModelProperty(required = true, value = "MinMos value from elegibility")
  public String getMinMos() {
    return minMos;
  }
  public void setMinMos(String minMos) {
    this.minMos = minMos;
  }

  /**
   * MinReload value from elegibility
   **/
  @ApiModelProperty(required = true, value = "MinReload value from elegibility")
  public String getMinReload() {
    return minReload;
  }
  public void setMinReload(String minReload) {
    this.minReload = minReload;
  }

  /**
   * MaxBalance value from elegibility
   **/
  @ApiModelProperty(required = true, value = "MaxBalance value from elegibility")
  public String getMaxBalance() {
    return maxBalance;
  }
  public void setMaxBalance(String maxBalance) {
    this.maxBalance = maxBalance;
  }

  /**
   * Enabled value from elegibility
   **/
  @ApiModelProperty(required = true, value = "Enabled value from elegibility")
  public String getEnabled() {
    return enabled;
  }
  public void setEnabled(String enabled) {
    this.enabled = enabled;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EligibilityInfo eligibilityInfo = (EligibilityInfo) o;
    return (this.credit == null ? eligibilityInfo.credit == null : this.credit.equals(eligibilityInfo.credit)) &&
        (this.fee == null ? eligibilityInfo.fee == null : this.fee.equals(eligibilityInfo.fee)) &&
        (this.ciaID == null ? eligibilityInfo.ciaID == null : this.ciaID.equals(eligibilityInfo.ciaID)) &&
        (this.orderNo == null ? eligibilityInfo.orderNo == null : this.orderNo.equals(eligibilityInfo.orderNo)) &&
        (this.trsId == null ? eligibilityInfo.trsId == null : this.trsId.equals(eligibilityInfo.trsId)) &&
        (this.minMos == null ? eligibilityInfo.minMos == null : this.minMos.equals(eligibilityInfo.minMos)) &&
        (this.minReload == null ? eligibilityInfo.minReload == null : this.minReload.equals(eligibilityInfo.minReload)) &&
        (this.maxBalance == null ? eligibilityInfo.maxBalance == null : this.maxBalance.equals(eligibilityInfo.maxBalance)) &&
        (this.enabled == null ? eligibilityInfo.enabled == null : this.enabled.equals(eligibilityInfo.enabled));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.credit == null ? 0: this.credit.hashCode());
    result = 31 * result + (this.fee == null ? 0: this.fee.hashCode());
    result = 31 * result + (this.ciaID == null ? 0: this.ciaID.hashCode());
    result = 31 * result + (this.orderNo == null ? 0: this.orderNo.hashCode());
    result = 31 * result + (this.trsId == null ? 0: this.trsId.hashCode());
    result = 31 * result + (this.minMos == null ? 0: this.minMos.hashCode());
    result = 31 * result + (this.minReload == null ? 0: this.minReload.hashCode());
    result = 31 * result + (this.maxBalance == null ? 0: this.maxBalance.hashCode());
    result = 31 * result + (this.enabled == null ? 0: this.enabled.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EligibilityInfo {\n");
    
    sb.append("  credit: ").append(credit).append("\n");
    sb.append("  fee: ").append(fee).append("\n");
    sb.append("  ciaID: ").append(ciaID).append("\n");
    sb.append("  orderNo: ").append(orderNo).append("\n");
    sb.append("  trsId: ").append(trsId).append("\n");
    sb.append("  minMos: ").append(minMos).append("\n");
    sb.append("  minReload: ").append(minReload).append("\n");
    sb.append("  maxBalance: ").append(maxBalance).append("\n");
    sb.append("  enabled: ").append(enabled).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
