/**
 * API-26 Bill Dates
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.billDates;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class BillsDatesSuccess {
  
  @SerializedName("billClosedDatesList")
  private List<Long> billClosedDatesList = null;

  /**
   * bill closed dates (Unix time)
   **/
  @ApiModelProperty(value = "bill closed dates (Unix time)")
  public List<Long> getBillClosedDatesList() {
    return billClosedDatesList;
  }
  public void setBillClosedDatesList(List<Long> billClosedDatesList) {
    this.billClosedDatesList = billClosedDatesList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillsDatesSuccess billsDatesSuccess = (BillsDatesSuccess) o;
    return (this.billClosedDatesList == null ? billsDatesSuccess.billClosedDatesList == null : this.billClosedDatesList.equals(billsDatesSuccess.billClosedDatesList));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.billClosedDatesList == null ? 0: this.billClosedDatesList.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillsDatesSuccess {\n");
    
    sb.append("  billClosedDatesList: ").append(billClosedDatesList).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
