package ro.vodafone.mcare.android.client.model.offers.activeOffersEbu; /**
 * API-39  Active offers postpaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about promotion
 **/
@ApiModel(description = "object containing data about promotion")
public class BillingOffer implements Serializable{

  @SerializedName("boName")
  private String boName = null;
  @SerializedName("boId")
  private Long boId = null;
  @SerializedName("boInstanceId")
  private Long boInstanceId = null;
  @SerializedName("boPrice")
  private String boPrice = null;
  @SerializedName("allowBoDelete")
  private Boolean allowBoDelete = null;
  @SerializedName("activationDate")
  private Long activationDate = null;
  @SerializedName("deactivationDate")
  private Long deactivationDate = null;
  @SerializedName("contractualPeriod")
  private String contractualPeriod = null;
  @SerializedName("benefitList")
  private List<Benefit> benefitList = null;

  /**
   * billing offer name
   **/
  @ApiModelProperty(value = "billing offer name")
  public String getBoName() {
    return boName;
  }
  public void setBoName(String boName) {
    this.boName = boName;
  }

  /**
   * offer id
   **/
  @ApiModelProperty(required = true, value = "offer id")
  public Long getBoId() {
    return boId;
  }
  public void setBoId(Long boId) {
    this.boId = boId;
  }

  /**
   * offer instance id
   **/
  @ApiModelProperty(value = "offer instance id")
  public Long getBoInstanceId() {
    return boInstanceId;
  }
  public void setBoInstanceId(Long boInstanceId) {
    this.boInstanceId = boInstanceId;
  }

  /**
   * cost for activating offer
   **/
  @ApiModelProperty(value = "cost for activating offer")
  public String getBoPrice() {
    return boPrice;
  }
  public void setBoPrice(String boPrice) {
    this.boPrice = boPrice;
  }

  /**
   * allow an offer to be removed, according to a business configured specific set of srvIds
   **/
  @ApiModelProperty(value = "allow an offer to be removed, according to a business configured specific set of srvIds")
  public Boolean getAllowBoDelete() {
    return allowBoDelete;
  }
  public void setAllowBoDelete(Boolean allowBoDelete) {
    this.allowBoDelete = allowBoDelete;
  }

  /**
   * start date for active offer
   **/
  @ApiModelProperty(value = "start date for active offer")
  public Long getActivationDate() {
    return activationDate;
  }
  public void setActivationDate(Long activationDate) {
    this.activationDate = activationDate;
  }

  /**
   * end date for active offer
   **/
  @ApiModelProperty(value = "end date for active offer")
  public Long getDeactivationDate() {
    return deactivationDate;
  }
  public void setDeactivationDate(Long deactivationDate) {
    this.deactivationDate = deactivationDate;
  }

  /**
   * end date for active offer
   **/
  @ApiModelProperty(value = "end date for active offer")
  public String getContractualPeriod() {
    return contractualPeriod;
  }
  public void setContractualPeriod(String contractualPeriod) {
    this.contractualPeriod = contractualPeriod;
  }

  /**
   * link to CMS image for OTT offers
   **/
  @ApiModelProperty(value = "link to CMS image for OTT offers")
  public List<Benefit> getBenefitList() {
    return benefitList;
  }
  public void setBenefitList(List<Benefit> benefitList) {
    this.benefitList = benefitList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingOffer billingOffer = (BillingOffer) o;
    return (this.boName == null ? billingOffer.boName == null : this.boName.equals(billingOffer.boName)) &&
            (this.boId == null ? billingOffer.boId == null : this.boId.equals(billingOffer.boId)) &&
            (this.boInstanceId == null ? billingOffer.boInstanceId == null : this.boInstanceId.equals(billingOffer.boInstanceId)) &&
            (this.boPrice == null ? billingOffer.boPrice == null : this.boPrice.equals(billingOffer.boPrice)) &&
            (this.allowBoDelete == null ? billingOffer.allowBoDelete == null : this.allowBoDelete.equals(billingOffer.allowBoDelete)) &&
            (this.activationDate == null ? billingOffer.activationDate == null : this.activationDate.equals(billingOffer.activationDate)) &&
            (this.deactivationDate == null ? billingOffer.deactivationDate == null : this.deactivationDate.equals(billingOffer.deactivationDate)) &&
            (this.contractualPeriod == null ? billingOffer.contractualPeriod == null : this.contractualPeriod.equals(billingOffer.contractualPeriod)) &&
            (this.benefitList == null ? billingOffer.benefitList == null : this.benefitList.equals(billingOffer.benefitList));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.boName == null ? 0: this.boName.hashCode());
    result = 31 * result + (this.boId == null ? 0: this.boId.hashCode());
    result = 31 * result + (this.boInstanceId == null ? 0: this.boInstanceId.hashCode());
    result = 31 * result + (this.boPrice == null ? 0: this.boPrice.hashCode());
    result = 31 * result + (this.allowBoDelete == null ? 0: this.allowBoDelete.hashCode());
    result = 31 * result + (this.activationDate == null ? 0: this.activationDate.hashCode());
    result = 31 * result + (this.deactivationDate == null ? 0: this.deactivationDate.hashCode());
    result = 31 * result + (this.contractualPeriod == null ? 0: this.contractualPeriod.hashCode());
    result = 31 * result + (this.benefitList == null ? 0: this.benefitList.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingOffer {\n");

    sb.append("  boName: ").append(boName).append("\n");
    sb.append("  boId: ").append(boId).append("\n");
    sb.append("  boInstanceId: ").append(boInstanceId).append("\n");
    sb.append("  boPrice: ").append(boPrice).append("\n");
    sb.append("  allowBoDelete: ").append(allowBoDelete).append("\n");
    sb.append("  activationDate: ").append(activationDate).append("\n");
    sb.append("  deactivationDate: ").append(deactivationDate).append("\n");
    sb.append("  contractualPeriod: ").append(contractualPeriod).append("\n");
    sb.append("  benefitList: ").append(benefitList).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
