package ro.vodafone.mcare.android.client.model.offers.activeOffersEbu; /**
 * API-39  Active offers postpaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 * <p>
 * OpenAPI spec version: 1.3
 * <p>
 * <p>
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.List;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about promotion
 **/
@ApiModel(description = "object containing data about promotion")
public class Promo implements Serializable {

	@SerializedName("promoName")
	private String promoName = null;
	@SerializedName("offerId")
	private Long offerId = null;
	@SerializedName("promoCategory")
	private String promoCategory = null;
	@SerializedName("promoPrice")
	private Double promoPrice = null;
	@SerializedName("allowPromoDelete")
	private Boolean allowPromoDelete = null;
	@SerializedName("activationDate")
	private Long activationDate = null;
	@SerializedName("deactivationDate")
	private Long deactivationDate = null;
	@SerializedName("promoActivationDate")
	private Long promoActivationDate = null;
	@SerializedName("promoDeactivationDate")
	private Long promoDeactivationDate = null;
	@SerializedName("contractualPeriod")
	private String contractualPeriod = null;
	@SerializedName("eShopDescription")
	private String eShopDescription = null;
	@SerializedName("relationType")
	private Boolean relationType = null;
	@SerializedName("isBroken")
	private Boolean isBroken = null;
	@SerializedName("benefitList")
	private List<Benefit> benefitList = null;
	@SerializedName("boList")
	private List<BillingOffer> boList = null;
	@SerializedName("offerInstanceId")
	private Integer offerInstanceId = null;
	@SerializedName("offerImage")
	private String offerImage = null;

	/**
	 * promo name
	 **/
	@ApiModelProperty(required = true, value = "promo name")
	public String getPromoName() {
		return promoName;
	}

	public void setPromoName(String promoName) {
		this.promoName = promoName;
	}

	/**
	 * offer id
	 **/
	@ApiModelProperty(value = "offer id")
	public Long getOfferId() {
		return offerId;
	}

	public void setOfferId(Long offerId) {
		this.offerId = offerId;
	}

	/**
	 * name of category to which the promo belongs
	 **/
	@ApiModelProperty(value = "name of category to which the promo belongs")
	public String getPromoCategory() {
		return promoCategory;
	}

	public void setPromoCategory(String promoCategory) {
		this.promoCategory = promoCategory;
	}

	/**
	 * cost for activating offer
	 **/
	@ApiModelProperty(value = "cost for activating offer")
	public Double getPromoPrice() {
		return promoPrice;
	}

	public void setPromoPrice(Double promoPrice) {
		this.promoPrice = promoPrice;
	}

	/**
	 * allow an offer to be removed, according to a business configured specific set of srvIds
	 **/
	@ApiModelProperty(required = true, value = "allow an offer to be removed, according to a business configured specific set of srvIds")
	public Boolean getAllowPromoDelete() {
		return allowPromoDelete;
	}

	public void setAllowPromoDelete(Boolean allowPromoDelete) {
		this.allowPromoDelete = allowPromoDelete;
	}

	/**
	 * start date for active offer
	 **/
	@ApiModelProperty(value = "start date for active offer")
	public Long getActivationDate() {
		return activationDate;
	}

	public void setActivationDate(Long activationDate) {
		this.activationDate = activationDate;
	}

	/**
	 * end date for active offer
	 **/
	@ApiModelProperty(value = "end date for active offer")
	public Long getDeactivationDate() {
		return deactivationDate;
	}

	public void setDeactivationDate(Long deactivationDate) {
		this.deactivationDate = deactivationDate;
	}

	/**
	 * end date for active offer
	 **/

	/**
	 * start date for active offer
	 **/
	@ApiModelProperty(value = "start date for active offer")
	public Long getPromoActivationDate() {
		return promoActivationDate;
	}

	public void setPromoActivationDate(Long promoActivationDate) {
		this.promoActivationDate = promoActivationDate;
	}

	/**
	 * end date for active offer
	 **/
	@ApiModelProperty(value = "end date for active offer")
	public Long getPromoDeactivationDate() {
		return promoDeactivationDate;
	}

	public void setPromoDeactivationDate(Long promoDeactivationDate) {
		this.promoDeactivationDate = promoDeactivationDate;
	}

	/**
	 * end date for active offer
	 **/
	@ApiModelProperty(value = "end date for active offer")
	public String getContractualPeriod() {
		return contractualPeriod;
	}

	public void setContractualPeriod(String contractualPeriod) {
		this.contractualPeriod = contractualPeriod;
	}

	/**
	 * eShop description
	 **/
	@ApiModelProperty(value = "eShop description")
	public String getEShopDescription() {
		return eShopDescription;
	}

	public void setEShopDescription(String eShopDescription) {
		this.eShopDescription = eShopDescription;
	}

	/**
	 * Relation type
	 **/
	@ApiModelProperty(value = "Relation type")
	public Boolean getRelationType() {
		return relationType;
	}

	public void setRelationType(Boolean relationType) {
		this.relationType = relationType;
	}

	/**
	 * Broken indicator
	 **/
	@ApiModelProperty(value = "Broken indicator")
	public Boolean getIsBroken() {
		return isBroken;
	}

	public void setIsBroken(Boolean isBroken) {
		this.isBroken = isBroken;
	}

	/**
	 * link to CMS image for OTT offers
	 **/
	@ApiModelProperty(value = "link to CMS image for OTT offers")
	public List<Benefit> getBenefitList() {
		return benefitList;
	}

	public void setBenefitList(List<Benefit> benefitList) {
		this.benefitList = benefitList;
	}

	/**
	 * BO list
	 **/
	@ApiModelProperty(value = "BO list")
	public List<BillingOffer> getBoList() {
		return boList;
	}

	public void setBoList(List<BillingOffer> boList) {
		this.boList = boList;
	}

	/**
	 * offerInstanceId
	 **/
	@ApiModelProperty(value = "offerInstanceId")
	public Integer getOfferInstanceId() {
		return offerInstanceId;
	}

	public void setOfferInstanceId(Integer offerInstanceId) {
		this.offerInstanceId = offerInstanceId;
	}

	public String getOfferImage() {
		return offerImage;
	}

	public void setOfferImage(String offerImage) {
		this.offerImage = offerImage;
	}

	public AdditionalPromosCategoryEnum getCategoryEnum() {
		return AdditionalPromosCategoryEnum.getCategoryByString(promoCategory);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		Promo promo = (Promo) o;
		return (this.promoName == null ? promo.promoName == null : this.promoName.equals(promo.promoName)) &&
				(this.offerId == null ? promo.offerId == null : this.offerId.equals(promo.offerId)) &&
				(this.promoCategory == null ? promo.promoCategory == null : this.promoCategory.equals(promo.promoCategory)) &&
				(this.promoPrice == null ? promo.promoPrice == null : this.promoPrice.equals(promo.promoPrice)) &&
				(this.allowPromoDelete == null ? promo.allowPromoDelete == null : this.allowPromoDelete.equals(promo.allowPromoDelete)) &&
				(this.promoActivationDate == null ? promo.promoActivationDate == null : this.promoActivationDate.equals(promo.promoActivationDate)) &&
				(this.promoDeactivationDate == null ? promo.promoDeactivationDate == null : this.promoDeactivationDate.equals(promo.promoDeactivationDate)) &&
				(this.activationDate == null ? promo.activationDate == null : this.activationDate.equals(promo.activationDate)) &&
				(this.deactivationDate == null ? promo.deactivationDate == null : this.deactivationDate.equals(promo.deactivationDate)) &&
				(this.contractualPeriod == null ? promo.contractualPeriod == null : this.contractualPeriod.equals(promo.contractualPeriod)) &&
				(this.eShopDescription == null ? promo.eShopDescription == null : this.eShopDescription.equals(promo.eShopDescription)) &&
				(this.relationType == null ? promo.relationType == null : this.relationType.equals(promo.relationType)) &&
				(this.isBroken == null ? promo.isBroken == null : this.isBroken.equals(promo.isBroken)) &&
				(this.benefitList == null ? promo.benefitList == null : this.benefitList.equals(promo.benefitList)) &&
				(this.boList == null ? promo.boList == null : this.boList.equals(promo.boList)) &&
				(this.offerInstanceId == null ? promo.offerInstanceId == null : this.offerInstanceId.equals(promo.offerInstanceId));
	}

	@Override
	public int hashCode() {
		int result = 17;
		result = 31 * result + (this.promoName == null ? 0 : this.promoName.hashCode());
		result = 31 * result + (this.offerId == null ? 0 : this.offerId.hashCode());
		result = 31 * result + (this.promoCategory == null ? 0 : this.promoCategory.hashCode());
		result = 31 * result + (this.promoPrice == null ? 0 : this.promoPrice.hashCode());
		result = 31 * result + (this.allowPromoDelete == null ? 0 : this.allowPromoDelete.hashCode());
		result = 31 * result + (this.promoActivationDate == null ? 0 : this.promoActivationDate.hashCode());
		result = 31 * result + (this.promoDeactivationDate == null ? 0 : this.promoDeactivationDate.hashCode());
		result = 31 * result + (this.activationDate == null ? 0 : this.activationDate.hashCode());
		result = 31 * result + (this.deactivationDate == null ? 0 : this.deactivationDate.hashCode());
		result = 31 * result + (this.contractualPeriod == null ? 0 : this.contractualPeriod.hashCode());
		result = 31 * result + (this.eShopDescription == null ? 0 : this.eShopDescription.hashCode());
		result = 31 * result + (this.relationType == null ? 0 : this.relationType.hashCode());
		result = 31 * result + (this.isBroken == null ? 0 : this.isBroken.hashCode());
		result = 31 * result + (this.benefitList == null ? 0 : this.benefitList.hashCode());
		result = 31 * result + (this.boList == null ? 0 : this.boList.hashCode());
		result = 31 * result + (this.offerInstanceId == null ? 0 : this.offerInstanceId.hashCode());
		return result;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class Promo {\n");

		sb.append("  promoName: ").append(promoName).append("\n");
		sb.append("  offerId: ").append(offerId).append("\n");
		sb.append("  promoCategory: ").append(promoCategory).append("\n");
		sb.append("  promoPrice: ").append(promoPrice).append("\n");
		sb.append("  allowPromoDelete: ").append(allowPromoDelete).append("\n");
		sb.append("  promoActivationDate: ").append(promoActivationDate).append("\n");
		sb.append("  promoDeactivationDate: ").append(promoDeactivationDate).append("\n");
		sb.append("  activationDate: ").append(activationDate).append("\n");
		sb.append("  deactivationDate: ").append(deactivationDate).append("\n");
		sb.append("  contractualPeriod: ").append(contractualPeriod).append("\n");
		sb.append("  eShopDescription: ").append(eShopDescription).append("\n");
		sb.append("  relationType: ").append(relationType).append("\n");
		sb.append("  isBroken: ").append(isBroken).append("\n");
		sb.append("  benefitList: ").append(benefitList).append("\n");
		sb.append("  boList: ").append(boList).append("\n");
		sb.append("  offerInstanceId: ").append(offerInstanceId).append("\n");
		sb.append("}\n");
		return sb.toString();
	}
}
