/**
 * API-28  Favorite numbers
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 5.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.favoriteNumbers;

import com.google.gson.annotations.SerializedName;

import java.util.List;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Response object with favorite numbers list.
 **/
@ApiModel(description = "Response object with favorite numbers list.")
public class FavoriteNumbersSuccess extends RealmObject{

  @SerializedName("favoriteNumbers")
  private RealmList<FavoriteNumber> favoriteNumbers = null;

  @PrimaryKey
  private long id_favoriteNumber;

  public FavoriteNumbersSuccess() {
    this.id_favoriteNumber = 1;
  }

  /**
   * list with favorite numbers for recharge
   **/
  @ApiModelProperty(value = "list with favorite numbers for recharge")
  public List<FavoriteNumber> getFavoriteNumbers() {
    return favoriteNumbers;
  }
  public void setFavoriteNumbers(RealmList<FavoriteNumber> favoriteNumbers) {
    this.favoriteNumbers = favoriteNumbers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FavoriteNumbersSuccess favoriteNumbersSuccess = (FavoriteNumbersSuccess) o;
    return (this.favoriteNumbers == null ? favoriteNumbersSuccess.favoriteNumbers == null : this.favoriteNumbers.equals(favoriteNumbersSuccess.favoriteNumbers));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.favoriteNumbers == null ? 0: this.favoriteNumbers.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FavoriteNumbersSuccess {\n");
    
    sb.append("  favoriteNumbers: ").append(favoriteNumbers).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
