/**
 * API-56 Bill Summary
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.billSummary;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Object containing data associated with successful transaction
 **/
@ApiModel(description = "Object containing data associated with successful transaction")
public class BillSummarySuccess extends RealmObject{

  public static final String HIDE_DOWNLOAD_BUTTON = "hideDownloadButton";

  @PrimaryKey
  private long id;
  @SerializedName(HIDE_DOWNLOAD_BUTTON)
  private boolean hideDownloadButton = false;

  @SerializedName("billSummaryList")
  private RealmList<BillSummaryItem> billSummaryList = null;

  public BillSummarySuccess() {
    this.id = 1;
  }

  /**
   * RealmList with bill summary data
   **/
  @ApiModelProperty(value = "RealmList with bill summary data")
  public RealmList<BillSummaryItem> getBillSummaryList() {
    return billSummaryList;
  }
  public void setBillSummaryList(RealmList<BillSummaryItem> billSummaryList) {
    this.billSummaryList = billSummaryList;
  }

  /*
* Flag to hide download ebill button if billMediaType=9 or 10
*/
  @ApiModelProperty(value = "Flag to hide download ebill button if billMediaType=9 or 10")
  public boolean isHideDownloadButton() {
    return hideDownloadButton;
  }

  public void setHideDownloadButton(boolean hideDownloadButton) {
    this.hideDownloadButton = hideDownloadButton;
  }
}
