/**
 * API-20 Cost Control
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.costControl;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class CostControl extends RealmObject{
  
  @SerializedName("lastUpdateDate")
  private Long lastUpdateDate = null;
  @SerializedName("currentExtraoptions")
  private Extraoption currentExtraoptions = null;
  @SerializedName("additionalCost")
  private AdditionalCost additionalCost = null;

  @Ignore
  private RealmList<AdditionalCost> additionalCosts;

  @PrimaryKey
  private long id;

  public CostControl() {
    id = 1;
  }

  /**
   * timestamp in Unix time representing last update
   **/
  @ApiModelProperty(value = "timestamp in Unix time representing last update")
  public Long getLastUpdateDate() {
    return lastUpdateDate;
  }
  public void setLastUpdateDate(Long lastUpdateDate) {
    this.lastUpdateDate = lastUpdateDate;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Extraoption getCurrentExtraoptions() {
    return currentExtraoptions;
  }
  public void setCurrentExtraoptions(Extraoption currentExtraoptions) {
    this.currentExtraoptions = currentExtraoptions;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public AdditionalCost getAdditionalCost() {
    return additionalCost;
  }
  public void setAdditionalCost(AdditionalCost additionalCost) {
    this.additionalCost = additionalCost;
  }

    public RealmList<AdditionalCost> getAdditionalCosts() {
        return additionalCosts;
    }

    public void setAdditionalCosts(RealmList<AdditionalCost> additionalCosts) {
        this.additionalCosts = additionalCosts;
    }


  public long getId() {
    return id;
  }

  public boolean isShortBalanceListValid(){
    return !(currentExtraoptions == null ||
            currentExtraoptions.getShortBalanceList() == null ||
            !currentExtraoptions.getShortBalanceList().isValid() ||
            currentExtraoptions.getShortBalanceList().isEmpty());
  }
}
