/**
 * API-40  Eligible offers postpaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.beo.postpaid.eligibleOffers;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import ro.vodafone.mcare.android.client.model.beo.EligibleOffersInterface;
import ro.vodafone.mcare.android.client.model.offers.activeOffersEbu.AdditionalPromosCategoryEnum;
import ro.vodafone.mcare.android.ui.fragments.Beo.adapter.BeoCategoryEnum;

/**
 * object containing eligible offers grouped by category.
 **/
@ApiModel(description = "object containing eligible offers grouped by category.")
public class EligibleCategoriesPost  extends RealmObject implements EligibleOffersInterface {

  public static final String IS_HIDDEN = "isHidden";

  @PrimaryKey
  @SerializedName("category")
  private String category = null;
  @SerializedName("isHidden")
  private Boolean isHidden = null;
  @SerializedName("eligibleOffersList")
  private RealmList<PostpaidOfferRow> eligibleOffersList = null;

  /**
   * offer category
   **/
  @ApiModelProperty(required = true, value = "offer category")
  public String getCategory() {
    return category;
  }
  public void setCategory(String category) {
    this.category = category;
  }

  /**
   * flag indicating if the category will be displayed to the user
   **/
  @ApiModelProperty(value = "flag indicating if the category will be displayed to the user")
  public Boolean getIsHidden() {
    return isHidden;
  }
  public void setIsHidden(Boolean isHidden) {
    this.isHidden = isHidden;
  }

  /**
   * list with offers eligible for activation belonging to the current category, sorted by priority
   **/
  @ApiModelProperty(required = true, value = "list with offers eligible for activation belonging to the current category, sorted by priority")
  public RealmList<PostpaidOfferRow> getEligibleOffersList() {
    return eligibleOffersList;
  }
  public void setEligibleOffersList(RealmList<PostpaidOfferRow> eligibleOffersList) {
    this.eligibleOffersList = eligibleOffersList;
  }

  public BeoCategoryEnum getCategoryEnum(){
    return BeoCategoryEnum.getCategoryByString(category);
  }
}
