/**
 * API-40  Eligible offers postpaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.beo.postpaid.eligibleOffers;


import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful transaction
 **/
@ApiModel(description = "object containing data associated with successful transaction")
public class EligibleOffersPostSuccess extends RealmObject {

  @PrimaryKey
  private long id;

  @SerializedName("eligibleOptionsCategories")
  private RealmList<EligibleCategoriesPost> eligibleOptionsCategories = null;
  @SerializedName("eligibleServicesCategories")
  private RealmList<EligibleCategoriesPost> eligibleServicesCategories = null;
  @SerializedName("bannerOffers")
  private RealmList<BannerOfferPostPaid> bannerOffers = null;

  public EligibleOffersPostSuccess() {
    id=1;
  }

  /**
   * list with eligible bonuses and options grouped by their respective category. The categories and the order in which they will be displayed is configurable.
   **/
  @ApiModelProperty(value = "list with eligible bonuses and options grouped by their respective category. The categories and the order in which they will be displayed is configurable.")
  public RealmList<EligibleCategoriesPost> getEligibleOptionsCategories() {
    return eligibleOptionsCategories;
  }
  public void setEligibleOptionsCategories(RealmList<EligibleCategoriesPost> eligibleOptionsCategories) {
    this.eligibleOptionsCategories = eligibleOptionsCategories;
  }

  /**
   * list with eligible services grouped by their respective category. The categories and the order in which they will be displayed is configurable.
   **/
  @ApiModelProperty(value = "list with eligible services grouped by their respective category. The categories and the order in which they will be displayed is configurable.")
  public RealmList<EligibleCategoriesPost> getEligibleServicesCategories() {
    return eligibleServicesCategories;
  }
  public void setEligibleServicesCategories(RealmList<EligibleCategoriesPost> eligibleServicesCategories) {
    this.eligibleServicesCategories = eligibleServicesCategories;
  }

  /**
   * Offers for display in banner
   **/
  @ApiModelProperty(value = "Offers for display in banner")
  public RealmList<BannerOfferPostPaid> getBannerOffers() {
    return bannerOffers;
  }
  public void setBannerOffers(RealmList<BannerOfferPostPaid> bannerOffers) {
    this.bannerOffers = bannerOffers;
  }


}
