/**
 * API-40  Eligible offers postpaid
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.beo.postpaid.eligibleOffers;

import com.google.gson.annotations.SerializedName;

import java.util.Comparator;
import java.util.List;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import ro.vodafone.mcare.android.client.model.beo.OfferRowInterface;

/**
 * object containing data about postpaid offer
 **/
@ApiModel(description = "object containing data about postpaid offer")
public class PostpaidOfferRow extends RealmObject implements OfferRowInterface{

  public static final String OFFER_PRIORITY ="offerPriority";
  public static final String MATRIX_ID="matrixId";
  public static final String OFFER_ID="offerId";
  public static final String EXCLUDED_PROMOS_LIST="excludedPromosList";
  public static final String ACTIVATION_DATE="activationDate";
  public static final String DEACTIVATION_DATE="deactivationDate";
  public static final String ACTIVATE_IN_MONTHS="activateInMonths";
  public static final String DEACTIVATE_AFTER_MONTHS="deactivateAfterMonths";

  @PrimaryKey
  @SerializedName("matrixId")
  private String matrixId = null;
  @SerializedName("offerId")
  private Long offerId = null;
  @SerializedName("offerName")
  private String offerName = null;
  @SerializedName("offerCategory")
  private String offerCategory = null;
  @SerializedName("excludedPromosList")
  private RealmList<ExcludedPromo> excludedPromosList = null;
  @SerializedName("offerShortDescription")
  private String offerShortDescription = null;
  @SerializedName("offerDetailedDescription")
  private String offerDetailedDescription = null;
  @SerializedName("offerPriority")
  private Long offerPriority = null;
  @SerializedName("offerPrice")
  private Double offerPrice = null;
  @SerializedName("offerImage")
  private String offerImage = null;
  @SerializedName("activationDate")
  private Long activationDate = null;
  @SerializedName("deactivationDate")
  private Long deactivationDate = null;
  @SerializedName("activateInMonths")
  private Integer activateInMonths = null;
  @SerializedName("deactivateAfterMonths")
  private Integer deactivateAfterMonths = null;

  /**
   * offer id
   **/
  @ApiModelProperty(required = true, value = "offer id")
  public Long getOfferId() {
    return offerId;
  }
  public void setOfferId(Long offerId) {
    this.offerId = offerId;
  }

  /**
   * offer matrix id used for activation
   **/
  @ApiModelProperty(required = true, value = "offer matrix id used for activation")
  public String getMatrixId() {
    return matrixId;
  }
  public void setMatrixId(String matrixId) {
    this.matrixId = matrixId;
  }

  /**
   * offer name
   **/
  @ApiModelProperty(required = true, value = "offer name")
  public String getOfferName() {
    return offerName;
  }
  public void setOfferName(String offerName) {
    this.offerName = offerName;
  }

  /**
   * offer category
   **/
  @ApiModelProperty(value = "offer category")
  public String getOfferCategory() {
    return offerCategory;
  }
  public void setOfferCategory(String offerCategory) {
    this.offerCategory = offerCategory;
  }

  /**
   * List of excluded promos
   **/
  @ApiModelProperty(value = "List of excluded promos")
  public RealmList<ExcludedPromo> getExcludedPromosList() {
    return excludedPromosList;
  }
  public void setExcludedPromosList(RealmList<ExcludedPromo> excludedPromosList) {
    this.excludedPromosList = excludedPromosList;
  }
  
  /**
   * offer description
   **/
  @ApiModelProperty(value = "offer description")
  public String getOfferShortDescription() {
    return offerShortDescription;
  }
  public void setOfferShortDescription(String offerShortDescription) {
    this.offerShortDescription = offerShortDescription;
  }

  /**
   * link containing offer detailed description
   **/
  @ApiModelProperty(value = "link containing offer detailed description")
  public String getOfferDetailedDescription() {
    return offerDetailedDescription;
  }
  public void setOfferDetailedDescription(String offerDetailedDescription) {
    this.offerDetailedDescription = offerDetailedDescription;
  }

  /**
   * priority indicator
   **/
  @ApiModelProperty(value = "priority indicator")
  public Long getOfferPriority() {
    return offerPriority;
  }
  public void setOfferPriority(Long offerPriority) {
    this.offerPriority = offerPriority;
  }

  /**
   * cost for activating offer
   **/
  @ApiModelProperty(required = true, value = "cost for activating offer")
  public Double getOfferPrice() {
    return offerPrice;
  }
  public void setOfferPrice(Double offerPrice) {
    this.offerPrice = offerPrice;
  }

  /**
   * link to CMS image for OTT offers
   **/
  @ApiModelProperty(value = "link to CMS image for OTT offers")
  public String getOfferImage() {
    return offerImage;
  }
  public void setOfferImage(String offerImage) {
    this.offerImage = offerImage;
  }

  /**
   * activation date for promo in long format
   **/
  @ApiModelProperty(value = "activation date for promo in long format")
  public Long getActivationDate() {
    return activationDate;
  }
  public void setActivationDate(Long activationDate) {
    this.activationDate = activationDate;
  }

  /**
   * deactivation date for promo in long format
   **/
  @ApiModelProperty(value = "deactivation date for promo in long format")
  public Long getDeactivationDate() {
    return deactivationDate;
  }
  public void setDeactivationDate(Long deactivationDate) {
    this.deactivationDate = deactivationDate;
  }

  /**
   * activateInMonths date for promo in integer format
   **/
  @ApiModelProperty(value = "activateInMonths date for promo in integer format")
  public Integer getActivateInMonths() {
    return activateInMonths;
  }
  public void setActivateInMonths(Integer activateInMonths) {
    this.activateInMonths = activateInMonths;
  }

  /**
   * deactivateAfterMonths date for promo in integer format
   **/
  @ApiModelProperty(value = "deactivateAfterMonths date for promo in integer format")
  public Integer getDeactivateAfterMonths() {
    return deactivateAfterMonths;
  }
  public void setDeactivateAfterMonths(Integer deactivateAfterMonths) {
    this.deactivateAfterMonths = deactivateAfterMonths;
  }

  public static Comparator<PostpaidOfferRow> getComparatorAfterPriority(){
    return new Comparator<PostpaidOfferRow>() {
      @Override
      public int compare(PostpaidOfferRow o1, PostpaidOfferRow o2) {

        if (o1.getOfferPriority() != null && o2.getOfferPriority() != null) {
          if (o1.getOfferPriority() == o2.getOfferPriority())
            return 0;
          return o1.getOfferPriority() < o2.getOfferPriority() ? -1 : 1;
        }
        else {
          return 0;
        }
      }
    };
  }
}
