/**
 * API-57 Payment Confirmation
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 10.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.paymentConfirmation;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Object containing data associated with successful transaction
 **/
@ApiModel(description = "Object containing data associated with successful transaction")
public class PaymentConfirmationSuccess {
  
  @SerializedName("paymentCodeFlag")
  private Boolean paymentCodeFlag = null;

  /**
   * Payment code flag
   **/
  @ApiModelProperty(value = "Payment code flag")
  public Boolean getPaymentCodeFlag() {
    return paymentCodeFlag;
  }
  public void setPaymentCodeFlag(Boolean paymentCodeFlag) {
    this.paymentCodeFlag = paymentCodeFlag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentConfirmationSuccess paymentConfirmationSuccess = (PaymentConfirmationSuccess) o;
    return (this.paymentCodeFlag == null ? paymentConfirmationSuccess.paymentCodeFlag == null : this.paymentCodeFlag.equals(paymentConfirmationSuccess.paymentCodeFlag));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.paymentCodeFlag == null ? 0: this.paymentCodeFlag.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentConfirmationSuccess {\n");
    
    sb.append("  paymentCodeFlag: ").append(paymentCodeFlag).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
