/**
 * API-51 Shop Orders
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.orders;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about Payment Details
 **/
@ApiModel(description = "object containing data about Payment Details")
public class ShopPaymentDetails extends RealmObject {
  
  @SerializedName("paymentMethod")
  private String paymentMethod = null;
  @SerializedName("address")
  private String address = null;

  /**
   * payment method summary
   **/
  @ApiModelProperty(value = "payment method summary")
  public String getPaymentMethod() {
    return paymentMethod;
  }
  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  /**
   * address description
   **/
  @ApiModelProperty(value = "address description")
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopPaymentDetails shopPaymentDetails = (ShopPaymentDetails) o;
    return (this.paymentMethod == null ? shopPaymentDetails.paymentMethod == null : this.paymentMethod.equals(shopPaymentDetails.paymentMethod)) &&
        (this.address == null ? shopPaymentDetails.address == null : this.address.equals(shopPaymentDetails.address));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.paymentMethod == null ? 0: this.paymentMethod.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopPaymentDetails {\n");
    
    sb.append("  paymentMethod: ").append(paymentMethod).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
