/**
 * API-51 Shop Orders
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.orders;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about Order
 **/
@ApiModel(description = "object containing data about Order")
public class ShopOrder extends RealmObject {
  
  @SerializedName("orderId")
  private String orderId = null;
  @SerializedName("paymentDetails")
  private ShopPaymentDetails paymentDetails = null;
  @SerializedName("costsInfo")
  private ShopCostsInfo costsInfo = null;
  @SerializedName("deliveryInfo")
  private ShopDeliveryInfo deliveryInfo = null;
  @SerializedName("commerceItems")
  private RealmList<ShopCommerceItem> commerceItems = null;

  /**
   * unique identifier for phone product
   **/
  @ApiModelProperty(required = true, value = "unique identifier for phone product")
  public String getOrderId() {
    return orderId;
  }
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ShopPaymentDetails getPaymentDetails() {
    return paymentDetails;
  }
  public void setPaymentDetails(ShopPaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ShopCostsInfo getCostsInfo() {
    return costsInfo;
  }
  public void setCostsInfo(ShopCostsInfo costsInfo) {
    this.costsInfo = costsInfo;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public ShopDeliveryInfo getDeliveryInfo() {
    return deliveryInfo;
  }
  public void setDeliveryInfo(ShopDeliveryInfo deliveryInfo) {
    this.deliveryInfo = deliveryInfo;
  }

  /**
   * list of Shop Commerce Items
   **/
  @ApiModelProperty(value = "list of Shop Commerce Items")
  public RealmList<ShopCommerceItem> getCommerceItems() {
    return commerceItems;
  }
  public void setCommerceItems(RealmList<ShopCommerceItem> commerceItems) {
    this.commerceItems = commerceItems;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopOrder shopOrder = (ShopOrder) o;
    return (this.orderId == null ? shopOrder.orderId == null : this.orderId.equals(shopOrder.orderId)) &&
        (this.paymentDetails == null ? shopOrder.paymentDetails == null : this.paymentDetails.equals(shopOrder.paymentDetails)) &&
        (this.costsInfo == null ? shopOrder.costsInfo == null : this.costsInfo.equals(shopOrder.costsInfo)) &&
        (this.deliveryInfo == null ? shopOrder.deliveryInfo == null : this.deliveryInfo.equals(shopOrder.deliveryInfo)) &&
        (this.commerceItems == null ? shopOrder.commerceItems == null : this.commerceItems.equals(shopOrder.commerceItems));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.orderId == null ? 0: this.orderId.hashCode());
    result = 31 * result + (this.paymentDetails == null ? 0: this.paymentDetails.hashCode());
    result = 31 * result + (this.costsInfo == null ? 0: this.costsInfo.hashCode());
    result = 31 * result + (this.deliveryInfo == null ? 0: this.deliveryInfo.hashCode());
    result = 31 * result + (this.commerceItems == null ? 0: this.commerceItems.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopOrder {\n");
    
    sb.append("  orderId: ").append(orderId).append("\n");
    sb.append("  paymentDetails: ").append(paymentDetails).append("\n");
    sb.append("  costsInfo: ").append(costsInfo).append("\n");
    sb.append("  deliveryInfo: ").append(deliveryInfo).append("\n");
    sb.append("  commerceItems: ").append(commerceItems).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
