/**
 * API-51 Shop Orders
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.orders;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data about Delivery Info
 **/
@ApiModel(description = "object containing data about Delivery Info")
public class ShopCommerceItem extends RealmObject {
  
  @SerializedName("displayImageUrl")
  private String displayImageUrl = null;
  @SerializedName("retentionNumber")
  private String retentionNumber = null;
  @SerializedName("phoneDisplayName")
  private String phoneDisplayName = null;
  @SerializedName("type")
  private String type = null;
  @SerializedName("pricePlanSkuId")
  private String pricePlanSkuId = null;
  @SerializedName("pricePlanContractPeriod")
  private String pricePlanContractPeriod = null;
  @SerializedName("bundlePrice")
  private Float bundlePrice = null;
  @SerializedName("pricePlanMonthlyFee")
  private Float pricePlanMonthlyFee = null;
  @SerializedName("pricePlanDisplayName")
  private String pricePlanDisplayName = null;

  /**
   * displayImageUrl
   **/
  @ApiModelProperty(value = "displayImageUrl")
  public String getDisplayImageUrl() {
    return displayImageUrl;
  }
  public void setDisplayImageUrl(String displayImageUrl) {
    this.displayImageUrl = displayImageUrl;
  }

  /**
   * retentionNumber
   **/
  @ApiModelProperty(value = "retentionNumber")
  public String getRetentionNumber() {
    return retentionNumber;
  }
  public void setRetentionNumber(String retentionNumber) {
    this.retentionNumber = retentionNumber;
  }

  /**
   * phoneDisplayName
   **/
  @ApiModelProperty(value = "phoneDisplayName")
  public String getPhoneDisplayName() {
    return phoneDisplayName;
  }
  public void setPhoneDisplayName(String phoneDisplayName) {
    this.phoneDisplayName = phoneDisplayName;
  }

  /**
   * item type
   **/
  @ApiModelProperty(value = "item type")
  public String getType() {
    return type;
  }
  public void setType(String type) {
    this.type = type;
  }

  /**
   * pricePlanSkuId
   **/
  @ApiModelProperty(value = "pricePlanSkuId")
  public String getPricePlanSkuId() {
    return pricePlanSkuId;
  }
  public void setPricePlanSkuId(String pricePlanSkuId) {
    this.pricePlanSkuId = pricePlanSkuId;
  }

  /**
   * pricePlanContractPeriod
   **/
  @ApiModelProperty(value = "pricePlanContractPeriod")
  public String getPricePlanContractPeriod() {
    return pricePlanContractPeriod;
  }
  public void setPricePlanContractPeriod(String pricePlanContractPeriod) {
    this.pricePlanContractPeriod = pricePlanContractPeriod;
  }

  /**
   * bundlePrice
   **/
  @ApiModelProperty(value = "bundlePrice")
  public Float getBundlePrice() {
    return bundlePrice;
  }
  public void setBundlePrice(Float bundlePrice) {
    this.bundlePrice = bundlePrice;
  }

  /**
   * pricePlanMonthlyFee
   **/
  @ApiModelProperty(value = "pricePlanMonthlyFee")
  public Float getPricePlanMonthlyFee() {
    return pricePlanMonthlyFee;
  }
  public void setPricePlanMonthlyFee(Float pricePlanMonthlyFee) {
    this.pricePlanMonthlyFee = pricePlanMonthlyFee;
  }

  /**
   * pricePlanDisplayName
   **/
  @ApiModelProperty(value = "pricePlanDisplayName")
  public String getPricePlanDisplayName() {
    return pricePlanDisplayName;
  }
  public void setPricePlanDisplayName(String pricePlanDisplayName) {
    this.pricePlanDisplayName = pricePlanDisplayName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopCommerceItem shopCommerceItem = (ShopCommerceItem) o;
    return (this.displayImageUrl == null ? shopCommerceItem.displayImageUrl == null : this.displayImageUrl.equals(shopCommerceItem.displayImageUrl)) &&
        (this.retentionNumber == null ? shopCommerceItem.retentionNumber == null : this.retentionNumber.equals(shopCommerceItem.retentionNumber)) &&
        (this.phoneDisplayName == null ? shopCommerceItem.phoneDisplayName == null : this.phoneDisplayName.equals(shopCommerceItem.phoneDisplayName)) &&
        (this.type == null ? shopCommerceItem.type == null : this.type.equals(shopCommerceItem.type)) &&
        (this.pricePlanSkuId == null ? shopCommerceItem.pricePlanSkuId == null : this.pricePlanSkuId.equals(shopCommerceItem.pricePlanSkuId)) &&
        (this.pricePlanContractPeriod == null ? shopCommerceItem.pricePlanContractPeriod == null : this.pricePlanContractPeriod.equals(shopCommerceItem.pricePlanContractPeriod)) &&
        (this.bundlePrice == null ? shopCommerceItem.bundlePrice == null : this.bundlePrice.equals(shopCommerceItem.bundlePrice)) &&
        (this.pricePlanMonthlyFee == null ? shopCommerceItem.pricePlanMonthlyFee == null : this.pricePlanMonthlyFee.equals(shopCommerceItem.pricePlanMonthlyFee)) &&
        (this.pricePlanDisplayName == null ? shopCommerceItem.pricePlanDisplayName == null : this.pricePlanDisplayName.equals(shopCommerceItem.pricePlanDisplayName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.displayImageUrl == null ? 0: this.displayImageUrl.hashCode());
    result = 31 * result + (this.retentionNumber == null ? 0: this.retentionNumber.hashCode());
    result = 31 * result + (this.phoneDisplayName == null ? 0: this.phoneDisplayName.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.pricePlanSkuId == null ? 0: this.pricePlanSkuId.hashCode());
    result = 31 * result + (this.pricePlanContractPeriod == null ? 0: this.pricePlanContractPeriod.hashCode());
    result = 31 * result + (this.bundlePrice == null ? 0: this.bundlePrice.hashCode());
    result = 31 * result + (this.pricePlanMonthlyFee == null ? 0: this.pricePlanMonthlyFee.hashCode());
    result = 31 * result + (this.pricePlanDisplayName == null ? 0: this.pricePlanDisplayName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopCommerceItem {\n");
    
    sb.append("  displayImageUrl: ").append(displayImageUrl).append("\n");
    sb.append("  retentionNumber: ").append(retentionNumber).append("\n");
    sb.append("  phoneDisplayName: ").append(phoneDisplayName).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  pricePlanSkuId: ").append(pricePlanSkuId).append("\n");
    sb.append("  pricePlanContractPeriod: ").append(pricePlanContractPeriod).append("\n");
    sb.append("  bundlePrice: ").append(bundlePrice).append("\n");
    sb.append("  pricePlanMonthlyFee: ").append(pricePlanMonthlyFee).append("\n");
    sb.append("  pricePlanDisplayName: ").append(pricePlanDisplayName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
