/**
 * API-51 Shop Orders
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 7.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.realm.orders;

import com.google.gson.annotations.SerializedName;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * object containing data associated with successful price plans
 **/
@ApiModel(description = "object containing data associated with successful price plans")
public class ShopOrdersSuccess extends RealmObject {
  
  @SerializedName("ordersList")
  private RealmList<ShopOrder> ordersList = null;

  /**
   * list of Shop Products from Catalog
   **/
  @ApiModelProperty(value = "list of Shop Products from Catalog")
  public RealmList<ShopOrder> getOrdersList() {
    return ordersList;
  }
  public void setOrdersList(RealmList<ShopOrder> ordersList) {
    this.ordersList = ordersList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShopOrdersSuccess shopOrdersSuccess = (ShopOrdersSuccess) o;
    return (this.ordersList == null ? shopOrdersSuccess.ordersList == null : this.ordersList.equals(shopOrdersSuccess.ordersList));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.ordersList == null ? 0: this.ordersList.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShopOrdersSuccess {\n");
    
    sb.append("  ordersList: ").append(ordersList).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
