/**
 * API-41  Postpaid offer eligibility and activation
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.beo.postpaid.activation;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Input parameters for activation request
 **/
@ApiModel(description = "Input parameters for activation request")
public class ActivationRequest {
  
  @SerializedName("offerName")
  private String offerName = null;
  @SerializedName("billCycleDate")
  private Integer billCycleDate = null;
  @SerializedName("offerType")
  private String offerType = null;

  public ActivationRequest() {
  }

  public ActivationRequest(String offerName, Integer billCycleDate, String offerType) {
    this.offerName = offerName;
    this.billCycleDate = billCycleDate;
    this.offerType = offerType;
  }

  /**
   * Online name of activated offer
   **/
  @ApiModelProperty(required = true, value = "Online name of activated offer")
  public String getOfferName() {
    return offerName;
  }
  public void setOfferName(String offerName) {
    this.offerName = offerName;
  }

  /**
   * day in month when invoice is issued
   **/
  @ApiModelProperty(required = true, value = "day in month when invoice is issued")
  public Integer getBillCycleDate() {
    return billCycleDate;
  }
  public void setBillCycleDate(Integer billCycleDate) {
    this.billCycleDate = billCycleDate;
  }

  /**
   * Online offer type
   **/
  @ApiModelProperty(value = "Online offer type")
  public String getOfferType() {
    return offerType;
  }
  public void setOfferType(String offerType) {
    this.offerType = offerType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActivationRequest activationRequest = (ActivationRequest) o;
    return (this.offerName == null ? activationRequest.offerName == null : this.offerName.equals(activationRequest.offerName)) &&
        (this.billCycleDate == null ? activationRequest.billCycleDate == null : this.billCycleDate.equals(activationRequest.billCycleDate)) &&
        (this.offerType == null ? activationRequest.offerType == null : this.offerType.equals(activationRequest.offerType));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.offerName == null ? 0: this.offerName.hashCode());
    result = 31 * result + (this.billCycleDate == null ? 0: this.billCycleDate.hashCode());
    result = 31 * result + (this.offerType == null ? 0: this.offerType.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActivationRequest {\n");
    
    sb.append("  offerName: ").append(offerName).append("\n");
    sb.append("  billCycleDate: ").append(billCycleDate).append("\n");
    sb.append("  offerType: ").append(offerType).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
