/**
 * API-41  Postpaid offer eligibility and activation
 * Rest web service exposed by Vodafone API application and consumed by mobile device applications.
 *
 * OpenAPI spec version: 6.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package ro.vodafone.mcare.android.client.model.beo.postpaid.activation;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Object containing offer delete response, returned if only deletion involve additional cost
 **/
@ApiModel(description = "Object containing offer delete response, returned if only deletion involve additional cost")
public class EbuOfferEligibilitySuccess {
  
  @SerializedName("allowDelete")
  private Boolean allowDelete = null;
  @SerializedName("totalCostAmount")
  private Double totalCostAmount = null;
  @SerializedName("totalCostCurrency")
  private String totalCostCurrency = null;

  /**
   * Allow delete flag
   **/
  @ApiModelProperty(required = true, value = "Allow delete flag")
  public Boolean getAllowDelete() {
    return allowDelete;
  }
  public void setAllowDelete(Boolean allowDelete) {
    this.allowDelete = allowDelete;
  }

  /**
   * Amount of money should be paid by user to deactivate offer
   **/
  @ApiModelProperty(value = "Amount of money should be paid by user to deactivate offer")
  public Double getTotalCostAmount() {
    return totalCostAmount;
  }
  public void setTotalCostAmount(Double totalCostAmount) {
    this.totalCostAmount = totalCostAmount;
  }

  /**
   * Currency
   **/
  @ApiModelProperty(value = "Currency")
  public String getTotalCostCurrency() {
    return totalCostCurrency;
  }
  public void setTotalCostCurrency(String totalCostCurrency) {
    this.totalCostCurrency = totalCostCurrency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EbuOfferEligibilitySuccess ebuOfferEligibilitySuccess = (EbuOfferEligibilitySuccess) o;
    return (this.allowDelete == null ? ebuOfferEligibilitySuccess.allowDelete == null : this.allowDelete.equals(ebuOfferEligibilitySuccess.allowDelete)) &&
        (this.totalCostAmount == null ? ebuOfferEligibilitySuccess.totalCostAmount == null : this.totalCostAmount.equals(ebuOfferEligibilitySuccess.totalCostAmount)) &&
        (this.totalCostCurrency == null ? ebuOfferEligibilitySuccess.totalCostCurrency == null : this.totalCostCurrency.equals(ebuOfferEligibilitySuccess.totalCostCurrency));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.allowDelete == null ? 0: this.allowDelete.hashCode());
    result = 31 * result + (this.totalCostAmount == null ? 0: this.totalCostAmount.hashCode());
    result = 31 * result + (this.totalCostCurrency == null ? 0: this.totalCostCurrency.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class EbuOfferEligibilitySuccess {\n");
    
    sb.append("  allowDelete: ").append(allowDelete).append("\n");
    sb.append("  totalCostAmount: ").append(totalCostAmount).append("\n");
    sb.append("  totalCostCurrency: ").append(totalCostCurrency).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
